name: health_connector_hc_android
resolution: workspace
description: Android implementation of health_connector using Health Connect
version: 2.3.1
repository: https://github.com/fam-tung-lam/health_connector/tree/main/packages/health_connector_hc_android

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  health_connector_core: ^2.2.3
  health_connector_logger: ^2.0.0
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  health_connector_lint: ^1.2.0
  mocktail: ^1.0.4
  parameterized_test: ^2.0.2
  pigeon: ^26.1.0

flutter:
  plugin:
    platforms:
      android:
        package: com.phamtunglam.health_connector_hc_android
        pluginClass: HealthConnectorHCAndroidPlugin
