import Foundation
import HealthKit

/// Extension to infer the data type from a HealthRecordDto instance.
///
/// ## Why This Extension Exists
///
/// Pigeon has a limitation where base classes and interfaces cannot have fields or properties.
/// Since `HealthRecordDto` is a protocol generated by Pigeon, it cannot have a property directly.
/// This extension provides a workaround by using runtime type checking to determine the
/// data type from the concrete DTO instance.
extension HealthRecordDto {
    var dataType: HealthDataTypeDto {
        get throws {
            switch self {
            case is StepRecordDto:
                return .steps
            case is WeightRecordDto:
                return .weight
            case is HeightRecordDto:
                return .height
            case is BodyFatPercentageRecordDto:
                return .bodyFatPercentage
            case is BodyTemperatureRecordDto:
                return .bodyTemperature
            case is ActiveCaloriesBurnedRecordDto:
                return .activeCaloriesBurned
            case is DistanceRecordDto:
                return .distance
            case is FloorsClimbedRecordDto:
                return .floorsClimbed
            case is WheelchairPushesRecordDto:
                return .wheelchairPushes
            case is HydrationRecordDto:
                return .hydration
            case is LeanBodyMassRecordDto:
                return .leanBodyMass
            case is HeartRateMeasurementRecordDto:
                return .heartRateMeasurementRecord
            case is RestingHeartRateRecordDto:
                return .restingHeartRate
            case is BloodPressureRecordDto:
                return .bloodPressure
            case is SystolicBloodPressureRecordDto:
                return .systolicBloodPressure
            case is DiastolicBloodPressureRecordDto:
                return .diastolicBloodPressure
            case is SleepStageRecordDto:
                return .sleepStageRecord
            case is EnergyNutrientRecordDto:
                return .energyNutrient
            case is CaffeineNutrientRecordDto:
                return .caffeine
            case is ProteinNutrientRecordDto:
                return .protein
            case is TotalCarbohydrateNutrientRecordDto:
                return .totalCarbohydrate
            case is TotalFatNutrientRecordDto:
                return .totalFat
            case is SaturatedFatNutrientRecordDto:
                return .saturatedFat
            case is MonounsaturatedFatNutrientRecordDto:
                return .monounsaturatedFat
            case is PolyunsaturatedFatNutrientRecordDto:
                return .polyunsaturatedFat
            case is CholesterolNutrientRecordDto:
                return .cholesterol
            case is DietaryFiberNutrientRecordDto:
                return .dietaryFiber
            case is SugarNutrientRecordDto:
                return .sugar
            case is VitaminANutrientRecordDto:
                return .vitaminA
            case is VitaminB6NutrientRecordDto:
                return .vitaminB6
            case is VitaminB12NutrientRecordDto:
                return .vitaminB12
            case is VitaminCNutrientRecordDto:
                return .vitaminC
            case is VitaminDNutrientRecordDto:
                return .vitaminD
            case is VitaminENutrientRecordDto:
                return .vitaminE
            case is VitaminKNutrientRecordDto:
                return .vitaminK
            case is ThiaminNutrientRecordDto:
                return .thiamin
            case is RiboflavinNutrientRecordDto:
                return .riboflavin
            case is NiacinNutrientRecordDto:
                return .niacin
            case is FolateNutrientRecordDto:
                return .folate
            case is BiotinNutrientRecordDto:
                return .biotin
            case is PantothenicAcidNutrientRecordDto:
                return .pantothenicAcid
            case is CalciumNutrientRecordDto:
                return .calcium
            case is IronNutrientRecordDto:
                return .iron
            case is MagnesiumNutrientRecordDto:
                return .magnesium
            case is ManganeseNutrientRecordDto:
                return .manganese
            case is PhosphorusNutrientRecordDto:
                return .phosphorus
            case is PotassiumNutrientRecordDto:
                return .potassium
            case is SeleniumNutrientRecordDto:
                return .selenium
            case is SodiumNutrientRecordDto:
                return .sodium
            case is ZincNutrientRecordDto:
                return .zinc
            case is NutritionRecordDto:
                return .nutrition
            case is BloodGlucoseRecordDto:
                return .bloodGlucose
            case is OxygenSaturationRecordDto:
                return .oxygenSaturation
            case is RespiratoryRateRecordDto:
                return .respiratoryRate
            case is Vo2MaxRecordDto:
                return .vo2Max
            default:
                throw HealthConnectorError.invalidArgument(
                    message: "Unknown HealthRecordDto type: \(type(of: self))"
                )
            }
        }
    }
}

/// Extension to convert `HealthDataTypeDto` to HealthKit types.
extension HealthDataTypeDto {
    /// Converts this DTO to a HealthKit `HKSampleType`.
    ///
    /// - Throws: HealthConnectorError if type creation fails
    func toHealthKitSampleType() throws -> HKSampleType {
        switch self {
        // MARK: - Category Types

        case .sleepStageRecord:
            try HKCategoryType.make(from: .sleepAnalysis)

        // MARK: - Correlation Types
        case .bloodPressure:
            try HKCorrelationType.make(from: .bloodPressure)
        case .nutrition:
            try HKCorrelationType.make(from: .food)

        // MARK: - Quantity Types
        case .height:
            try HKQuantityType.make(from: .height)
        case .weight:
            try HKQuantityType.make(from: .bodyMass)
        case .leanBodyMass:
            try HKQuantityType.make(from: .leanBodyMass)
        case .bodyFatPercentage:
            try HKQuantityType.make(from: .bodyFatPercentage)
        case .bodyTemperature:
            try HKQuantityType.make(from: .bodyTemperature)
        case .steps:
            try HKQuantityType.make(from: .stepCount)
        case .activeCaloriesBurned:
            try HKQuantityType.make(from: .activeEnergyBurned)
        case .distance:
            try HKQuantityType.make(from: .distanceWalkingRunning)
        case .floorsClimbed:
            try HKQuantityType.make(from: .flightsClimbed)
        case .wheelchairPushes:
            try HKQuantityType.make(from: .pushCount)
        case .heartRateMeasurementRecord:
            try HKQuantityType.make(from: .heartRate)
        case .restingHeartRate:
            try HKQuantityType.make(from: .restingHeartRate)
        case .oxygenSaturation:
            try HKQuantityType.make(from: .oxygenSaturation)
        case .respiratoryRate:
            try HKQuantityType.make(from: .respiratoryRate)
        case .vo2Max:
            try HKQuantityType.make(from: .vo2Max)
        case .systolicBloodPressure:
            try HKQuantityType.make(from: .bloodPressureSystolic)
        case .diastolicBloodPressure:
            try HKQuantityType.make(from: .bloodPressureDiastolic)
        case .hydration:
            try HKQuantityType.make(from: .dietaryWater)
        case .energyNutrient:
            try HKQuantityType.make(from: .dietaryEnergyConsumed)
        case .caffeine:
            try HKQuantityType.make(from: .dietaryCaffeine)
        case .protein:
            try HKQuantityType.make(from: .dietaryProtein)
        case .totalCarbohydrate:
            try HKQuantityType.make(from: .dietaryCarbohydrates)
        case .totalFat:
            try HKQuantityType.make(from: .dietaryFatTotal)
        case .saturatedFat:
            try HKQuantityType.make(from: .dietaryFatSaturated)
        case .monounsaturatedFat:
            try HKQuantityType.make(from: .dietaryFatMonounsaturated)
        case .polyunsaturatedFat:
            try HKQuantityType.make(from: .dietaryFatPolyunsaturated)
        case .cholesterol:
            try HKQuantityType.make(from: .dietaryCholesterol)
        case .dietaryFiber:
            try HKQuantityType.make(from: .dietaryFiber)
        case .sugar:
            try HKQuantityType.make(from: .dietarySugar)
        case .vitaminA:
            try HKQuantityType.make(from: .dietaryVitaminA)
        case .vitaminB6:
            try HKQuantityType.make(from: .dietaryVitaminB6)
        case .vitaminB12:
            try HKQuantityType.make(from: .dietaryVitaminB12)
        case .vitaminC:
            try HKQuantityType.make(from: .dietaryVitaminC)
        case .vitaminD:
            try HKQuantityType.make(from: .dietaryVitaminD)
        case .vitaminE:
            try HKQuantityType.make(from: .dietaryVitaminE)
        case .vitaminK:
            try HKQuantityType.make(from: .dietaryVitaminK)
        case .thiamin:
            try HKQuantityType.make(from: .dietaryThiamin)
        case .riboflavin:
            try HKQuantityType.make(from: .dietaryRiboflavin)
        case .niacin:
            try HKQuantityType.make(from: .dietaryNiacin)
        case .folate:
            try HKQuantityType.make(from: .dietaryFolate)
        case .biotin:
            try HKQuantityType.make(from: .dietaryBiotin)
        case .pantothenicAcid:
            try HKQuantityType.make(from: .dietaryPantothenicAcid)
        case .calcium:
            try HKQuantityType.make(from: .dietaryCalcium)
        case .iron:
            try HKQuantityType.make(from: .dietaryIron)
        case .magnesium:
            try HKQuantityType.make(from: .dietaryMagnesium)
        case .manganese:
            try HKQuantityType.make(from: .dietaryManganese)
        case .phosphorus:
            try HKQuantityType.make(from: .dietaryPhosphorus)
        case .potassium:
            try HKQuantityType.make(from: .dietaryPotassium)
        case .selenium:
            try HKQuantityType.make(from: .dietarySelenium)
        case .sodium:
            try HKQuantityType.make(from: .dietarySodium)
        case .zinc:
            try HKQuantityType.make(from: .dietaryZinc)
        case .bloodGlucose:
            try HKQuantityType.make(from: .bloodGlucose)
        }
    }
}
