import Foundation
import HealthKit

/**
 * Extension to infer the data type from a HealthRecordDto instance.
 *
 * ## Why This Extension Exists
 *
 * Pigeon has a limitation where base classes and interfaces cannot have fields or properties.
 * Since `HealthRecordDto` is a protocol generated by Pigeon, it cannot have a property directly.
 * This extension provides a workaround by using runtime type checking to determine the
 * data type from the concrete DTO instance.
 */
extension HealthRecordDto {
    var dataType: HealthDataTypeDto {
        get throws {
            switch self {
            case is StepRecordDto:
                return .steps
            case is WeightRecordDto:
                return .weight
            case is HeightRecordDto:
                return .height
            case is BodyFatPercentageRecordDto:
                return .bodyFatPercentage
            case is BodyTemperatureRecordDto:
                return .bodyTemperature
            case is ActiveCaloriesBurnedRecordDto:
                return .activeCaloriesBurned
            case is DistanceRecordDto:
                return .distance
            case is FloorsClimbedRecordDto:
                return .floorsClimbed
            case is WheelchairPushesRecordDto:
                return .wheelchairPushes
            case is HydrationRecordDto:
                return .hydration
            case is LeanBodyMassRecordDto:
                return .leanBodyMass
            case is HeartRateMeasurementRecordDto:
                return .heartRateMeasurementRecord
            case is RestingHeartRateRecordDto:
                return .restingHeartRate
            case is BloodPressureRecordDto:
                return .bloodPressure
            case is SystolicBloodPressureRecordDto:
                return .systolicBloodPressure
            case is DiastolicBloodPressureRecordDto:
                return .diastolicBloodPressure
            case is SleepStageRecordDto:
                return .sleepStageRecord
            case is EnergyNutrientRecordDto:
                return .energyNutrient
            case is CaffeineNutrientRecordDto:
                return .caffeine
            case is ProteinNutrientRecordDto:
                return .protein
            case is TotalCarbohydrateNutrientRecordDto:
                return .totalCarbohydrate
            case is TotalFatNutrientRecordDto:
                return .totalFat
            case is SaturatedFatNutrientRecordDto:
                return .saturatedFat
            case is MonounsaturatedFatNutrientRecordDto:
                return .monounsaturatedFat
            case is PolyunsaturatedFatNutrientRecordDto:
                return .polyunsaturatedFat
            case is CholesterolNutrientRecordDto:
                return .cholesterol
            case is DietaryFiberNutrientRecordDto:
                return .dietaryFiber
            case is SugarNutrientRecordDto:
                return .sugar
            case is VitaminANutrientRecordDto:
                return .vitaminA
            case is VitaminB6NutrientRecordDto:
                return .vitaminB6
            case is VitaminB12NutrientRecordDto:
                return .vitaminB12
            case is VitaminCNutrientRecordDto:
                return .vitaminC
            case is VitaminDNutrientRecordDto:
                return .vitaminD
            case is VitaminENutrientRecordDto:
                return .vitaminE
            case is VitaminKNutrientRecordDto:
                return .vitaminK
            case is ThiaminNutrientRecordDto:
                return .thiamin
            case is RiboflavinNutrientRecordDto:
                return .riboflavin
            case is NiacinNutrientRecordDto:
                return .niacin
            case is FolateNutrientRecordDto:
                return .folate
            case is BiotinNutrientRecordDto:
                return .biotin
            case is PantothenicAcidNutrientRecordDto:
                return .pantothenicAcid
            case is CalciumNutrientRecordDto:
                return .calcium
            case is IronNutrientRecordDto:
                return .iron
            case is MagnesiumNutrientRecordDto:
                return .magnesium
            case is ManganeseNutrientRecordDto:
                return .manganese
            case is PhosphorusNutrientRecordDto:
                return .phosphorus
            case is PotassiumNutrientRecordDto:
                return .potassium
            case is SeleniumNutrientRecordDto:
                return .selenium
            case is SodiumNutrientRecordDto:
                return .sodium
            case is ZincNutrientRecordDto:
                return .zinc
            case is NutritionRecordDto:
                return .nutrition
            case is BloodGlucoseRecordDto:
                return .bloodGlucose
            case is OxygenSaturationRecordDto:
                return .oxygenSaturation
            case is RespiratoryRateRecordDto:
                return .respiratoryRate
            case is Vo2MaxRecordDto:
                return .vo2Max
            default:
                throw HealthConnectorErrors.invalidArgument(
                    message: "Unknown HealthRecordDto type: \(type(of: self))"
                )
            }
        }
    }
}

/**
 * Extension to convert `HealthDataTypeDto` to HealthKit types.
 */
extension HealthDataTypeDto {
    /**
     * Converts this DTO to a HealthKit `HKSampleType`.
     *
     * - Throws: HealthConnectorError if type creation fails
     */
    func toHealthKitSampleType() throws -> HKSampleType {
        switch self {
        // MARK: - Category Types

        case .sleepStageRecord:
            try HKCategoryType.safeCategoryType(forIdentifier: .sleepAnalysis)

        // MARK: - Correlation Types
        case .bloodPressure:
            try HKCorrelationType.safeCorrelationType(forIdentifier: .bloodPressure)
        case .nutrition:
            try HKCorrelationType.safeCorrelationType(forIdentifier: .food)

        // MARK: - Quantity Types
        case .height:
            try HKQuantityType.safeQuantityType(forIdentifier: .height)
        case .weight:
            try HKQuantityType.safeQuantityType(forIdentifier: .bodyMass)
        case .leanBodyMass:
            try HKQuantityType.safeQuantityType(forIdentifier: .leanBodyMass)
        case .bodyFatPercentage:
            try HKQuantityType.safeQuantityType(forIdentifier: .bodyFatPercentage)
        case .bodyTemperature:
            try HKQuantityType.safeQuantityType(forIdentifier: .bodyTemperature)
        case .steps:
            try HKQuantityType.safeQuantityType(forIdentifier: .stepCount)
        case .activeCaloriesBurned:
            try HKQuantityType.safeQuantityType(forIdentifier: .activeEnergyBurned)
        case .distance:
            try HKQuantityType.safeQuantityType(forIdentifier: .distanceWalkingRunning)
        case .floorsClimbed:
            try HKQuantityType.safeQuantityType(forIdentifier: .flightsClimbed)
        case .wheelchairPushes:
            try HKQuantityType.safeQuantityType(forIdentifier: .pushCount)
        case .heartRateMeasurementRecord:
            try HKQuantityType.safeQuantityType(forIdentifier: .heartRate)
        case .restingHeartRate:
            try HKQuantityType.safeQuantityType(forIdentifier: .restingHeartRate)
        case .oxygenSaturation:
            try HKQuantityType.safeQuantityType(forIdentifier: .oxygenSaturation)
        case .respiratoryRate:
            try HKQuantityType.safeQuantityType(forIdentifier: .respiratoryRate)
        case .vo2Max:
            try HKQuantityType.safeQuantityType(forIdentifier: .vo2Max)
        case .systolicBloodPressure:
            try HKQuantityType.safeQuantityType(forIdentifier: .bloodPressureSystolic)
        case .diastolicBloodPressure:
            try HKQuantityType.safeQuantityType(forIdentifier: .bloodPressureDiastolic)
        case .hydration:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryWater)
        case .energyNutrient:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryEnergyConsumed)
        case .caffeine:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryCaffeine)
        case .protein:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryProtein)
        case .totalCarbohydrate:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryCarbohydrates)
        case .totalFat:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryFatTotal)
        case .saturatedFat:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryFatSaturated)
        case .monounsaturatedFat:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryFatMonounsaturated)
        case .polyunsaturatedFat:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryFatPolyunsaturated)
        case .cholesterol:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryCholesterol)
        case .dietaryFiber:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryFiber)
        case .sugar:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietarySugar)
        case .vitaminA:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryVitaminA)
        case .vitaminB6:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryVitaminB6)
        case .vitaminB12:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryVitaminB12)
        case .vitaminC:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryVitaminC)
        case .vitaminD:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryVitaminD)
        case .vitaminE:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryVitaminE)
        case .vitaminK:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryVitaminK)
        case .thiamin:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryThiamin)
        case .riboflavin:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryRiboflavin)
        case .niacin:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryNiacin)
        case .folate:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryFolate)
        case .biotin:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryBiotin)
        case .pantothenicAcid:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryPantothenicAcid)
        case .calcium:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryCalcium)
        case .iron:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryIron)
        case .magnesium:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryMagnesium)
        case .manganese:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryManganese)
        case .phosphorus:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryPhosphorus)
        case .potassium:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryPotassium)
        case .selenium:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietarySelenium)
        case .sodium:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietarySodium)
        case .zinc:
            try HKQuantityType.safeQuantityType(forIdentifier: .dietaryZinc)
        case .bloodGlucose:
            try HKQuantityType.safeQuantityType(forIdentifier: .bloodGlucose)
        }
    }
}
