import Foundation
import HealthKit

/// Extension for mapping `HealthDataPermissionDto` → `HKSampleType`.
extension HealthDataPermissionDto {
    /// Converts this `HealthDataPermissionDto` to a list of corresponding `HKSampleType`s.
    ///
    /// - Returns: A list of corresponding `HKSampleType`s for this health data permission.
    ///            For simple types, returns a single-element array.
    ///            For correlation types, returns the correlation type plus all component types.
    /// - Throws: `HealthConnectorError` if type creation fails
    func toHKSampleTypes() throws -> [HKSampleType] {
        switch healthDataType {
        case .activeCaloriesBurned,
             .alcoholicBeverages,
             .exerciseTime,
             .moveTime,
             .standTime,
             .walkingSteadiness,
             .bloodAlcoholContent,
             .basalEnergyBurned,
             .distance,
             .cyclingDistance,
             .cyclingPower,
             .runningPower,
             .cyclingPedalingCadence,
             .cyclingPedalingCadence,
             .swimmingDistance,
             .swimmingStrokes,
             .wheelchairDistance,
             .wheelchairDistance,
             .walkingRunningDistance,
             .downhillSnowSportsDistance,
             .rowingDistance,
             .paddleSportsDistance,
             .crossCountrySkiingDistance,
             .skatingSportsDistance,
             .sixMinuteWalkTestDistance,
             .floorsClimbed,
             .height,
             .hydration,
             .leanBodyMass,
             .bodyFatPercentage,
             .bodyTemperature,
             .basalBodyTemperature,
             .sleepingWristTemperature,
             .steps,
             .weight,
             .wheelchairPushes,
             .heartRateMeasurementRecord,
             .restingHeartRate,
             .sleepStageRecord,
             .sleepStage,
             .dietaryEnergyConsumed,
             .caffeine,
             .protein,
             .totalCarbohydrate,
             .totalFat,
             .saturatedFat,
             .monounsaturatedFat,
             .polyunsaturatedFat,
             .cholesterol,
             .dietaryFiber,
             .sugar,
             .vitaminA,
             .vitaminB6,
             .vitaminB12,
             .vitaminC,
             .vitaminD,
             .vitaminE,
             .vitaminK,
             .thiamin,
             .riboflavin,
             .niacin,
             .folate,
             .biotin,
             .pantothenicAcid,
             .calcium,
             .iron,
             .magnesium,
             .manganese,
             .phosphorus,
             .potassium,
             .selenium,
             .sodium,
             .zinc,
             .systolicBloodPressure,
             .diastolicBloodPressure,
             .oxygenSaturation,
             .respiratoryRate,
             .vo2Max,
             .bloodGlucose,
             .walkingSpeed,
             .runningSpeed,
             .stairAscentSpeed,
             .stairDescentSpeed,
             .bodyMassIndex,
             .waistCircumference,
             .walkingAsymmetryPercentage,
             .walkingDoubleSupportPercentage,
             .walkingStepLength,
             .heartRateVariabilitySDNN,
             .peripheralPerfusionIndex,
             .forcedVitalCapacity,
             .sexualActivity,
             .cervicalMucus,
             .intermenstrualBleeding,
             .menstrualFlow,
             .lactation,
             .contraceptive,
             .ovulationTest,
             .ovulationTestResult,
             .pregnancyTest,
             .progesteroneTest,
             .progesteroneTestResult,
             .pregnancy,
             .exerciseSession,
             .mindfulnessSession,
             .lowHeartRateEvent,
             .irregularHeartRhythmEvent,
             .highHeartRateEvent:
            try [healthDataType.toHKSampleType()]

        // For correlation types HealthKit requires requesting permissions for
        // the individual quantity types, not the correlation type itself
        case .nutrition:
            try getNutritionTypes()

        case .bloodPressure:
            try [
                HealthDataTypeDto.systolicBloodPressure.toHKSampleType(),
                HealthDataTypeDto.diastolicBloodPressure.toHKSampleType(),
            ]
        }
    }

    private func getNutritionTypes() throws -> [HKSampleType] {
        try [
            HealthDataTypeDto.dietaryEnergyConsumed.toHKSampleType(),
            HealthDataTypeDto.caffeine.toHKSampleType(),
            HealthDataTypeDto.protein.toHKSampleType(),
            HealthDataTypeDto.totalCarbohydrate.toHKSampleType(),
            HealthDataTypeDto.totalFat.toHKSampleType(),
            HealthDataTypeDto.saturatedFat.toHKSampleType(),
            HealthDataTypeDto.monounsaturatedFat.toHKSampleType(),
            HealthDataTypeDto.polyunsaturatedFat.toHKSampleType(),
            HealthDataTypeDto.cholesterol.toHKSampleType(),
            HealthDataTypeDto.dietaryFiber.toHKSampleType(),
            HealthDataTypeDto.sugar.toHKSampleType(),
            HealthDataTypeDto.vitaminA.toHKSampleType(),
            HealthDataTypeDto.vitaminB6.toHKSampleType(),
            HealthDataTypeDto.vitaminB12.toHKSampleType(),
            HealthDataTypeDto.vitaminC.toHKSampleType(),
            HealthDataTypeDto.vitaminD.toHKSampleType(),
            HealthDataTypeDto.vitaminE.toHKSampleType(),
            HealthDataTypeDto.vitaminK.toHKSampleType(),
            HealthDataTypeDto.thiamin.toHKSampleType(),
            HealthDataTypeDto.riboflavin.toHKSampleType(),
            HealthDataTypeDto.niacin.toHKSampleType(),
            HealthDataTypeDto.folate.toHKSampleType(),
            HealthDataTypeDto.biotin.toHKSampleType(),
            HealthDataTypeDto.pantothenicAcid.toHKSampleType(),
            HealthDataTypeDto.calcium.toHKSampleType(),
            HealthDataTypeDto.iron.toHKSampleType(),
            HealthDataTypeDto.magnesium.toHKSampleType(),
            HealthDataTypeDto.manganese.toHKSampleType(),
            HealthDataTypeDto.phosphorus.toHKSampleType(),
            HealthDataTypeDto.potassium.toHKSampleType(),
            HealthDataTypeDto.selenium.toHKSampleType(),
            HealthDataTypeDto.sodium.toHKSampleType(),
            HealthDataTypeDto.zinc.toHKSampleType(),
            HealthDataTypeDto.hydration.toHKSampleType(),
        ]
    }
}
