name: health_connector_lint
resolution: workspace
description: Lint rules for health_connector packages
version: 1.2.0
repository: https://github.com/fam-tung-lam/health_connector/tree/main/packages/health_connector_lint

topics:
  - lints

environment:
  sdk: ^3.9.2

dependencies:
  lints: ^6.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
