import 'package:health_connector_logger/src/health_connector_logger.dart'
    show LogLevel;
import 'package:meta/meta.dart';

/// A structured log event emitted by `HealthConnectorLogger`.
///
/// Represents a single log entry with all associated metadata including
/// the log level, tag, operation, timestamp, and optional contextual data.
///
/// ## Usage
///
/// Subscribe to `HealthConnectorLogger.logs` to receive these events:
///
/// ```dart
/// HealthConnectorLogger.logs.listen((log) {
///   print('${log.level.name}: ${log.operation}');
///   if (log.exception != null) {
///     print('Exception: ${log.exception}');
///   }
/// });
/// ```
///
/// ## Fields
///
/// - [level]: The severity level of the log entry
/// - [tag]: A category identifier for the log (e.g., 'API', 'DATABASE')
/// - [operation]: The operation being logged (e.g., 'readRecords')
/// - [dateTime]: The timestamp when the log was created
/// - [phase]: Optional operation phase (e.g., 'entry', 'completed')
/// - [message]: Optional descriptive message
/// - [context]: Optional contextual data as key-value pairs
/// - [exception]: Optional exception object if an error occurred
/// - [stackTrace]: Optional stack trace associated with an exception
/// - [structuredMessage]: The formatted structured message output
@immutable
class HealthConnectorLog {
  /// The severity level of this log entry.
  final LogLevel level;

  /// A tag for categorizing the log entry.
  ///
  /// Typically represents the source or category of the log,
  /// such as 'API', 'DATABASE', or 'PERMISSIONS'.
  final String tag;

  /// The operation being logged.
  ///
  /// Examples: 'readRecords', 'writeRecords', 'requestPermissions'.
  final String operation;

  /// The timestamp when this log was created.
  final DateTime dateTime;

  /// Optional phase of the operation.
  ///
  /// Examples: 'entry', 'exit', 'succeeded', 'failed'.
  final String? phase;

  /// Optional descriptive message.
  final String? message;

  /// Optional contextual information as key-value pairs.
  ///
  /// Examples: `{'recordCount': 42, 'duration': '123ms'}`.
  final Map<String, dynamic>? context;

  /// Optional exception object if an error occurred.
  final Object? exception;

  /// Optional stack trace associated with the exception.
  final StackTrace? stackTrace;

  /// The formatted structured message.
  ///
  /// This is the JSON-like formatted output generated by the logger's
  /// formatting logic, including all fields with proper indentation.
  final String structuredMessage;

  /// Creates a [HealthConnectorLog] with the specified properties.
  const HealthConnectorLog({
    required this.level,
    required this.tag,
    required this.operation,
    required this.dateTime,
    required this.structuredMessage,
    this.phase,
    this.message,
    this.context,
    this.exception,
    this.stackTrace,
  });

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HealthConnectorLog &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          tag == other.tag &&
          operation == other.operation &&
          dateTime == other.dateTime &&
          phase == other.phase &&
          message == other.message &&
          _mapEquals(context, other.context) &&
          exception == other.exception &&
          stackTrace == other.stackTrace &&
          structuredMessage == other.structuredMessage;

  @override
  int get hashCode =>
      level.hashCode ^
      tag.hashCode ^
      operation.hashCode ^
      dateTime.hashCode ^
      phase.hashCode ^
      message.hashCode ^
      _mapHashCode(context) ^
      exception.hashCode ^
      stackTrace.hashCode ^
      structuredMessage.hashCode;

  @override
  String toString() =>
      'HealthConnectorLog('
      'level: ${level.name}, '
      'tag: $tag, '
      'operation: $operation, '
      'dateTime: $dateTime, '
      'phase: $phase, '
      'message: $message, '
      'context: $context, '
      'exception: $exception, '
      'stackTrace: $stackTrace, '
      'structuredMessage: $structuredMessage'
      ')';

  /// Helper method for comparing maps in equality check.
  static bool _mapEquals(
    Map<String, dynamic>? a,
    Map<String, dynamic>? b,
  ) {
    if (identical(a, b)) {
      return true;
    }
    if (a == null || b == null) {
      return false;
    }
    if (a.length != b.length) {
      return false;
    }

    for (final key in a.keys) {
      if (!b.containsKey(key) || a[key] != b[key]) {
        return false;
      }
    }
    return true;
  }

  /// Helper method for computing hash code of a map.
  static int _mapHashCode(Map<String, dynamic>? map) {
    if (map == null) {
      return 0;
    }
    var hash = 0;
    for (final entry in map.entries) {
      hash ^= entry.key.hashCode ^ entry.value.hashCode;
    }
    return hash;
  }
}
