name: health_connector
resolution: workspace
description: A Flutter plugin to access health data from Health Connect (Android) and HealthKit (iOS)
version: 0.1.0
homepage: https://github.com/fam-tung-lam/health_connector
repository: https://github.com/fam-tung-lam/health_connector/tree/main/packages/health_connector

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  health_connector_core:
    path: ../health_connector_core
  health_connector_hc_android:
    path: ../health_connector_hc_android
  health_connector_hk_ios:
    path: ../health_connector_hk_ios
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  health_connector_lint: ^0.1.1

license: Apache-2.0