name: health_connector
resolution: workspace
description: The most comprehensive Flutter health plugin for seamless iOS HealthKit and Android Health Connect integration.
version: 2.3.2
homepage: https://github.com/fam-tung-lam/health_connector
repository: https://github.com/fam-tung-lam/health_connector/tree/main/packages/health_connector

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  health_connector_core: ^2.2.3
  health_connector_hc_android: ^2.3.1
  health_connector_hk_ios: ^2.2.2
  health_connector_logger: ^2.0.0
  meta: ^1.16.0

dev_dependencies:
  health_connector_lint: ^1.2.0
  mocktail: ^1.0.4
  parameterized_test: ^2.0.2
  test: ^1.24.0

platforms:
  android:
  ios:
