name: health_connector
resolution: workspace
description: A Flutter plugin to access health data from Android Health Connect and iOS HealthKit
version: 2.1.0
homepage: https://github.com/fam-tung-lam/health_connector
repository: https://github.com/fam-tung-lam/health_connector/tree/main/packages/health_connector

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  health_connector_core: ^2.1.0
  health_connector_hc_android: ^2.1.0
  health_connector_hk_ios: ^2.1.0
  health_connector_logger: ^2.0.0
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  health_connector_lint: ^1.2.0

platforms:
  android:
  ios:
