name: health_connector_core
resolution: workspace
description: Core models, utilities, and platform interface for Health Connector
version: 2.2.0
repository: https://github.com/fam-tung-lam/health_connector/tree/main/packages/health_connector_core

environment:
  sdk: ^3.9.2

dependencies:
  health_connector_logger: ^2.0.0
  meta: ^1.16.0

dev_dependencies:
  health_connector_lint: ^1.2.0
  mocktail: ^1.0.4
  parameterized_test: ^2.0.2
  test: ^1.24.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
