name: health_connector_core
resolution: workspace
description: Core models, utilities, and platform interface for Health Connector
version: 0.1.0
repository: https://github.com/fam-tung-lam/health_connector/tree/main/packages/health_connector_core

environment:
  sdk: ^3.9.2

dependencies:
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  health_connector_lint: ^0.1.0
