name: 'Setup Gradle'
description: 'Setup Gradle with caching'

runs:
  using: 'composite'
  steps:
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@da187c8e6ffbd3802e00f2477aa5a822b25f2dda # v4.4.4
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}
        gradle-home-cache-cleanup: true
