import Foundation

/// Protocol for types that can be serialized to and from strings for metadata storage.
///
/// This protocol is used instead of `RawRepresentable<String>` because many DTO enums
/// are generated by Pigeon with `Int` raw values, making it impossible to add a second
/// `RawRepresentable` conformance with `String`.
protocol StringSerializable {
    /// Converts this value to a string for storage in HKMetadata.
    func toMetadataString() -> String

    /// Creates an instance from a metadata string.
    /// - Parameter string: The string value from metadata
    /// - Returns: The deserialized value, or `nil` if the string is invalid
    static func fromMetadataString(_ string: String) -> Self?
}

/// Specialized protocol for enum-backed metadata values stored as strings.
///
/// Uses `StringSerializable` instead of `RawRepresentable` to avoid conflicts
/// with Pigeon-generated DTOs that have `Int` raw values.
///
/// ## Usage
///
/// 1. Make your DTO enum conform to `StringSerializable`:
///
/// ```swift
/// extension MindfulnessSessionTypeDto: StringSerializable {
///     func toMetadataString() -> String {
///         switch self {
///         case .unknown: return "unknown"
///         case .meditation: return "meditation"
///         // ...
///         }
///     }
///
///     static func fromMetadataString(_ string: String) -> Self? {
///         switch string {
///         case "unknown": return .unknown
///         case "meditation": return .meditation
///         // ...
///         default: return nil
///         }
///     }
/// }
/// ```
///
/// 2. Define your key using `StringEnumMetadataKey`:
///
/// ```swift
/// enum SessionTypeKey: StringEnumMetadataKey {
///     typealias Value = MindfulnessSessionTypeDto
///     static let keySuffix = "session_type"
///     static let defaultValue: MindfulnessSessionTypeDto = .unknown
/// }
/// ```
protocol StringEnumMetadataKey: CustomMetadataKey
    where Value: StringSerializable
{
    /// The default value to use when deserialization fails.
    ///
    /// This is typically `.unknown` for enum types that have an unknown case.
    static var defaultValue: Value { get }
}

// MARK: - Default Implementations

extension StringEnumMetadataKey {
    /// Serializes the enum value to its string representation.
    static func serialize(_ value: Value) -> Any {
        value.toMetadataString()
    }

    /// Deserializes a string to the enum value.
    ///
    /// - Parameter rawValue: The raw value from metadata (expected to be a String)
    /// - Returns: The deserialized enum value, or `nil` if deserialization fails
    static func deserialize(_ rawValue: Any?) -> Value? {
        guard let stringValue = rawValue as? String else { return nil }
        return Value.fromMetadataString(stringValue)
    }

    /// Reads the value from metadata, returning `defaultValue` if not found or invalid.
    ///
    /// - Parameter metadata: The HealthKit metadata dictionary
    /// - Returns: The deserialized value, or `defaultValue` if key is missing or invalid
    static func readOrDefault(from metadata: [String: Any]?) -> Value {
        read(from: metadata) ?? defaultValue
    }
}
