name: health_connector_hk_ios
resolution: workspace
description: iOS implementation of health_connector using HealthKit
version: 2.2.2
repository: https://github.com/fam-tung-lam/health_connector/tree/main/packages/health_connector_hk_ios

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  health_connector_core: ^2.2.3
  health_connector_logger: ^2.0.0
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  health_connector_lint: ^1.2.0
  mocktail: ^1.0.4
  parameterized_test: ^2.0.2
  pigeon: ^26.1.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: HealthConnectorHkIosPlugin
