name: health_connector_hk_ios
resolution: workspace
description: iOS implementation of health_connector using HealthKit
version: 0.1.0
repository: https://github.com/fam-tung-lam/health_connector/tree/main/packages/health_connector_hk_ios

environment:
  sdk: ^3.9.2
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  health_connector_core:
    path: ../health_connector_core
  meta: ^1.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  health_connector_lint: ^0.1.1
  pigeon: ^26.1.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: HealthConnectorHkIosPlugin

license: Apache-2.0