import 'package:health_connector/health_connector_internal.dart'
    show ExerciseType;
import 'package:health_connector_toolbox/src/common/constants/app_texts.dart';

/// Extension providing display names for [ExerciseType] enum values.
extension ExerciseTypeDisplayName on ExerciseType {
  /// Returns the localized display name for this exercise type.
  String get displayName {
    return switch (this) {
      ExerciseType.other => AppTexts.exerciseOtherWorkout,
      ExerciseType.running => AppTexts.exerciseRunning,
      ExerciseType.runningTreadmill => AppTexts.exerciseRunningTreadmill,
      ExerciseType.walking => AppTexts.exerciseWalking,
      ExerciseType.cycling => AppTexts.exerciseCycling,
      ExerciseType.cyclingStationary => AppTexts.exerciseBikingStationary,
      ExerciseType.hiking => AppTexts.exerciseHiking,
      ExerciseType.swimming => AppTexts.exerciseSwimming,
      ExerciseType.swimmingOpenWater => AppTexts.exerciseSwimmingOpenWater,
      ExerciseType.swimmingPool => AppTexts.exerciseSwimmingPool,
      ExerciseType.surfing => AppTexts.exerciseSurfing,
      ExerciseType.waterPolo => AppTexts.exerciseWaterPolo,
      ExerciseType.rowing => AppTexts.exerciseRowing,
      ExerciseType.sailing => AppTexts.exerciseSailing,
      ExerciseType.paddling => AppTexts.exercisePaddling,
      ExerciseType.diving => AppTexts.exerciseScubaDiving,
      ExerciseType.waterFitness => AppTexts.exerciseWaterFitness,
      ExerciseType.waterSports => AppTexts.exerciseWaterSports,
      ExerciseType.strengthTraining => AppTexts.exerciseStrengthTraining,
      ExerciseType.weightlifting => AppTexts.exerciseWeightlifting,
      ExerciseType.calisthenics => AppTexts.exerciseCalisthenics,
      ExerciseType.basketball => AppTexts.exerciseBasketball,
      ExerciseType.soccer => AppTexts.exerciseSoccer,
      ExerciseType.americanFootball => AppTexts.exerciseAmericanFootball,
      ExerciseType.frisbeeDisc => AppTexts.exerciseFrisbeeDisc,
      ExerciseType.australianFootball => AppTexts.exerciseAustralianFootball,
      ExerciseType.baseball => AppTexts.exerciseBaseball,
      ExerciseType.softball => AppTexts.exerciseSoftball,
      ExerciseType.volleyball => AppTexts.exerciseVolleyball,
      ExerciseType.rugby => AppTexts.exerciseRugby,
      ExerciseType.cricket => AppTexts.exerciseCricket,
      ExerciseType.handball => AppTexts.exerciseHandball,
      ExerciseType.iceHockey => AppTexts.exerciseIceHockey,
      ExerciseType.rollerHockey => AppTexts.exerciseRollerHockey,
      ExerciseType.hockey => AppTexts.exerciseHockey,
      ExerciseType.tennis => AppTexts.exerciseTennis,
      ExerciseType.tableTennis => AppTexts.exerciseTableTennis,
      ExerciseType.badminton => AppTexts.exerciseBadminton,
      ExerciseType.squash => AppTexts.exerciseSquash,
      ExerciseType.racquetball => AppTexts.exerciseRacquetball,
      ExerciseType.skiing => AppTexts.exerciseSkiing,
      ExerciseType.snowboarding => AppTexts.exerciseSnowboarding,
      ExerciseType.snowshoeing => AppTexts.exerciseSnowshoeing,
      ExerciseType.skating => AppTexts.exerciseSkating,
      ExerciseType.boxing => AppTexts.exerciseBoxing,
      ExerciseType.kickboxing => AppTexts.exerciseKickboxing,
      ExerciseType.martialArts => AppTexts.exerciseMartialArts,
      ExerciseType.wrestling => AppTexts.exerciseWrestling,
      ExerciseType.fencing => AppTexts.exerciseFencing,
      ExerciseType.dancing => AppTexts.exerciseDancing,
      ExerciseType.gymnastics => AppTexts.exerciseGymnastics,
      ExerciseType.yoga => AppTexts.exerciseYoga,
      ExerciseType.pilates => AppTexts.exercisePilates,
      ExerciseType.highIntensityIntervalTraining => AppTexts.exerciseHIIT,
      ExerciseType.exerciseClass => AppTexts.exerciseExerciseClass,
      ExerciseType.bootCamp => AppTexts.exerciseBootCamp,
      ExerciseType.guidedBreathing => AppTexts.exerciseGuidedBreathing,
      ExerciseType.elliptical => AppTexts.exerciseElliptical,
      ExerciseType.stairClimbing => AppTexts.exerciseStairClimbing,

      ExerciseType.crossTraining => AppTexts.exerciseCrossTraining,
      ExerciseType.jumpRope => AppTexts.exerciseJumpRope,
      ExerciseType.golf => AppTexts.exerciseGolf,
      ExerciseType.paragliding => AppTexts.exerciseParagliding,
      ExerciseType.climbing => AppTexts.exerciseClimbing,
      ExerciseType.wheelchair => AppTexts.exerciseWheelchair,
      ExerciseType.wheelchairWalkPace => AppTexts.exerciseWheelchairWalkPace,
      ExerciseType.wheelchairRunPace => AppTexts.exerciseWheelchairRunPace,

      // Multisport
      ExerciseType.swimBikeRun => AppTexts.exerciseSwimBikeRun,
      // iOS-only types - provide display names for completeness
      ExerciseType.pickleball => AppTexts.exercisePickleball,
      ExerciseType.discSports => AppTexts.exerciseDiscSports,
      ExerciseType.fitnessGaming => AppTexts.exerciseFitnessGaming,
      ExerciseType.barre => AppTexts.exerciseBarre,
      ExerciseType.taiChi => AppTexts.exerciseTaiChi,
      ExerciseType.mixedCardio => AppTexts.exerciseMixedCardio,
      ExerciseType.handCycling => AppTexts.exerciseHandCycling,
      ExerciseType.cooldown => AppTexts.exerciseCooldown,
      ExerciseType.flexibility => AppTexts.exerciseFlexibility,
      ExerciseType.archery => AppTexts.exerciseArchery,
      ExerciseType.bowling => AppTexts.exerciseBowling,
      ExerciseType.curling => AppTexts.exerciseCurling,
      ExerciseType.equestrianSports => AppTexts.exerciseEquestrianSports,
      ExerciseType.fishing => AppTexts.exerciseFishing,
      ExerciseType.hunting => AppTexts.exerciseHunting,
      ExerciseType.lacrosse => AppTexts.exerciseLacrosse,
      ExerciseType.mindAndBody => AppTexts.exerciseMindAndBody,
      ExerciseType.play => AppTexts.exercisePlay,
      ExerciseType.preparationAndRecovery =>
        AppTexts.exercisePreparationAndRecovery,
      ExerciseType.stepTraining => AppTexts.exerciseStepTraining,
      ExerciseType.trackAndField => AppTexts.exerciseTrackAndField,
      ExerciseType.transition => AppTexts.exerciseTransition,
      ExerciseType.crossCountrySkiing => AppTexts.exerciseCrossCountrySkiing,
      ExerciseType.downhillSkiing => AppTexts.exerciseDownhillSkiing,
      ExerciseType.snowSports => AppTexts.exerciseSnowSports,
      ExerciseType.cardioDance => AppTexts.exerciseCardioDance,
      ExerciseType.socialDance => AppTexts.exerciseSocialDance,
      ExerciseType.coreTraining => AppTexts.exerciseCoreTraining,
    };
  }
}
