name: health_connector_logger
resolution: workspace
description: Structured logging utility for Health Connector packages
version: 2.0.0
repository: https://github.com/fam-tung-lam/health_connector/tree/main/packages/health_connector_logger

environment:
  sdk: ^3.9.2

dependencies:
  collection: ^1.19.1
  meta: ^1.16.0
  collection: ^1.19.1

dev_dependencies:
  health_connector_lint: ^1.2.0
  test: ^1.24.0

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
