// Copyright 2025 Pham Tung Lam
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ---
// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class HealthConnectorError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "HealthConnectorError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? HealthConnectorError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsHealthConnectorPlatformApi(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsHealthConnectorPlatformApi(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsHealthConnectorPlatformApi(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashHealthConnectorPlatformApi(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashHealthConnectorPlatformApi(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashHealthConnectorPlatformApi(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

/// Error codes that native platforms can use when throwing error.
public enum HealthConnectorErrorCodeDto: Int {
  /// Health platform is unavailable on this device.
  case healthPlatformUnavailable = 0
  /// Invalid platform configuration detected.
  case invalidPlatformConfiguration = 1
  /// Invalid argument or input validation error.
  case invalidArgument = 2
  /// Attempted to use platform APIs that are not supported on
  /// the current health platform.
  case unsupportedHealthPlatformApi = 3
  /// Unknown or unspecified error.
  case unknown = 4
  /// Security/permission error occurred.
  case securityError = 5
}

/// Represents the status of the health platform on the device.
public enum HealthPlatformStatusDto: Int {
  /// The health platform is available and ready to use.
  case available = 0
  /// The health platform is not available on this device.
  case notAvailable = 1
}

/// Blood glucose unit types supported by the plugin.
public enum BloodGlucoseUnitDto: Int {
  case milligramsPerDeciliter = 0
  case millimolesPerLiter = 1
}

/// Energy unit types supported by the plugin.
public enum EnergyUnitDto: Int {
  case calories = 0
  case joules = 1
  case kilocalories = 2
  case kilojoules = 3
}

/// Length unit types supported by the plugin.
public enum LengthUnitDto: Int {
  case feet = 0
  case inches = 1
  case kilometers = 2
  case meters = 3
  case miles = 4
}

/// Mass unit types supported by the plugin.
public enum MassUnitDto: Int {
  case grams = 0
  case kilograms = 1
  case ounces = 2
  case pounds = 3
}

/// Numeric unit types supported by the plugin.
///
/// Numeric values don't have unit conversions, but this enum is provided
/// for consistency with other unit types.
public enum NumericUnitDto: Int {
  case numeric = 0
}

/// Percentage unit types supported by the plugin.
public enum PercentageUnitDto: Int {
  /// Percentage as a decimal value (0.0 to 1.0).
  case decimal = 0
  /// Percentage as a whole number (0 to 100).
  case whole = 1
}

/// Represents the type of access requested for health data.
public enum PermissionAccessTypeDto: Int {
  /// Read access to health data.
  case read = 0
  /// Write access to health data.
  case write = 1
}

/// Represents the status of a permission.
public enum PermissionStatusDto: Int {
  /// Permission has been explicitly denied by the user.
  case denied = 0
  /// Permission has been explicitly granted by the user.
  case granted = 1
  /// The permission status cannot be determined.
  case unknown = 2
}

/// Pressure unit types supported by the plugin.
public enum PressureUnitDto: Int {
  case millimetersOfMercury = 0
}

/// Power unit types supported by the plugin.
public enum PowerUnitDto: Int {
  case kilowatts = 0
  case watts = 1
}

/// Temperature unit types supported by the plugin.
public enum TemperatureUnitDto: Int {
  case celsius = 0
  case fahrenheit = 1
  case kelvin = 2
}

/// Velocity unit types supported by the plugin.
public enum VelocityUnitDto: Int {
  case kilometersPerHour = 0
  case metersPerSecond = 1
  case milesPerHour = 2
}

/// Volume unit types supported by the plugin.
public enum VolumeUnitDto: Int {
  case fluidOuncesUs = 0
  case liters = 1
  case milliliters = 2
}

/// Represents a health data type.
public enum HealthDataTypeDto: Int {
  /// Active calories burned data.
  case activeCaloriesBurned = 0
  /// Distance traveled data.
  case distance = 1
  /// Floors climbed data.
  case floorsClimbed = 2
  /// Step count data.
  case steps = 3
  /// Body weight data.
  case weight = 4
  /// Body height data.
  case height = 5
  /// Body fat percentage data.
  case bodyFatPercentage = 6
  /// Body temperature data.
  case bodyTemperature = 7
  /// Lean body mass data.
  case leanBodyMass = 8
  /// Wheelchair pushes data.
  case wheelchairPushes = 9
  /// Hydration (water intake) data.
  case hydration = 10
  /// Heart rate measurement record data (iOS).
  case heartRateMeasurementRecord = 11
}

/// Aggregation metric types for health data queries.
public enum AggregationMetricDto: Int {
  /// Average (mean) value across all data points.
  case avg = 0
  /// Count of data points (records) in the dataset.
  case count = 1
  /// Maximum value in the dataset.
  case max = 2
  /// Minimum value in the dataset.
  case min = 3
  /// Sum of all values in the time range.
  case sum = 4
}

/// Sealed class for all measurement unit DTOs.
///
/// Generated class from Pigeon that represents data sent in messages.
/// This protocol should not be extended by any user class outside of the generated file.
protocol MeasurementUnitDto {

}

/// Represents a blood glucose measurement for platform transfer.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct BloodGlucoseDto: MeasurementUnitDto {
  /// The unit in which the value is expressed.
  var unit: BloodGlucoseUnitDto
  /// The numeric value of the blood glucose.
  var value: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BloodGlucoseDto? {
    let unit = pigeonVar_list[0] as! BloodGlucoseUnitDto
    let value = pigeonVar_list[1] as! Double

    return BloodGlucoseDto(
      unit: unit,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      unit,
      value,
    ]
  }
  public static func == (lhs: BloodGlucoseDto, rhs: BloodGlucoseDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Represents an energy measurement for platform transfer.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct EnergyDto: MeasurementUnitDto {
  /// The unit in which the value is expressed.
  var unit: EnergyUnitDto
  /// The numeric value of the energy.
  var value: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EnergyDto? {
    let unit = pigeonVar_list[0] as! EnergyUnitDto
    let value = pigeonVar_list[1] as! Double

    return EnergyDto(
      unit: unit,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      unit,
      value,
    ]
  }
  public static func == (lhs: EnergyDto, rhs: EnergyDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Represents a length measurement for platform transfer.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct LengthDto: MeasurementUnitDto {
  /// The unit in which the value is expressed.
  var unit: LengthUnitDto
  /// The numeric value of the length.
  var value: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LengthDto? {
    let unit = pigeonVar_list[0] as! LengthUnitDto
    let value = pigeonVar_list[1] as! Double

    return LengthDto(
      unit: unit,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      unit,
      value,
    ]
  }
  public static func == (lhs: LengthDto, rhs: LengthDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Represents a mass measurement for platform transfer.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct MassDto: MeasurementUnitDto {
  /// The unit in which the value is expressed.
  var unit: MassUnitDto
  /// The numeric value of the mass.
  var value: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MassDto? {
    let unit = pigeonVar_list[0] as! MassUnitDto
    let value = pigeonVar_list[1] as! Double

    return MassDto(
      unit: unit,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      unit,
      value,
    ]
  }
  public static func == (lhs: MassDto, rhs: MassDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Represents a numeric measurement for platform transfer.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct NumericDto: MeasurementUnitDto {
  /// The unit in which the value is expressed.
  var unit: NumericUnitDto
  /// The numeric value.
  var value: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NumericDto? {
    let unit = pigeonVar_list[0] as! NumericUnitDto
    let value = pigeonVar_list[1] as! Double

    return NumericDto(
      unit: unit,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      unit,
      value,
    ]
  }
  public static func == (lhs: NumericDto, rhs: NumericDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Represents a percentage measurement for platform transfer.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct PercentageDto: MeasurementUnitDto {
  /// The unit in which the value is expressed.
  var unit: PercentageUnitDto
  /// The numeric value of the percentage.
  var value: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PercentageDto? {
    let unit = pigeonVar_list[0] as! PercentageUnitDto
    let value = pigeonVar_list[1] as! Double

    return PercentageDto(
      unit: unit,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      unit,
      value,
    ]
  }
  public static func == (lhs: PercentageDto, rhs: PercentageDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Represents a power measurement for platform transfer.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct PowerDto: MeasurementUnitDto {
  /// The unit in which the value is expressed.
  var unit: PowerUnitDto
  /// The numeric value of the power.
  var value: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PowerDto? {
    let unit = pigeonVar_list[0] as! PowerUnitDto
    let value = pigeonVar_list[1] as! Double

    return PowerDto(
      unit: unit,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      unit,
      value,
    ]
  }
  public static func == (lhs: PowerDto, rhs: PowerDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Represents a pressure measurement for platform transfer.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct PressureDto: MeasurementUnitDto {
  /// The unit in which the value is expressed.
  var unit: PressureUnitDto
  /// The numeric value of the pressure.
  var value: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PressureDto? {
    let unit = pigeonVar_list[0] as! PressureUnitDto
    let value = pigeonVar_list[1] as! Double

    return PressureDto(
      unit: unit,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      unit,
      value,
    ]
  }
  public static func == (lhs: PressureDto, rhs: PressureDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Represents a temperature measurement for platform transfer.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct TemperatureDto: MeasurementUnitDto {
  /// The unit in which the value is expressed.
  var unit: TemperatureUnitDto
  /// The numeric value of the temperature.
  var value: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> TemperatureDto? {
    let unit = pigeonVar_list[0] as! TemperatureUnitDto
    let value = pigeonVar_list[1] as! Double

    return TemperatureDto(
      unit: unit,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      unit,
      value,
    ]
  }
  public static func == (lhs: TemperatureDto, rhs: TemperatureDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Represents a velocity measurement for platform transfer.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct VelocityDto: MeasurementUnitDto {
  /// The unit in which the value is expressed.
  var unit: VelocityUnitDto
  /// The numeric value of the velocity.
  var value: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VelocityDto? {
    let unit = pigeonVar_list[0] as! VelocityUnitDto
    let value = pigeonVar_list[1] as! Double

    return VelocityDto(
      unit: unit,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      unit,
      value,
    ]
  }
  public static func == (lhs: VelocityDto, rhs: VelocityDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Represents a volume measurement for platform transfer.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct VolumeDto: MeasurementUnitDto {
  /// The unit in which the value is expressed.
  var unit: VolumeUnitDto
  /// The numeric value of the volume.
  var value: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VolumeDto? {
    let unit = pigeonVar_list[0] as! VolumeUnitDto
    let value = pigeonVar_list[1] as! Double

    return VolumeDto(
      unit: unit,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      unit,
      value,
    ]
  }
  public static func == (lhs: VolumeDto, rhs: VolumeDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Represents metadata for a health record.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct MetadataDto: Hashable {
  /// A custom identifier assigned by your application.
  ///
  /// Use this for client-side record tracking, deduplication, or correlation.
  var clientRecordId: String? = nil
  /// A version number assigned by your application.
  ///
  /// Use this to implement your own versioning or tracking logic.
  var clientRecordVersion: Int64? = nil
  /// The package name of the source app that wrote this health record.
  var dataOrigin: String
  /// The name of the device that recorded the data (optional).
  var deviceName: String? = nil
  /// The manufacturer of the device that recorded the data (optional).
  var deviceManufacturer: String? = nil
  /// The model of the device that recorded the data (optional).
  var deviceModel: String? = nil
  /// The hardware version of the device that recorded the data (optional).
  var deviceHardwareVersion: String? = nil
  /// The firmware version of the device that recorded the data (optional).
  var deviceFirmwareVersion: String? = nil
  /// The software version of the device that recorded the data (optional).
  var deviceSoftwareVersion: String? = nil
  /// A local identifier for the device that recorded the data (optional).
  var deviceLocalIdentifier: String? = nil
  /// The UDI (Unique Device Identifier) for the device that recorded the data (optional).
  var deviceUdiDeviceIdentifier: String? = nil
  /// Whether this data was manually entered by the user.
  ///
  /// `true` indicates manual entry, `false` indicates unknown/not manual entry.
  var isManualEntry: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MetadataDto? {
    let clientRecordId: String? = nilOrValue(pigeonVar_list[0])
    let clientRecordVersion: Int64? = nilOrValue(pigeonVar_list[1])
    let dataOrigin = pigeonVar_list[2] as! String
    let deviceName: String? = nilOrValue(pigeonVar_list[3])
    let deviceManufacturer: String? = nilOrValue(pigeonVar_list[4])
    let deviceModel: String? = nilOrValue(pigeonVar_list[5])
    let deviceHardwareVersion: String? = nilOrValue(pigeonVar_list[6])
    let deviceFirmwareVersion: String? = nilOrValue(pigeonVar_list[7])
    let deviceSoftwareVersion: String? = nilOrValue(pigeonVar_list[8])
    let deviceLocalIdentifier: String? = nilOrValue(pigeonVar_list[9])
    let deviceUdiDeviceIdentifier: String? = nilOrValue(pigeonVar_list[10])
    let isManualEntry = pigeonVar_list[11] as! Bool

    return MetadataDto(
      clientRecordId: clientRecordId,
      clientRecordVersion: clientRecordVersion,
      dataOrigin: dataOrigin,
      deviceName: deviceName,
      deviceManufacturer: deviceManufacturer,
      deviceModel: deviceModel,
      deviceHardwareVersion: deviceHardwareVersion,
      deviceFirmwareVersion: deviceFirmwareVersion,
      deviceSoftwareVersion: deviceSoftwareVersion,
      deviceLocalIdentifier: deviceLocalIdentifier,
      deviceUdiDeviceIdentifier: deviceUdiDeviceIdentifier,
      isManualEntry: isManualEntry
    )
  }
  func toList() -> [Any?] {
    return [
      clientRecordId,
      clientRecordVersion,
      dataOrigin,
      deviceName,
      deviceManufacturer,
      deviceModel,
      deviceHardwareVersion,
      deviceFirmwareVersion,
      deviceSoftwareVersion,
      deviceLocalIdentifier,
      deviceUdiDeviceIdentifier,
      isManualEntry,
    ]
  }
  public static func == (lhs: MetadataDto, rhs: MetadataDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Represents a permission request for accessing specific health data.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct HealthDataPermissionDto: Hashable {
  /// The type of access being requested (read or write).
  var accessType: PermissionAccessTypeDto
  /// The type of health data for which permission is requested.
  var healthDataType: HealthDataTypeDto


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HealthDataPermissionDto? {
    let accessType = pigeonVar_list[0] as! PermissionAccessTypeDto
    let healthDataType = pigeonVar_list[1] as! HealthDataTypeDto

    return HealthDataPermissionDto(
      accessType: accessType,
      healthDataType: healthDataType
    )
  }
  func toList() -> [Any?] {
    return [
      accessType,
      healthDataType,
    ]
  }
  public static func == (lhs: HealthDataPermissionDto, rhs: HealthDataPermissionDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Sealed class for all health record DTOs.
///
/// Generated class from Pigeon that represents data sent in messages.
/// This protocol should not be extended by any user class outside of the generated file.
protocol HealthRecordDto {

}

/// Represents an active calories burned record for platform transfer.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct ActiveCaloriesBurnedRecordDto: HealthRecordDto {
  /// Energy (calories) burned during the interval.
  var energy: EnergyDto
  /// End time in milliseconds since epoch (UTC).
  var endTime: Int64
  /// Platform-assigned unique identifier.
  var id: String? = nil
  /// Metadata about this record.
  var metadata: MetadataDto
  /// Start time in milliseconds since epoch (UTC).
  var startTime: Int64
  /// Timezone offset in seconds (optional).
  var zoneOffsetSeconds: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ActiveCaloriesBurnedRecordDto? {
    let energy = pigeonVar_list[0] as! EnergyDto
    let endTime = pigeonVar_list[1] as! Int64
    let id: String? = nilOrValue(pigeonVar_list[2])
    let metadata = pigeonVar_list[3] as! MetadataDto
    let startTime = pigeonVar_list[4] as! Int64
    let zoneOffsetSeconds: Int64? = nilOrValue(pigeonVar_list[5])

    return ActiveCaloriesBurnedRecordDto(
      energy: energy,
      endTime: endTime,
      id: id,
      metadata: metadata,
      startTime: startTime,
      zoneOffsetSeconds: zoneOffsetSeconds
    )
  }
  func toList() -> [Any?] {
    return [
      energy,
      endTime,
      id,
      metadata,
      startTime,
      zoneOffsetSeconds,
    ]
  }
  public static func == (lhs: ActiveCaloriesBurnedRecordDto, rhs: ActiveCaloriesBurnedRecordDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Represents a distance record for platform transfer.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct DistanceRecordDto: HealthRecordDto {
  /// Distance traveled during the interval.
  var distance: LengthDto
  /// End time in milliseconds since epoch (UTC).
  var endTime: Int64
  /// Platform-assigned unique identifier.
  var id: String? = nil
  /// Metadata about this record.
  var metadata: MetadataDto
  /// Start time in milliseconds since epoch (UTC).
  var startTime: Int64
  /// Timezone offset in seconds (optional).
  var zoneOffsetSeconds: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DistanceRecordDto? {
    let distance = pigeonVar_list[0] as! LengthDto
    let endTime = pigeonVar_list[1] as! Int64
    let id: String? = nilOrValue(pigeonVar_list[2])
    let metadata = pigeonVar_list[3] as! MetadataDto
    let startTime = pigeonVar_list[4] as! Int64
    let zoneOffsetSeconds: Int64? = nilOrValue(pigeonVar_list[5])

    return DistanceRecordDto(
      distance: distance,
      endTime: endTime,
      id: id,
      metadata: metadata,
      startTime: startTime,
      zoneOffsetSeconds: zoneOffsetSeconds
    )
  }
  func toList() -> [Any?] {
    return [
      distance,
      endTime,
      id,
      metadata,
      startTime,
      zoneOffsetSeconds,
    ]
  }
  public static func == (lhs: DistanceRecordDto, rhs: DistanceRecordDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Represents a floors climbed record for platform transfer.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct FloorsClimbedRecordDto: HealthRecordDto {
  /// Number of floors (flights of stairs) climbed during the interval.
  var floors: NumericDto
  /// End time in milliseconds since epoch (UTC).
  var endTime: Int64
  /// Platform-assigned unique identifier.
  var id: String? = nil
  /// Metadata about this record.
  var metadata: MetadataDto
  /// Start time in milliseconds since epoch (UTC).
  var startTime: Int64
  /// Timezone offset in seconds (optional).
  var zoneOffsetSeconds: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FloorsClimbedRecordDto? {
    let floors = pigeonVar_list[0] as! NumericDto
    let endTime = pigeonVar_list[1] as! Int64
    let id: String? = nilOrValue(pigeonVar_list[2])
    let metadata = pigeonVar_list[3] as! MetadataDto
    let startTime = pigeonVar_list[4] as! Int64
    let zoneOffsetSeconds: Int64? = nilOrValue(pigeonVar_list[5])

    return FloorsClimbedRecordDto(
      floors: floors,
      endTime: endTime,
      id: id,
      metadata: metadata,
      startTime: startTime,
      zoneOffsetSeconds: zoneOffsetSeconds
    )
  }
  func toList() -> [Any?] {
    return [
      floors,
      endTime,
      id,
      metadata,
      startTime,
      zoneOffsetSeconds,
    ]
  }
  public static func == (lhs: FloorsClimbedRecordDto, rhs: FloorsClimbedRecordDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Represents a wheelchair pushes record for platform transfer.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct WheelchairPushesRecordDto: HealthRecordDto {
  /// Number of wheelchair pushes performed during the interval.
  var pushes: NumericDto
  /// End time in milliseconds since epoch (UTC).
  var endTime: Int64
  /// Platform-assigned unique identifier.
  var id: String? = nil
  /// Metadata about this record.
  var metadata: MetadataDto
  /// Start time in milliseconds since epoch (UTC).
  var startTime: Int64
  /// Timezone offset in seconds (optional).
  var zoneOffsetSeconds: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WheelchairPushesRecordDto? {
    let pushes = pigeonVar_list[0] as! NumericDto
    let endTime = pigeonVar_list[1] as! Int64
    let id: String? = nilOrValue(pigeonVar_list[2])
    let metadata = pigeonVar_list[3] as! MetadataDto
    let startTime = pigeonVar_list[4] as! Int64
    let zoneOffsetSeconds: Int64? = nilOrValue(pigeonVar_list[5])

    return WheelchairPushesRecordDto(
      pushes: pushes,
      endTime: endTime,
      id: id,
      metadata: metadata,
      startTime: startTime,
      zoneOffsetSeconds: zoneOffsetSeconds
    )
  }
  func toList() -> [Any?] {
    return [
      pushes,
      endTime,
      id,
      metadata,
      startTime,
      zoneOffsetSeconds,
    ]
  }
  public static func == (lhs: WheelchairPushesRecordDto, rhs: WheelchairPushesRecordDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Represents a step count record for platform transfer.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct StepRecordDto: HealthRecordDto {
  /// Number of steps taken during the interval (must be >= 0).
  var count: NumericDto
  /// End time in milliseconds since epoch (UTC).
  var endTime: Int64
  /// Platform-assigned unique identifier.
  var id: String? = nil
  /// Metadata about this record.
  var metadata: MetadataDto
  /// Start time in milliseconds since epoch (UTC).
  var startTime: Int64
  /// Timezone offset in seconds (optional).
  var zoneOffsetSeconds: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> StepRecordDto? {
    let count = pigeonVar_list[0] as! NumericDto
    let endTime = pigeonVar_list[1] as! Int64
    let id: String? = nilOrValue(pigeonVar_list[2])
    let metadata = pigeonVar_list[3] as! MetadataDto
    let startTime = pigeonVar_list[4] as! Int64
    let zoneOffsetSeconds: Int64? = nilOrValue(pigeonVar_list[5])

    return StepRecordDto(
      count: count,
      endTime: endTime,
      id: id,
      metadata: metadata,
      startTime: startTime,
      zoneOffsetSeconds: zoneOffsetSeconds
    )
  }
  func toList() -> [Any?] {
    return [
      count,
      endTime,
      id,
      metadata,
      startTime,
      zoneOffsetSeconds,
    ]
  }
  public static func == (lhs: StepRecordDto, rhs: StepRecordDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Represents a weight record for platform transfer.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct WeightRecordDto: HealthRecordDto {
  /// Platform-assigned unique identifier.
  var id: String? = nil
  /// Metadata about this record.
  var metadata: MetadataDto
  /// Measurement time in milliseconds since epoch (UTC).
  var time: Int64
  /// Weight measurement.
  var weight: MassDto
  /// Timezone offset in seconds for measurement time (optional).
  var zoneOffsetSeconds: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WeightRecordDto? {
    let id: String? = nilOrValue(pigeonVar_list[0])
    let metadata = pigeonVar_list[1] as! MetadataDto
    let time = pigeonVar_list[2] as! Int64
    let weight = pigeonVar_list[3] as! MassDto
    let zoneOffsetSeconds: Int64? = nilOrValue(pigeonVar_list[4])

    return WeightRecordDto(
      id: id,
      metadata: metadata,
      time: time,
      weight: weight,
      zoneOffsetSeconds: zoneOffsetSeconds
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      metadata,
      time,
      weight,
      zoneOffsetSeconds,
    ]
  }
  public static func == (lhs: WeightRecordDto, rhs: WeightRecordDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// DTO for lean body mass health data.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct LeanBodyMassRecordDto: HealthRecordDto {
  /// Platform-assigned unique identifier.
  var id: String? = nil
  /// Metadata about this record.
  var metadata: MetadataDto
  /// Measurement time in milliseconds since epoch (UTC).
  var time: Int64
  /// Lean body mass measurement.
  var mass: MassDto
  /// Timezone offset in seconds for measurement time (optional).
  var zoneOffsetSeconds: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> LeanBodyMassRecordDto? {
    let id: String? = nilOrValue(pigeonVar_list[0])
    let metadata = pigeonVar_list[1] as! MetadataDto
    let time = pigeonVar_list[2] as! Int64
    let mass = pigeonVar_list[3] as! MassDto
    let zoneOffsetSeconds: Int64? = nilOrValue(pigeonVar_list[4])

    return LeanBodyMassRecordDto(
      id: id,
      metadata: metadata,
      time: time,
      mass: mass,
      zoneOffsetSeconds: zoneOffsetSeconds
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      metadata,
      time,
      mass,
      zoneOffsetSeconds,
    ]
  }
  public static func == (lhs: LeanBodyMassRecordDto, rhs: LeanBodyMassRecordDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// DTO for body height health data.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct HeightRecordDto: HealthRecordDto {
  /// Platform-assigned unique identifier.
  var id: String? = nil
  /// Metadata about this record.
  var metadata: MetadataDto
  /// Measurement time in milliseconds since epoch (UTC).
  var time: Int64
  /// Height measurement.
  var height: LengthDto
  /// Timezone offset in seconds for measurement time (optional).
  var zoneOffsetSeconds: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HeightRecordDto? {
    let id: String? = nilOrValue(pigeonVar_list[0])
    let metadata = pigeonVar_list[1] as! MetadataDto
    let time = pigeonVar_list[2] as! Int64
    let height = pigeonVar_list[3] as! LengthDto
    let zoneOffsetSeconds: Int64? = nilOrValue(pigeonVar_list[4])

    return HeightRecordDto(
      id: id,
      metadata: metadata,
      time: time,
      height: height,
      zoneOffsetSeconds: zoneOffsetSeconds
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      metadata,
      time,
      height,
      zoneOffsetSeconds,
    ]
  }
  public static func == (lhs: HeightRecordDto, rhs: HeightRecordDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// DTO for body fat percentage health data.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct BodyFatPercentageRecordDto: HealthRecordDto {
  /// Platform-assigned unique identifier.
  var id: String? = nil
  /// Metadata about this record.
  var metadata: MetadataDto
  /// Measurement time in milliseconds since epoch (UTC).
  var time: Int64
  /// Body fat percentage measurement.
  var percentage: PercentageDto
  /// Timezone offset in seconds for measurement time (optional).
  var zoneOffsetSeconds: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BodyFatPercentageRecordDto? {
    let id: String? = nilOrValue(pigeonVar_list[0])
    let metadata = pigeonVar_list[1] as! MetadataDto
    let time = pigeonVar_list[2] as! Int64
    let percentage = pigeonVar_list[3] as! PercentageDto
    let zoneOffsetSeconds: Int64? = nilOrValue(pigeonVar_list[4])

    return BodyFatPercentageRecordDto(
      id: id,
      metadata: metadata,
      time: time,
      percentage: percentage,
      zoneOffsetSeconds: zoneOffsetSeconds
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      metadata,
      time,
      percentage,
      zoneOffsetSeconds,
    ]
  }
  public static func == (lhs: BodyFatPercentageRecordDto, rhs: BodyFatPercentageRecordDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// DTO for body temperature health data.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct BodyTemperatureRecordDto: HealthRecordDto {
  /// Platform-assigned unique identifier.
  var id: String? = nil
  /// Metadata about this record.
  var metadata: MetadataDto
  /// Measurement time in milliseconds since epoch (UTC).
  var time: Int64
  /// Body temperature measurement.
  var temperature: TemperatureDto
  /// Timezone offset in seconds for measurement time (optional).
  var zoneOffsetSeconds: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BodyTemperatureRecordDto? {
    let id: String? = nilOrValue(pigeonVar_list[0])
    let metadata = pigeonVar_list[1] as! MetadataDto
    let time = pigeonVar_list[2] as! Int64
    let temperature = pigeonVar_list[3] as! TemperatureDto
    let zoneOffsetSeconds: Int64? = nilOrValue(pigeonVar_list[4])

    return BodyTemperatureRecordDto(
      id: id,
      metadata: metadata,
      time: time,
      temperature: temperature,
      zoneOffsetSeconds: zoneOffsetSeconds
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      metadata,
      time,
      temperature,
      zoneOffsetSeconds,
    ]
  }
  public static func == (lhs: BodyTemperatureRecordDto, rhs: BodyTemperatureRecordDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Represents a hydration (water intake) record for platform transfer.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct HydrationRecordDto: HealthRecordDto {
  /// Platform-assigned unique identifier.
  var id: String? = nil
  /// Start time in milliseconds since epoch (UTC).
  var startTime: Int64
  /// End time in milliseconds since epoch (UTC).
  var endTime: Int64
  /// Metadata about this record.
  var metadata: MetadataDto
  /// Volume of water consumed during the interval.
  var volume: VolumeDto
  /// Timezone offset in seconds (optional).
  var zoneOffsetSeconds: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HydrationRecordDto? {
    let id: String? = nilOrValue(pigeonVar_list[0])
    let startTime = pigeonVar_list[1] as! Int64
    let endTime = pigeonVar_list[2] as! Int64
    let metadata = pigeonVar_list[3] as! MetadataDto
    let volume = pigeonVar_list[4] as! VolumeDto
    let zoneOffsetSeconds: Int64? = nilOrValue(pigeonVar_list[5])

    return HydrationRecordDto(
      id: id,
      startTime: startTime,
      endTime: endTime,
      metadata: metadata,
      volume: volume,
      zoneOffsetSeconds: zoneOffsetSeconds
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      startTime,
      endTime,
      metadata,
      volume,
      zoneOffsetSeconds,
    ]
  }
  public static func == (lhs: HydrationRecordDto, rhs: HydrationRecordDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Represents a single heart rate measurement for platform transfer.
///
/// This is a platform-agnostic value class used within heart rate records.
/// It contains a timestamp and BPM value without ID or metadata.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct HeartRateMeasurementDto: Hashable {
  /// Timestamp in milliseconds since epoch (UTC).
  var time: Int64
  /// Heart rate value in beats per minute (BPM).
  var beatsPerMinute: NumericDto


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HeartRateMeasurementDto? {
    let time = pigeonVar_list[0] as! Int64
    let beatsPerMinute = pigeonVar_list[1] as! NumericDto

    return HeartRateMeasurementDto(
      time: time,
      beatsPerMinute: beatsPerMinute
    )
  }
  func toList() -> [Any?] {
    return [
      time,
      beatsPerMinute,
    ]
  }
  public static func == (lhs: HeartRateMeasurementDto, rhs: HeartRateMeasurementDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Represents a heart rate measurement record for platform transfer (iOS).
///
/// Generated class from Pigeon that represents data sent in messages.
public struct HeartRateMeasurementRecordDto: HealthRecordDto {
  /// Platform-assigned unique identifier.
  var id: String? = nil
  /// Measurement time in milliseconds since epoch (UTC).
  var time: Int64
  /// Metadata about this record.
  var metadata: MetadataDto
  /// The heart rate measurement.
  var measurement: HeartRateMeasurementDto
  /// Timezone offset in seconds for measurement time (optional).
  var zoneOffsetSeconds: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HeartRateMeasurementRecordDto? {
    let id: String? = nilOrValue(pigeonVar_list[0])
    let time = pigeonVar_list[1] as! Int64
    let metadata = pigeonVar_list[2] as! MetadataDto
    let measurement = pigeonVar_list[3] as! HeartRateMeasurementDto
    let zoneOffsetSeconds: Int64? = nilOrValue(pigeonVar_list[4])

    return HeartRateMeasurementRecordDto(
      id: id,
      time: time,
      metadata: metadata,
      measurement: measurement,
      zoneOffsetSeconds: zoneOffsetSeconds
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      time,
      metadata,
      measurement,
      zoneOffsetSeconds,
    ]
  }
  public static func == (lhs: HeartRateMeasurementRecordDto, rhs: HeartRateMeasurementRecordDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Represents the result of a health data permission request.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct HealthDataPermissionRequestResultDto: Hashable {
  /// The health data permission that was requested.
  var permission: HealthDataPermissionDto
  /// The status of the permission after the request.
  var status: PermissionStatusDto


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> HealthDataPermissionRequestResultDto? {
    let permission = pigeonVar_list[0] as! HealthDataPermissionDto
    let status = pigeonVar_list[1] as! PermissionStatusDto

    return HealthDataPermissionRequestResultDto(
      permission: permission,
      status: status
    )
  }
  func toList() -> [Any?] {
    return [
      permission,
      status,
    ]
  }
  public static func == (lhs: HealthDataPermissionRequestResultDto, rhs: HealthDataPermissionRequestResultDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Represents a permissions request.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct PermissionsRequestDto: Hashable {
  /// List of health data permissions to request.
  var healthDataPermissions: [HealthDataPermissionDto]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PermissionsRequestDto? {
    let healthDataPermissions = pigeonVar_list[0] as! [HealthDataPermissionDto]

    return PermissionsRequestDto(
      healthDataPermissions: healthDataPermissions
    )
  }
  func toList() -> [Any?] {
    return [
      healthDataPermissions
    ]
  }
  public static func == (lhs: PermissionsRequestDto, rhs: PermissionsRequestDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Represents the response from a permissions request.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct PermissionsRequestResponseDto: Hashable {
  /// Results for each health data permission that was requested.
  var healthDataPermissionResults: [HealthDataPermissionRequestResultDto]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PermissionsRequestResponseDto? {
    let healthDataPermissionResults = pigeonVar_list[0] as! [HealthDataPermissionRequestResultDto]

    return PermissionsRequestResponseDto(
      healthDataPermissionResults: healthDataPermissionResults
    )
  }
  func toList() -> [Any?] {
    return [
      healthDataPermissionResults
    ]
  }
  public static func == (lhs: PermissionsRequestResponseDto, rhs: PermissionsRequestResponseDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Request to perform aggregation on health records.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct AggregateRequestDto: Hashable {
  /// The type of aggregation to perform.
  var aggregationMetric: AggregationMetricDto
  /// The type of health data to aggregate.
  var dataType: HealthDataTypeDto
  /// End of time range in milliseconds since epoch (UTC), exclusive.
  var endTime: Int64
  /// Start of time range in milliseconds since epoch (UTC), inclusive.
  var startTime: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AggregateRequestDto? {
    let aggregationMetric = pigeonVar_list[0] as! AggregationMetricDto
    let dataType = pigeonVar_list[1] as! HealthDataTypeDto
    let endTime = pigeonVar_list[2] as! Int64
    let startTime = pigeonVar_list[3] as! Int64

    return AggregateRequestDto(
      aggregationMetric: aggregationMetric,
      dataType: dataType,
      endTime: endTime,
      startTime: startTime
    )
  }
  func toList() -> [Any?] {
    return [
      aggregationMetric,
      dataType,
      endTime,
      startTime,
    ]
  }
  public static func == (lhs: AggregateRequestDto, rhs: AggregateRequestDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Response containing aggregated value.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct AggregateResponseDto: Hashable {
  /// Aggregated value.
  var value: MeasurementUnitDto


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AggregateResponseDto? {
    let value = pigeonVar_list[0] as! MeasurementUnitDto

    return AggregateResponseDto(
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      value
    ]
  }
  public static func == (lhs: AggregateResponseDto, rhs: AggregateResponseDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Request to delete specific records by their IDs.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct DeleteRecordsByIdsRequestDto: Hashable {
  /// The type of health data to delete.
  var dataType: HealthDataTypeDto
  /// List of unique identifiers for records to delete.
  var recordIds: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DeleteRecordsByIdsRequestDto? {
    let dataType = pigeonVar_list[0] as! HealthDataTypeDto
    let recordIds = pigeonVar_list[1] as! [String]

    return DeleteRecordsByIdsRequestDto(
      dataType: dataType,
      recordIds: recordIds
    )
  }
  func toList() -> [Any?] {
    return [
      dataType,
      recordIds,
    ]
  }
  public static func == (lhs: DeleteRecordsByIdsRequestDto, rhs: DeleteRecordsByIdsRequestDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Request to delete records by time range.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct DeleteRecordsByTimeRangeRequestDto: Hashable {
  /// The type of health data to delete.
  var dataType: HealthDataTypeDto
  /// End of time range in milliseconds since epoch (UTC), exclusive.
  var endTime: Int64
  /// Start of time range in milliseconds since epoch (UTC), inclusive.
  var startTime: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DeleteRecordsByTimeRangeRequestDto? {
    let dataType = pigeonVar_list[0] as! HealthDataTypeDto
    let endTime = pigeonVar_list[1] as! Int64
    let startTime = pigeonVar_list[2] as! Int64

    return DeleteRecordsByTimeRangeRequestDto(
      dataType: dataType,
      endTime: endTime,
      startTime: startTime
    )
  }
  func toList() -> [Any?] {
    return [
      dataType,
      endTime,
      startTime,
    ]
  }
  public static func == (lhs: DeleteRecordsByTimeRangeRequestDto, rhs: DeleteRecordsByTimeRangeRequestDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Request to read a single health record by ID.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct ReadRecordRequestDto: Hashable {
  /// The unique identifier of the record to read.
  var recordId: String
  /// The type of health data to read.
  var dataType: HealthDataTypeDto


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ReadRecordRequestDto? {
    let recordId = pigeonVar_list[0] as! String
    let dataType = pigeonVar_list[1] as! HealthDataTypeDto

    return ReadRecordRequestDto(
      recordId: recordId,
      dataType: dataType
    )
  }
  func toList() -> [Any?] {
    return [
      recordId,
      dataType,
    ]
  }
  public static func == (lhs: ReadRecordRequestDto, rhs: ReadRecordRequestDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Response containing a single health record.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct ReadRecordResponseDto: Hashable {
  /// The health record that was read.
  var record: HealthRecordDto? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ReadRecordResponseDto? {
    let record: HealthRecordDto? = nilOrValue(pigeonVar_list[0])

    return ReadRecordResponseDto(
      record: record
    )
  }
  func toList() -> [Any?] {
    return [
      record
    ]
  }
  public static func == (lhs: ReadRecordResponseDto, rhs: ReadRecordResponseDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Request to read multiple health records within a time range.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct ReadRecordsRequestDto: Hashable {
  /// The type of health data to read.
  var dataType: HealthDataTypeDto
  /// Maximum number of records to return per page (1-10,000).
  var pageSize: Int64
  /// Opaque pagination token for fetching next page (optional).
  ///
  /// Provided by previous response's nextPageToken.
  var pageToken: String? = nil
  /// Start of time range in milliseconds since epoch (UTC), inclusive.
  var startTime: Int64
  /// End of time range in milliseconds since epoch (UTC), exclusive.
  var endTime: Int64
  /// List of package names to filter by.
  var dataOriginPackageNames: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ReadRecordsRequestDto? {
    let dataType = pigeonVar_list[0] as! HealthDataTypeDto
    let pageSize = pigeonVar_list[1] as! Int64
    let pageToken: String? = nilOrValue(pigeonVar_list[2])
    let startTime = pigeonVar_list[3] as! Int64
    let endTime = pigeonVar_list[4] as! Int64
    let dataOriginPackageNames = pigeonVar_list[5] as! [String]

    return ReadRecordsRequestDto(
      dataType: dataType,
      pageSize: pageSize,
      pageToken: pageToken,
      startTime: startTime,
      endTime: endTime,
      dataOriginPackageNames: dataOriginPackageNames
    )
  }
  func toList() -> [Any?] {
    return [
      dataType,
      pageSize,
      pageToken,
      startTime,
      endTime,
      dataOriginPackageNames,
    ]
  }
  public static func == (lhs: ReadRecordsRequestDto, rhs: ReadRecordsRequestDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Response containing paginated health records.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct ReadRecordsResponseDto: Hashable {
  /// Token for fetching next page, null if no more pages exist.
  var nextPageToken: String? = nil
  /// List of health records that were read.
  var records: [HealthRecordDto]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ReadRecordsResponseDto? {
    let nextPageToken: String? = nilOrValue(pigeonVar_list[0])
    let records = pigeonVar_list[1] as! [HealthRecordDto]

    return ReadRecordsResponseDto(
      nextPageToken: nextPageToken,
      records: records
    )
  }
  func toList() -> [Any?] {
    return [
      nextPageToken,
      records,
    ]
  }
  public static func == (lhs: ReadRecordsResponseDto, rhs: ReadRecordsResponseDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Request to write a single health record.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct WriteRecordRequestDto: Hashable {
  /// Health record.
  var record: HealthRecordDto


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WriteRecordRequestDto? {
    let record = pigeonVar_list[0] as! HealthRecordDto

    return WriteRecordRequestDto(
      record: record
    )
  }
  func toList() -> [Any?] {
    return [
      record
    ]
  }
  public static func == (lhs: WriteRecordRequestDto, rhs: WriteRecordRequestDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Response after writing a single record.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct WriteRecordResponseDto: Hashable {
  /// Platform-assigned unique identifier for the written record.
  var recordId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WriteRecordResponseDto? {
    let recordId = pigeonVar_list[0] as! String

    return WriteRecordResponseDto(
      recordId: recordId
    )
  }
  func toList() -> [Any?] {
    return [
      recordId
    ]
  }
  public static func == (lhs: WriteRecordResponseDto, rhs: WriteRecordResponseDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Request to write multiple health records atomically.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct WriteRecordsRequestDto: Hashable {
  /// Records being written.
  var records: [HealthRecordDto]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WriteRecordsRequestDto? {
    let records = pigeonVar_list[0] as! [HealthRecordDto]

    return WriteRecordsRequestDto(
      records: records
    )
  }
  func toList() -> [Any?] {
    return [
      records
    ]
  }
  public static func == (lhs: WriteRecordsRequestDto, rhs: WriteRecordsRequestDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Response after writing multiple records.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct WriteRecordsResponseDto: Hashable {
  /// Platform-assigned unique identifiers for written records.
  var recordIds: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> WriteRecordsResponseDto? {
    let recordIds = pigeonVar_list[0] as! [String]

    return WriteRecordsResponseDto(
      recordIds: recordIds
    )
  }
  func toList() -> [Any?] {
    return [
      recordIds
    ]
  }
  public static func == (lhs: WriteRecordsResponseDto, rhs: WriteRecordsResponseDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Request to update a single health record.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct UpdateRecordRequestDto: Hashable {
  /// The health record to update.
  var record: HealthRecordDto


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UpdateRecordRequestDto? {
    let record = pigeonVar_list[0] as! HealthRecordDto

    return UpdateRecordRequestDto(
      record: record
    )
  }
  func toList() -> [Any?] {
    return [
      record
    ]
  }
  public static func == (lhs: UpdateRecordRequestDto, rhs: UpdateRecordRequestDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

/// Response after updating a single record.
///
/// Generated class from Pigeon that represents data sent in messages.
public struct UpdateRecordResponseDto: Hashable {
  /// Platform-assigned unique identifier for the updated record.
  var recordId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UpdateRecordResponseDto? {
    let recordId = pigeonVar_list[0] as! String

    return UpdateRecordResponseDto(
      recordId: recordId
    )
  }
  func toList() -> [Any?] {
    return [
      recordId
    ]
  }
  public static func == (lhs: UpdateRecordResponseDto, rhs: UpdateRecordResponseDto) -> Bool {
    return deepEqualsHealthConnectorPlatformApi(lhs.toList(), rhs.toList())  }
  public func hash(into hasher: inout Hasher) {
    deepHashHealthConnectorPlatformApi(value: toList(), hasher: &hasher)
  }
}

private class HealthConnectorPlatformApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return HealthConnectorErrorCodeDto(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return HealthPlatformStatusDto(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BloodGlucoseUnitDto(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return EnergyUnitDto(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return LengthUnitDto(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return MassUnitDto(rawValue: enumResultAsInt)
      }
      return nil
    case 135:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return NumericUnitDto(rawValue: enumResultAsInt)
      }
      return nil
    case 136:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PercentageUnitDto(rawValue: enumResultAsInt)
      }
      return nil
    case 137:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PermissionAccessTypeDto(rawValue: enumResultAsInt)
      }
      return nil
    case 138:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PermissionStatusDto(rawValue: enumResultAsInt)
      }
      return nil
    case 139:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PressureUnitDto(rawValue: enumResultAsInt)
      }
      return nil
    case 140:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return PowerUnitDto(rawValue: enumResultAsInt)
      }
      return nil
    case 141:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return TemperatureUnitDto(rawValue: enumResultAsInt)
      }
      return nil
    case 142:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return VelocityUnitDto(rawValue: enumResultAsInt)
      }
      return nil
    case 143:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return VolumeUnitDto(rawValue: enumResultAsInt)
      }
      return nil
    case 144:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return HealthDataTypeDto(rawValue: enumResultAsInt)
      }
      return nil
    case 145:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AggregationMetricDto(rawValue: enumResultAsInt)
      }
      return nil
    case 146:
      return BloodGlucoseDto.fromList(self.readValue() as! [Any?])
    case 147:
      return EnergyDto.fromList(self.readValue() as! [Any?])
    case 148:
      return LengthDto.fromList(self.readValue() as! [Any?])
    case 149:
      return MassDto.fromList(self.readValue() as! [Any?])
    case 150:
      return NumericDto.fromList(self.readValue() as! [Any?])
    case 151:
      return PercentageDto.fromList(self.readValue() as! [Any?])
    case 152:
      return PowerDto.fromList(self.readValue() as! [Any?])
    case 153:
      return PressureDto.fromList(self.readValue() as! [Any?])
    case 154:
      return TemperatureDto.fromList(self.readValue() as! [Any?])
    case 155:
      return VelocityDto.fromList(self.readValue() as! [Any?])
    case 156:
      return VolumeDto.fromList(self.readValue() as! [Any?])
    case 157:
      return MetadataDto.fromList(self.readValue() as! [Any?])
    case 158:
      return HealthDataPermissionDto.fromList(self.readValue() as! [Any?])
    case 159:
      return ActiveCaloriesBurnedRecordDto.fromList(self.readValue() as! [Any?])
    case 160:
      return DistanceRecordDto.fromList(self.readValue() as! [Any?])
    case 161:
      return FloorsClimbedRecordDto.fromList(self.readValue() as! [Any?])
    case 162:
      return WheelchairPushesRecordDto.fromList(self.readValue() as! [Any?])
    case 163:
      return StepRecordDto.fromList(self.readValue() as! [Any?])
    case 164:
      return WeightRecordDto.fromList(self.readValue() as! [Any?])
    case 165:
      return LeanBodyMassRecordDto.fromList(self.readValue() as! [Any?])
    case 166:
      return HeightRecordDto.fromList(self.readValue() as! [Any?])
    case 167:
      return BodyFatPercentageRecordDto.fromList(self.readValue() as! [Any?])
    case 168:
      return BodyTemperatureRecordDto.fromList(self.readValue() as! [Any?])
    case 169:
      return HydrationRecordDto.fromList(self.readValue() as! [Any?])
    case 170:
      return HeartRateMeasurementDto.fromList(self.readValue() as! [Any?])
    case 171:
      return HeartRateMeasurementRecordDto.fromList(self.readValue() as! [Any?])
    case 172:
      return HealthDataPermissionRequestResultDto.fromList(self.readValue() as! [Any?])
    case 173:
      return PermissionsRequestDto.fromList(self.readValue() as! [Any?])
    case 174:
      return PermissionsRequestResponseDto.fromList(self.readValue() as! [Any?])
    case 175:
      return AggregateRequestDto.fromList(self.readValue() as! [Any?])
    case 176:
      return AggregateResponseDto.fromList(self.readValue() as! [Any?])
    case 177:
      return DeleteRecordsByIdsRequestDto.fromList(self.readValue() as! [Any?])
    case 178:
      return DeleteRecordsByTimeRangeRequestDto.fromList(self.readValue() as! [Any?])
    case 179:
      return ReadRecordRequestDto.fromList(self.readValue() as! [Any?])
    case 180:
      return ReadRecordResponseDto.fromList(self.readValue() as! [Any?])
    case 181:
      return ReadRecordsRequestDto.fromList(self.readValue() as! [Any?])
    case 182:
      return ReadRecordsResponseDto.fromList(self.readValue() as! [Any?])
    case 183:
      return WriteRecordRequestDto.fromList(self.readValue() as! [Any?])
    case 184:
      return WriteRecordResponseDto.fromList(self.readValue() as! [Any?])
    case 185:
      return WriteRecordsRequestDto.fromList(self.readValue() as! [Any?])
    case 186:
      return WriteRecordsResponseDto.fromList(self.readValue() as! [Any?])
    case 187:
      return UpdateRecordRequestDto.fromList(self.readValue() as! [Any?])
    case 188:
      return UpdateRecordResponseDto.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class HealthConnectorPlatformApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? HealthConnectorErrorCodeDto {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? HealthPlatformStatusDto {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? BloodGlucoseUnitDto {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? EnergyUnitDto {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? LengthUnitDto {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? MassUnitDto {
      super.writeByte(134)
      super.writeValue(value.rawValue)
    } else if let value = value as? NumericUnitDto {
      super.writeByte(135)
      super.writeValue(value.rawValue)
    } else if let value = value as? PercentageUnitDto {
      super.writeByte(136)
      super.writeValue(value.rawValue)
    } else if let value = value as? PermissionAccessTypeDto {
      super.writeByte(137)
      super.writeValue(value.rawValue)
    } else if let value = value as? PermissionStatusDto {
      super.writeByte(138)
      super.writeValue(value.rawValue)
    } else if let value = value as? PressureUnitDto {
      super.writeByte(139)
      super.writeValue(value.rawValue)
    } else if let value = value as? PowerUnitDto {
      super.writeByte(140)
      super.writeValue(value.rawValue)
    } else if let value = value as? TemperatureUnitDto {
      super.writeByte(141)
      super.writeValue(value.rawValue)
    } else if let value = value as? VelocityUnitDto {
      super.writeByte(142)
      super.writeValue(value.rawValue)
    } else if let value = value as? VolumeUnitDto {
      super.writeByte(143)
      super.writeValue(value.rawValue)
    } else if let value = value as? HealthDataTypeDto {
      super.writeByte(144)
      super.writeValue(value.rawValue)
    } else if let value = value as? AggregationMetricDto {
      super.writeByte(145)
      super.writeValue(value.rawValue)
    } else if let value = value as? BloodGlucoseDto {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else if let value = value as? EnergyDto {
      super.writeByte(147)
      super.writeValue(value.toList())
    } else if let value = value as? LengthDto {
      super.writeByte(148)
      super.writeValue(value.toList())
    } else if let value = value as? MassDto {
      super.writeByte(149)
      super.writeValue(value.toList())
    } else if let value = value as? NumericDto {
      super.writeByte(150)
      super.writeValue(value.toList())
    } else if let value = value as? PercentageDto {
      super.writeByte(151)
      super.writeValue(value.toList())
    } else if let value = value as? PowerDto {
      super.writeByte(152)
      super.writeValue(value.toList())
    } else if let value = value as? PressureDto {
      super.writeByte(153)
      super.writeValue(value.toList())
    } else if let value = value as? TemperatureDto {
      super.writeByte(154)
      super.writeValue(value.toList())
    } else if let value = value as? VelocityDto {
      super.writeByte(155)
      super.writeValue(value.toList())
    } else if let value = value as? VolumeDto {
      super.writeByte(156)
      super.writeValue(value.toList())
    } else if let value = value as? MetadataDto {
      super.writeByte(157)
      super.writeValue(value.toList())
    } else if let value = value as? HealthDataPermissionDto {
      super.writeByte(158)
      super.writeValue(value.toList())
    } else if let value = value as? ActiveCaloriesBurnedRecordDto {
      super.writeByte(159)
      super.writeValue(value.toList())
    } else if let value = value as? DistanceRecordDto {
      super.writeByte(160)
      super.writeValue(value.toList())
    } else if let value = value as? FloorsClimbedRecordDto {
      super.writeByte(161)
      super.writeValue(value.toList())
    } else if let value = value as? WheelchairPushesRecordDto {
      super.writeByte(162)
      super.writeValue(value.toList())
    } else if let value = value as? StepRecordDto {
      super.writeByte(163)
      super.writeValue(value.toList())
    } else if let value = value as? WeightRecordDto {
      super.writeByte(164)
      super.writeValue(value.toList())
    } else if let value = value as? LeanBodyMassRecordDto {
      super.writeByte(165)
      super.writeValue(value.toList())
    } else if let value = value as? HeightRecordDto {
      super.writeByte(166)
      super.writeValue(value.toList())
    } else if let value = value as? BodyFatPercentageRecordDto {
      super.writeByte(167)
      super.writeValue(value.toList())
    } else if let value = value as? BodyTemperatureRecordDto {
      super.writeByte(168)
      super.writeValue(value.toList())
    } else if let value = value as? HydrationRecordDto {
      super.writeByte(169)
      super.writeValue(value.toList())
    } else if let value = value as? HeartRateMeasurementDto {
      super.writeByte(170)
      super.writeValue(value.toList())
    } else if let value = value as? HeartRateMeasurementRecordDto {
      super.writeByte(171)
      super.writeValue(value.toList())
    } else if let value = value as? HealthDataPermissionRequestResultDto {
      super.writeByte(172)
      super.writeValue(value.toList())
    } else if let value = value as? PermissionsRequestDto {
      super.writeByte(173)
      super.writeValue(value.toList())
    } else if let value = value as? PermissionsRequestResponseDto {
      super.writeByte(174)
      super.writeValue(value.toList())
    } else if let value = value as? AggregateRequestDto {
      super.writeByte(175)
      super.writeValue(value.toList())
    } else if let value = value as? AggregateResponseDto {
      super.writeByte(176)
      super.writeValue(value.toList())
    } else if let value = value as? DeleteRecordsByIdsRequestDto {
      super.writeByte(177)
      super.writeValue(value.toList())
    } else if let value = value as? DeleteRecordsByTimeRangeRequestDto {
      super.writeByte(178)
      super.writeValue(value.toList())
    } else if let value = value as? ReadRecordRequestDto {
      super.writeByte(179)
      super.writeValue(value.toList())
    } else if let value = value as? ReadRecordResponseDto {
      super.writeByte(180)
      super.writeValue(value.toList())
    } else if let value = value as? ReadRecordsRequestDto {
      super.writeByte(181)
      super.writeValue(value.toList())
    } else if let value = value as? ReadRecordsResponseDto {
      super.writeByte(182)
      super.writeValue(value.toList())
    } else if let value = value as? WriteRecordRequestDto {
      super.writeByte(183)
      super.writeValue(value.toList())
    } else if let value = value as? WriteRecordResponseDto {
      super.writeByte(184)
      super.writeValue(value.toList())
    } else if let value = value as? WriteRecordsRequestDto {
      super.writeByte(185)
      super.writeValue(value.toList())
    } else if let value = value as? WriteRecordsResponseDto {
      super.writeByte(186)
      super.writeValue(value.toList())
    } else if let value = value as? UpdateRecordRequestDto {
      super.writeByte(187)
      super.writeValue(value.toList())
    } else if let value = value as? UpdateRecordResponseDto {
      super.writeByte(188)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class HealthConnectorPlatformApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return HealthConnectorPlatformApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return HealthConnectorPlatformApiPigeonCodecWriter(data: data)
  }
}

class HealthConnectorPlatformApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = HealthConnectorPlatformApiPigeonCodec(readerWriter: HealthConnectorPlatformApiPigeonCodecReaderWriter())
}


/// The main API for communicating with the health platform.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol HealthConnectorPlatformApi {
  func aggregate(request: AggregateRequestDto, completion: @escaping (Result<AggregateResponseDto, Error>) -> Void)
  func deleteRecordsByIds(request: DeleteRecordsByIdsRequestDto, completion: @escaping (Result<Void, Error>) -> Void)
  func deleteRecordsByTimeRange(request: DeleteRecordsByTimeRangeRequestDto, completion: @escaping (Result<Void, Error>) -> Void)
  func getHealthPlatformStatus(completion: @escaping (Result<HealthPlatformStatusDto, Error>) -> Void)
  func requestPermissions(request: PermissionsRequestDto, completion: @escaping (Result<PermissionsRequestResponseDto, Error>) -> Void)
  func readRecord(request: ReadRecordRequestDto, completion: @escaping (Result<ReadRecordResponseDto?, Error>) -> Void)
  func readRecords(request: ReadRecordsRequestDto, completion: @escaping (Result<ReadRecordsResponseDto, Error>) -> Void)
  func writeRecord(request: WriteRecordRequestDto, completion: @escaping (Result<WriteRecordResponseDto, Error>) -> Void)
  func writeRecords(request: WriteRecordsRequestDto, completion: @escaping (Result<WriteRecordsResponseDto, Error>) -> Void)
  func updateRecord(request: UpdateRecordRequestDto, completion: @escaping (Result<UpdateRecordResponseDto, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class HealthConnectorPlatformApiSetup {
  static var codec: FlutterStandardMessageCodec { HealthConnectorPlatformApiPigeonCodec.shared }
  /// Sets up an instance of `HealthConnectorPlatformApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: HealthConnectorPlatformApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let aggregateChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.health_connector_hk_ios.HealthConnectorPlatformApi.aggregate\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      aggregateChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! AggregateRequestDto
        api.aggregate(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      aggregateChannel.setMessageHandler(nil)
    }
    let deleteRecordsByIdsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.health_connector_hk_ios.HealthConnectorPlatformApi.deleteRecordsByIds\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteRecordsByIdsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! DeleteRecordsByIdsRequestDto
        api.deleteRecordsByIds(request: requestArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      deleteRecordsByIdsChannel.setMessageHandler(nil)
    }
    let deleteRecordsByTimeRangeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.health_connector_hk_ios.HealthConnectorPlatformApi.deleteRecordsByTimeRange\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      deleteRecordsByTimeRangeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! DeleteRecordsByTimeRangeRequestDto
        api.deleteRecordsByTimeRange(request: requestArg) { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      deleteRecordsByTimeRangeChannel.setMessageHandler(nil)
    }
    let getHealthPlatformStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.health_connector_hk_ios.HealthConnectorPlatformApi.getHealthPlatformStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getHealthPlatformStatusChannel.setMessageHandler { _, reply in
        api.getHealthPlatformStatus { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      getHealthPlatformStatusChannel.setMessageHandler(nil)
    }
    let requestPermissionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.health_connector_hk_ios.HealthConnectorPlatformApi.requestPermissions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      requestPermissionsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PermissionsRequestDto
        api.requestPermissions(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      requestPermissionsChannel.setMessageHandler(nil)
    }
    let readRecordChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.health_connector_hk_ios.HealthConnectorPlatformApi.readRecord\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readRecordChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ReadRecordRequestDto
        api.readRecord(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readRecordChannel.setMessageHandler(nil)
    }
    let readRecordsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.health_connector_hk_ios.HealthConnectorPlatformApi.readRecords\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      readRecordsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ReadRecordsRequestDto
        api.readRecords(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      readRecordsChannel.setMessageHandler(nil)
    }
    let writeRecordChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.health_connector_hk_ios.HealthConnectorPlatformApi.writeRecord\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      writeRecordChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! WriteRecordRequestDto
        api.writeRecord(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      writeRecordChannel.setMessageHandler(nil)
    }
    let writeRecordsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.health_connector_hk_ios.HealthConnectorPlatformApi.writeRecords\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      writeRecordsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! WriteRecordsRequestDto
        api.writeRecords(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      writeRecordsChannel.setMessageHandler(nil)
    }
    let updateRecordChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.health_connector_hk_ios.HealthConnectorPlatformApi.updateRecord\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateRecordChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! UpdateRecordRequestDto
        api.updateRecord(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      updateRecordChannel.setMessageHandler(nil)
    }
  }
}
