// Copyright 2025 Pham Tung Lam
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// ---
// Autogenerated from Pigeon (v26.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length && a.entries.every((MapEntry<Object?, Object?> entry) =>
        (b as Map<Object?, Object?>).containsKey(entry.key) &&
        _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}


/// Error codes that native platforms can use when throwing error.
enum HealthConnectorErrorCodeDto {
  /// Health platform is unavailable on this device.
  healthPlatformUnavailable,
  /// Invalid platform configuration detected.
  invalidPlatformConfiguration,
  /// Invalid argument or input validation error.
  invalidArgument,
  /// Attempted to use platform APIs that are not supported on
  /// the current health platform.
  unsupportedHealthPlatformApi,
  /// Unknown or unspecified error.
  unknown,
  /// Security/permission error occurred.
  securityError,
}

/// Represents the status of the health platform on the device.
enum HealthPlatformStatusDto {
  /// The health platform is available and ready to use.
  available,
  /// The health platform is not available on this device.
  notAvailable,
}

/// Blood glucose unit types supported by the plugin.
enum BloodGlucoseUnitDto {
  milligramsPerDeciliter,
  millimolesPerLiter,
}

/// Energy unit types supported by the plugin.
enum EnergyUnitDto {
  calories,
  joules,
  kilocalories,
  kilojoules,
}

/// Length unit types supported by the plugin.
enum LengthUnitDto {
  feet,
  inches,
  kilometers,
  meters,
  miles,
}

/// Mass unit types supported by the plugin.
enum MassUnitDto {
  grams,
  kilograms,
  ounces,
  pounds,
}

/// Numeric unit types supported by the plugin.
///
/// Numeric values don't have unit conversions, but this enum is provided
/// for consistency with other unit types.
enum NumericUnitDto {
  numeric,
}

/// Percentage unit types supported by the plugin.
enum PercentageUnitDto {
  /// Percentage as a decimal value (0.0 to 1.0).
  decimal,
  /// Percentage as a whole number (0 to 100).
  whole,
}

/// Represents the type of access requested for health data.
enum PermissionAccessTypeDto {
  /// Read access to health data.
  read,
  /// Write access to health data.
  write,
}

/// Represents the status of a permission.
enum PermissionStatusDto {
  /// Permission has been explicitly denied by the user.
  denied,
  /// Permission has been explicitly granted by the user.
  granted,
  /// The permission status cannot be determined.
  unknown,
}

/// Pressure unit types supported by the plugin.
enum PressureUnitDto {
  millimetersOfMercury,
}

/// Power unit types supported by the plugin.
enum PowerUnitDto {
  kilowatts,
  watts,
}

/// Temperature unit types supported by the plugin.
enum TemperatureUnitDto {
  celsius,
  fahrenheit,
  kelvin,
}

/// Velocity unit types supported by the plugin.
enum VelocityUnitDto {
  kilometersPerHour,
  metersPerSecond,
  milesPerHour,
}

/// Volume unit types supported by the plugin.
enum VolumeUnitDto {
  fluidOuncesUs,
  liters,
  milliliters,
}

/// Recording method for health data.
enum RecordingMethodDto {
  /// Data was recorded during an active user-initiated session.
  activelyRecorded,
  /// Data was automatically recorded by a device in the background.
  automaticallyRecorded,
  /// Data was manually entered by the user.
  manualEntry,
  /// The recording method is unknown or unspecified.
  unknown,
}

/// Represents a health data type.
enum HealthDataTypeDto {
  /// Active calories burned data.
  activeCaloriesBurned,
  /// Distance traveled data.
  distance,
  /// Floors climbed data.
  floorsClimbed,
  /// Step count data.
  steps,
  /// Body weight data.
  weight,
  /// Body height data.
  height,
  /// Body fat percentage data.
  bodyFatPercentage,
  /// Body temperature data.
  bodyTemperature,
  /// Lean body mass data.
  leanBodyMass,
  /// Wheelchair pushes data.
  wheelchairPushes,
  /// Hydration (water intake) data.
  hydration,
  /// Heart rate measurement record data (iOS).
  heartRateMeasurementRecord,
}

/// Aggregation metric types for health data queries.
enum AggregationMetricDto {
  /// Average (mean) value across all data points.
  avg,
  /// Count of data points (records) in the dataset.
  count,
  /// Maximum value in the dataset.
  max,
  /// Minimum value in the dataset.
  min,
  /// Sum of all values in the time range.
  sum,
}

/// Sealed class for all measurement unit DTOs.
sealed class MeasurementUnitDto {
}

/// Represents a blood glucose measurement for platform transfer.
class BloodGlucoseDto extends MeasurementUnitDto {
  BloodGlucoseDto({
    required this.unit,
    required this.value,
  });

  /// The unit in which the value is expressed.
  BloodGlucoseUnitDto unit;

  /// The numeric value of the blood glucose.
  double value;

  List<Object?> _toList() {
    return <Object?>[
      unit,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static BloodGlucoseDto decode(Object result) {
    result as List<Object?>;
    return BloodGlucoseDto(
      unit: result[0]! as BloodGlucoseUnitDto,
      value: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BloodGlucoseDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents an energy measurement for platform transfer.
class EnergyDto extends MeasurementUnitDto {
  EnergyDto({
    required this.unit,
    required this.value,
  });

  /// The unit in which the value is expressed.
  EnergyUnitDto unit;

  /// The numeric value of the energy.
  double value;

  List<Object?> _toList() {
    return <Object?>[
      unit,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static EnergyDto decode(Object result) {
    result as List<Object?>;
    return EnergyDto(
      unit: result[0]! as EnergyUnitDto,
      value: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! EnergyDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents a length measurement for platform transfer.
class LengthDto extends MeasurementUnitDto {
  LengthDto({
    required this.unit,
    required this.value,
  });

  /// The unit in which the value is expressed.
  LengthUnitDto unit;

  /// The numeric value of the length.
  double value;

  List<Object?> _toList() {
    return <Object?>[
      unit,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static LengthDto decode(Object result) {
    result as List<Object?>;
    return LengthDto(
      unit: result[0]! as LengthUnitDto,
      value: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LengthDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents a mass measurement for platform transfer.
class MassDto extends MeasurementUnitDto {
  MassDto({
    required this.unit,
    required this.value,
  });

  /// The unit in which the value is expressed.
  MassUnitDto unit;

  /// The numeric value of the mass.
  double value;

  List<Object?> _toList() {
    return <Object?>[
      unit,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static MassDto decode(Object result) {
    result as List<Object?>;
    return MassDto(
      unit: result[0]! as MassUnitDto,
      value: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MassDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents a numeric measurement for platform transfer.
class NumericDto extends MeasurementUnitDto {
  NumericDto({
    required this.unit,
    required this.value,
  });

  /// The unit in which the value is expressed.
  NumericUnitDto unit;

  /// The numeric value.
  double value;

  List<Object?> _toList() {
    return <Object?>[
      unit,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static NumericDto decode(Object result) {
    result as List<Object?>;
    return NumericDto(
      unit: result[0]! as NumericUnitDto,
      value: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NumericDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents a percentage measurement for platform transfer.
class PercentageDto extends MeasurementUnitDto {
  PercentageDto({
    required this.unit,
    required this.value,
  });

  /// The unit in which the value is expressed.
  PercentageUnitDto unit;

  /// The numeric value of the percentage.
  double value;

  List<Object?> _toList() {
    return <Object?>[
      unit,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static PercentageDto decode(Object result) {
    result as List<Object?>;
    return PercentageDto(
      unit: result[0]! as PercentageUnitDto,
      value: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PercentageDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents a power measurement for platform transfer.
class PowerDto extends MeasurementUnitDto {
  PowerDto({
    required this.unit,
    required this.value,
  });

  /// The unit in which the value is expressed.
  PowerUnitDto unit;

  /// The numeric value of the power.
  double value;

  List<Object?> _toList() {
    return <Object?>[
      unit,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static PowerDto decode(Object result) {
    result as List<Object?>;
    return PowerDto(
      unit: result[0]! as PowerUnitDto,
      value: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PowerDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents a pressure measurement for platform transfer.
class PressureDto extends MeasurementUnitDto {
  PressureDto({
    required this.unit,
    required this.value,
  });

  /// The unit in which the value is expressed.
  PressureUnitDto unit;

  /// The numeric value of the pressure.
  double value;

  List<Object?> _toList() {
    return <Object?>[
      unit,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static PressureDto decode(Object result) {
    result as List<Object?>;
    return PressureDto(
      unit: result[0]! as PressureUnitDto,
      value: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PressureDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents a temperature measurement for platform transfer.
class TemperatureDto extends MeasurementUnitDto {
  TemperatureDto({
    required this.unit,
    required this.value,
  });

  /// The unit in which the value is expressed.
  TemperatureUnitDto unit;

  /// The numeric value of the temperature.
  double value;

  List<Object?> _toList() {
    return <Object?>[
      unit,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static TemperatureDto decode(Object result) {
    result as List<Object?>;
    return TemperatureDto(
      unit: result[0]! as TemperatureUnitDto,
      value: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! TemperatureDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents a velocity measurement for platform transfer.
class VelocityDto extends MeasurementUnitDto {
  VelocityDto({
    required this.unit,
    required this.value,
  });

  /// The unit in which the value is expressed.
  VelocityUnitDto unit;

  /// The numeric value of the velocity.
  double value;

  List<Object?> _toList() {
    return <Object?>[
      unit,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static VelocityDto decode(Object result) {
    result as List<Object?>;
    return VelocityDto(
      unit: result[0]! as VelocityUnitDto,
      value: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VelocityDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents a volume measurement for platform transfer.
class VolumeDto extends MeasurementUnitDto {
  VolumeDto({
    required this.unit,
    required this.value,
  });

  /// The unit in which the value is expressed.
  VolumeUnitDto unit;

  /// The numeric value of the volume.
  double value;

  List<Object?> _toList() {
    return <Object?>[
      unit,
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static VolumeDto decode(Object result) {
    result as List<Object?>;
    return VolumeDto(
      unit: result[0]! as VolumeUnitDto,
      value: result[1]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VolumeDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents data origin (source application) for health records.
class DataOriginDto {
  DataOriginDto({
    required this.packageName,
  });

  /// The package name of the source app.
  String packageName;

  List<Object?> _toList() {
    return <Object?>[
      packageName,
    ];
  }

  Object encode() {
    return _toList();  }

  static DataOriginDto decode(Object result) {
    result as List<Object?>;
    return DataOriginDto(
      packageName: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DataOriginDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents device information for health data recording.
class DeviceDto {
  DeviceDto({
    this.firmwareVersion,
    this.hardwareVersion,
    this.localIdentifier,
    this.manufacturer,
    this.model,
    this.name,
    this.softwareVersion,
    this.udiDeviceIdentifier,
  });

  /// The firmware version of the device.
  String? firmwareVersion;

  /// The hardware version of the device.
  String? hardwareVersion;

  /// A local identifier for the device.
  String? localIdentifier;

  /// The device manufacturer.
  String? manufacturer;

  /// The device model.
  String? model;

  /// The name of the device.
  String? name;

  /// The software version of the device.
  String? softwareVersion;

  /// The UDI (Unique Device Identifier) for the device.
  String? udiDeviceIdentifier;

  List<Object?> _toList() {
    return <Object?>[
      firmwareVersion,
      hardwareVersion,
      localIdentifier,
      manufacturer,
      model,
      name,
      softwareVersion,
      udiDeviceIdentifier,
    ];
  }

  Object encode() {
    return _toList();  }

  static DeviceDto decode(Object result) {
    result as List<Object?>;
    return DeviceDto(
      firmwareVersion: result[0] as String?,
      hardwareVersion: result[1] as String?,
      localIdentifier: result[2] as String?,
      manufacturer: result[3] as String?,
      model: result[4] as String?,
      name: result[5] as String?,
      softwareVersion: result[6] as String?,
      udiDeviceIdentifier: result[7] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DeviceDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents metadata for a health record.
class MetadataDto {
  MetadataDto({
    this.clientRecordId,
    this.clientRecordVersion,
    required this.dataOrigin,
    this.device,
    required this.recordingMethod,
  });

  /// A custom identifier assigned by your application.
  ///
  /// Use this for client-side record tracking, deduplication, or correlation.
  String? clientRecordId;

  /// A version number assigned by your application.
  ///
  /// Use this to implement your own versioning or tracking logic.
  int? clientRecordVersion;

  /// The application that wrote this health record.
  DataOriginDto dataOrigin;

  /// The device that recorded the data (optional).
  DeviceDto? device;

  /// The method used to record this data.
  RecordingMethodDto recordingMethod;

  List<Object?> _toList() {
    return <Object?>[
      clientRecordId,
      clientRecordVersion,
      dataOrigin,
      device,
      recordingMethod,
    ];
  }

  Object encode() {
    return _toList();  }

  static MetadataDto decode(Object result) {
    result as List<Object?>;
    return MetadataDto(
      clientRecordId: result[0] as String?,
      clientRecordVersion: result[1] as int?,
      dataOrigin: result[2]! as DataOriginDto,
      device: result[3] as DeviceDto?,
      recordingMethod: result[4]! as RecordingMethodDto,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MetadataDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents a permission request for accessing specific health data.
class HealthDataPermissionDto {
  HealthDataPermissionDto({
    required this.accessType,
    required this.healthDataType,
  });

  /// The type of access being requested (read or write).
  PermissionAccessTypeDto accessType;

  /// The type of health data for which permission is requested.
  HealthDataTypeDto healthDataType;

  List<Object?> _toList() {
    return <Object?>[
      accessType,
      healthDataType,
    ];
  }

  Object encode() {
    return _toList();  }

  static HealthDataPermissionDto decode(Object result) {
    result as List<Object?>;
    return HealthDataPermissionDto(
      accessType: result[0]! as PermissionAccessTypeDto,
      healthDataType: result[1]! as HealthDataTypeDto,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HealthDataPermissionDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Sealed class for all health record DTOs.
sealed class HealthRecordDto {
}

/// Represents an active calories burned record for platform transfer.
class ActiveCaloriesBurnedRecordDto extends HealthRecordDto {
  ActiveCaloriesBurnedRecordDto({
    required this.energy,
    required this.endTime,
    this.id,
    required this.metadata,
    required this.startTime,
    this.endZoneOffsetSeconds,
    this.startZoneOffsetSeconds,
  });

  /// Energy (calories) burned during the interval.
  EnergyDto energy;

  /// End time in milliseconds since epoch (UTC).
  int endTime;

  /// Platform-assigned unique identifier.
  String? id;

  /// Metadata about this record.
  MetadataDto metadata;

  /// Start time in milliseconds since epoch (UTC).
  int startTime;

  /// Timezone offset in seconds for end time (optional).
  int? endZoneOffsetSeconds;

  /// Timezone offset in seconds for start time (optional).
  int? startZoneOffsetSeconds;

  List<Object?> _toList() {
    return <Object?>[
      energy,
      endTime,
      id,
      metadata,
      startTime,
      endZoneOffsetSeconds,
      startZoneOffsetSeconds,
    ];
  }

  Object encode() {
    return _toList();  }

  static ActiveCaloriesBurnedRecordDto decode(Object result) {
    result as List<Object?>;
    return ActiveCaloriesBurnedRecordDto(
      energy: result[0]! as EnergyDto,
      endTime: result[1]! as int,
      id: result[2] as String?,
      metadata: result[3]! as MetadataDto,
      startTime: result[4]! as int,
      endZoneOffsetSeconds: result[5] as int?,
      startZoneOffsetSeconds: result[6] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ActiveCaloriesBurnedRecordDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents a distance record for platform transfer.
class DistanceRecordDto extends HealthRecordDto {
  DistanceRecordDto({
    required this.distance,
    required this.endTime,
    this.id,
    required this.metadata,
    required this.startTime,
    this.endZoneOffsetSeconds,
    this.startZoneOffsetSeconds,
  });

  /// Distance traveled during the interval.
  LengthDto distance;

  /// End time in milliseconds since epoch (UTC).
  int endTime;

  /// Platform-assigned unique identifier.
  String? id;

  /// Metadata about this record.
  MetadataDto metadata;

  /// Start time in milliseconds since epoch (UTC).
  int startTime;

  /// Timezone offset in seconds for end time (optional).
  int? endZoneOffsetSeconds;

  /// Timezone offset in seconds for start time (optional).
  int? startZoneOffsetSeconds;

  List<Object?> _toList() {
    return <Object?>[
      distance,
      endTime,
      id,
      metadata,
      startTime,
      endZoneOffsetSeconds,
      startZoneOffsetSeconds,
    ];
  }

  Object encode() {
    return _toList();  }

  static DistanceRecordDto decode(Object result) {
    result as List<Object?>;
    return DistanceRecordDto(
      distance: result[0]! as LengthDto,
      endTime: result[1]! as int,
      id: result[2] as String?,
      metadata: result[3]! as MetadataDto,
      startTime: result[4]! as int,
      endZoneOffsetSeconds: result[5] as int?,
      startZoneOffsetSeconds: result[6] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DistanceRecordDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents a floors climbed record for platform transfer.
class FloorsClimbedRecordDto extends HealthRecordDto {
  FloorsClimbedRecordDto({
    required this.floors,
    required this.endTime,
    this.id,
    required this.metadata,
    required this.startTime,
    this.endZoneOffsetSeconds,
    this.startZoneOffsetSeconds,
  });

  /// Number of floors (flights of stairs) climbed during the interval.
  NumericDto floors;

  /// End time in milliseconds since epoch (UTC).
  int endTime;

  /// Platform-assigned unique identifier.
  String? id;

  /// Metadata about this record.
  MetadataDto metadata;

  /// Start time in milliseconds since epoch (UTC).
  int startTime;

  /// Timezone offset in seconds for end time (optional).
  int? endZoneOffsetSeconds;

  /// Timezone offset in seconds for start time (optional).
  int? startZoneOffsetSeconds;

  List<Object?> _toList() {
    return <Object?>[
      floors,
      endTime,
      id,
      metadata,
      startTime,
      endZoneOffsetSeconds,
      startZoneOffsetSeconds,
    ];
  }

  Object encode() {
    return _toList();  }

  static FloorsClimbedRecordDto decode(Object result) {
    result as List<Object?>;
    return FloorsClimbedRecordDto(
      floors: result[0]! as NumericDto,
      endTime: result[1]! as int,
      id: result[2] as String?,
      metadata: result[3]! as MetadataDto,
      startTime: result[4]! as int,
      endZoneOffsetSeconds: result[5] as int?,
      startZoneOffsetSeconds: result[6] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FloorsClimbedRecordDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents a wheelchair pushes record for platform transfer.
class WheelchairPushesRecordDto extends HealthRecordDto {
  WheelchairPushesRecordDto({
    required this.pushes,
    required this.endTime,
    this.id,
    required this.metadata,
    required this.startTime,
    this.endZoneOffsetSeconds,
    this.startZoneOffsetSeconds,
  });

  /// Number of wheelchair pushes performed during the interval.
  NumericDto pushes;

  /// End time in milliseconds since epoch (UTC).
  int endTime;

  /// Platform-assigned unique identifier.
  String? id;

  /// Metadata about this record.
  MetadataDto metadata;

  /// Start time in milliseconds since epoch (UTC).
  int startTime;

  /// Timezone offset in seconds for end time (optional).
  int? endZoneOffsetSeconds;

  /// Timezone offset in seconds for start time (optional).
  int? startZoneOffsetSeconds;

  List<Object?> _toList() {
    return <Object?>[
      pushes,
      endTime,
      id,
      metadata,
      startTime,
      endZoneOffsetSeconds,
      startZoneOffsetSeconds,
    ];
  }

  Object encode() {
    return _toList();  }

  static WheelchairPushesRecordDto decode(Object result) {
    result as List<Object?>;
    return WheelchairPushesRecordDto(
      pushes: result[0]! as NumericDto,
      endTime: result[1]! as int,
      id: result[2] as String?,
      metadata: result[3]! as MetadataDto,
      startTime: result[4]! as int,
      endZoneOffsetSeconds: result[5] as int?,
      startZoneOffsetSeconds: result[6] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WheelchairPushesRecordDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents a step count record for platform transfer.
class StepRecordDto extends HealthRecordDto {
  StepRecordDto({
    required this.count,
    required this.endTime,
    this.id,
    required this.metadata,
    required this.startTime,
    this.endZoneOffsetSeconds,
    this.startZoneOffsetSeconds,
  });

  /// Number of steps taken during the interval (must be >= 0).
  NumericDto count;

  /// End time in milliseconds since epoch (UTC).
  int endTime;

  /// Platform-assigned unique identifier.
  String? id;

  /// Metadata about this record.
  MetadataDto metadata;

  /// Start time in milliseconds since epoch (UTC).
  int startTime;

  /// Timezone offset in seconds for end time (optional).
  int? endZoneOffsetSeconds;

  /// Timezone offset in seconds for start time (optional).
  int? startZoneOffsetSeconds;

  List<Object?> _toList() {
    return <Object?>[
      count,
      endTime,
      id,
      metadata,
      startTime,
      endZoneOffsetSeconds,
      startZoneOffsetSeconds,
    ];
  }

  Object encode() {
    return _toList();  }

  static StepRecordDto decode(Object result) {
    result as List<Object?>;
    return StepRecordDto(
      count: result[0]! as NumericDto,
      endTime: result[1]! as int,
      id: result[2] as String?,
      metadata: result[3]! as MetadataDto,
      startTime: result[4]! as int,
      endZoneOffsetSeconds: result[5] as int?,
      startZoneOffsetSeconds: result[6] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! StepRecordDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents a weight record for platform transfer.
class WeightRecordDto extends HealthRecordDto {
  WeightRecordDto({
    this.id,
    required this.metadata,
    required this.time,
    required this.weight,
    this.zoneOffsetSeconds,
  });

  /// Platform-assigned unique identifier.
  String? id;

  /// Metadata about this record.
  MetadataDto metadata;

  /// Measurement time in milliseconds since epoch (UTC).
  int time;

  /// Weight measurement.
  MassDto weight;

  /// Timezone offset in seconds for measurement time (optional).
  int? zoneOffsetSeconds;

  List<Object?> _toList() {
    return <Object?>[
      id,
      metadata,
      time,
      weight,
      zoneOffsetSeconds,
    ];
  }

  Object encode() {
    return _toList();  }

  static WeightRecordDto decode(Object result) {
    result as List<Object?>;
    return WeightRecordDto(
      id: result[0] as String?,
      metadata: result[1]! as MetadataDto,
      time: result[2]! as int,
      weight: result[3]! as MassDto,
      zoneOffsetSeconds: result[4] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WeightRecordDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// DTO for lean body mass health data.
class LeanBodyMassRecordDto extends HealthRecordDto {
  LeanBodyMassRecordDto({
    this.id,
    required this.metadata,
    required this.time,
    required this.mass,
    this.zoneOffsetSeconds,
  });

  /// Platform-assigned unique identifier.
  String? id;

  /// Metadata about this record.
  MetadataDto metadata;

  /// Measurement time in milliseconds since epoch (UTC).
  int time;

  /// Lean body mass measurement.
  MassDto mass;

  /// Timezone offset in seconds for measurement time (optional).
  int? zoneOffsetSeconds;

  List<Object?> _toList() {
    return <Object?>[
      id,
      metadata,
      time,
      mass,
      zoneOffsetSeconds,
    ];
  }

  Object encode() {
    return _toList();  }

  static LeanBodyMassRecordDto decode(Object result) {
    result as List<Object?>;
    return LeanBodyMassRecordDto(
      id: result[0] as String?,
      metadata: result[1]! as MetadataDto,
      time: result[2]! as int,
      mass: result[3]! as MassDto,
      zoneOffsetSeconds: result[4] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! LeanBodyMassRecordDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// DTO for body height health data.
class HeightRecordDto extends HealthRecordDto {
  HeightRecordDto({
    this.id,
    required this.metadata,
    required this.time,
    required this.height,
    this.zoneOffsetSeconds,
  });

  /// Platform-assigned unique identifier.
  String? id;

  /// Metadata about this record.
  MetadataDto metadata;

  /// Measurement time in milliseconds since epoch (UTC).
  int time;

  /// Height measurement.
  LengthDto height;

  /// Timezone offset in seconds for measurement time (optional).
  int? zoneOffsetSeconds;

  List<Object?> _toList() {
    return <Object?>[
      id,
      metadata,
      time,
      height,
      zoneOffsetSeconds,
    ];
  }

  Object encode() {
    return _toList();  }

  static HeightRecordDto decode(Object result) {
    result as List<Object?>;
    return HeightRecordDto(
      id: result[0] as String?,
      metadata: result[1]! as MetadataDto,
      time: result[2]! as int,
      height: result[3]! as LengthDto,
      zoneOffsetSeconds: result[4] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HeightRecordDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// DTO for body fat percentage health data.
class BodyFatPercentageRecordDto extends HealthRecordDto {
  BodyFatPercentageRecordDto({
    this.id,
    required this.metadata,
    required this.time,
    required this.percentage,
    this.zoneOffsetSeconds,
  });

  /// Platform-assigned unique identifier.
  String? id;

  /// Metadata about this record.
  MetadataDto metadata;

  /// Measurement time in milliseconds since epoch (UTC).
  int time;

  /// Body fat percentage measurement.
  PercentageDto percentage;

  /// Timezone offset in seconds for measurement time (optional).
  int? zoneOffsetSeconds;

  List<Object?> _toList() {
    return <Object?>[
      id,
      metadata,
      time,
      percentage,
      zoneOffsetSeconds,
    ];
  }

  Object encode() {
    return _toList();  }

  static BodyFatPercentageRecordDto decode(Object result) {
    result as List<Object?>;
    return BodyFatPercentageRecordDto(
      id: result[0] as String?,
      metadata: result[1]! as MetadataDto,
      time: result[2]! as int,
      percentage: result[3]! as PercentageDto,
      zoneOffsetSeconds: result[4] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BodyFatPercentageRecordDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// DTO for body temperature health data.
class BodyTemperatureRecordDto extends HealthRecordDto {
  BodyTemperatureRecordDto({
    this.id,
    required this.metadata,
    required this.time,
    required this.temperature,
    this.zoneOffsetSeconds,
  });

  /// Platform-assigned unique identifier.
  String? id;

  /// Metadata about this record.
  MetadataDto metadata;

  /// Measurement time in milliseconds since epoch (UTC).
  int time;

  /// Body temperature measurement.
  TemperatureDto temperature;

  /// Timezone offset in seconds for measurement time (optional).
  int? zoneOffsetSeconds;

  List<Object?> _toList() {
    return <Object?>[
      id,
      metadata,
      time,
      temperature,
      zoneOffsetSeconds,
    ];
  }

  Object encode() {
    return _toList();  }

  static BodyTemperatureRecordDto decode(Object result) {
    result as List<Object?>;
    return BodyTemperatureRecordDto(
      id: result[0] as String?,
      metadata: result[1]! as MetadataDto,
      time: result[2]! as int,
      temperature: result[3]! as TemperatureDto,
      zoneOffsetSeconds: result[4] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! BodyTemperatureRecordDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents a hydration (water intake) record for platform transfer.
class HydrationRecordDto extends HealthRecordDto {
  HydrationRecordDto({
    this.id,
    required this.startTime,
    required this.endTime,
    required this.metadata,
    required this.volume,
    this.startZoneOffsetSeconds,
    this.endZoneOffsetSeconds,
  });

  /// Platform-assigned unique identifier.
  String? id;

  /// Start time in milliseconds since epoch (UTC).
  int startTime;

  /// End time in milliseconds since epoch (UTC).
  int endTime;

  /// Metadata about this record.
  MetadataDto metadata;

  /// Volume of water consumed during the interval.
  VolumeDto volume;

  /// Timezone offset in seconds for start time (optional).
  int? startZoneOffsetSeconds;

  /// Timezone offset in seconds for end time (optional).
  int? endZoneOffsetSeconds;

  List<Object?> _toList() {
    return <Object?>[
      id,
      startTime,
      endTime,
      metadata,
      volume,
      startZoneOffsetSeconds,
      endZoneOffsetSeconds,
    ];
  }

  Object encode() {
    return _toList();  }

  static HydrationRecordDto decode(Object result) {
    result as List<Object?>;
    return HydrationRecordDto(
      id: result[0] as String?,
      startTime: result[1]! as int,
      endTime: result[2]! as int,
      metadata: result[3]! as MetadataDto,
      volume: result[4]! as VolumeDto,
      startZoneOffsetSeconds: result[5] as int?,
      endZoneOffsetSeconds: result[6] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HydrationRecordDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents a single heart rate measurement for platform transfer.
///
/// This is a platform-agnostic value class used within heart rate records.
/// It contains a timestamp and BPM value without ID or metadata.
class HeartRateMeasurementDto {
  HeartRateMeasurementDto({
    required this.time,
    required this.beatsPerMinute,
  });

  /// Timestamp in milliseconds since epoch (UTC).
  int time;

  /// Heart rate value in beats per minute (BPM).
  NumericDto beatsPerMinute;

  List<Object?> _toList() {
    return <Object?>[
      time,
      beatsPerMinute,
    ];
  }

  Object encode() {
    return _toList();  }

  static HeartRateMeasurementDto decode(Object result) {
    result as List<Object?>;
    return HeartRateMeasurementDto(
      time: result[0]! as int,
      beatsPerMinute: result[1]! as NumericDto,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HeartRateMeasurementDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents a heart rate measurement record for platform transfer (iOS).
class HeartRateMeasurementRecordDto extends HealthRecordDto {
  HeartRateMeasurementRecordDto({
    this.id,
    required this.time,
    required this.metadata,
    required this.measurement,
    this.zoneOffsetSeconds,
  });

  /// Platform-assigned unique identifier.
  String? id;

  /// Measurement time in milliseconds since epoch (UTC).
  int time;

  /// Metadata about this record.
  MetadataDto metadata;

  /// The heart rate measurement.
  HeartRateMeasurementDto measurement;

  /// Timezone offset in seconds for measurement time (optional).
  int? zoneOffsetSeconds;

  List<Object?> _toList() {
    return <Object?>[
      id,
      time,
      metadata,
      measurement,
      zoneOffsetSeconds,
    ];
  }

  Object encode() {
    return _toList();  }

  static HeartRateMeasurementRecordDto decode(Object result) {
    result as List<Object?>;
    return HeartRateMeasurementRecordDto(
      id: result[0] as String?,
      time: result[1]! as int,
      metadata: result[2]! as MetadataDto,
      measurement: result[3]! as HeartRateMeasurementDto,
      zoneOffsetSeconds: result[4] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HeartRateMeasurementRecordDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents the result of a health data permission request.
class HealthDataPermissionRequestResultDto {
  HealthDataPermissionRequestResultDto({
    required this.permission,
    required this.status,
  });

  /// The health data permission that was requested.
  HealthDataPermissionDto permission;

  /// The status of the permission after the request.
  PermissionStatusDto status;

  List<Object?> _toList() {
    return <Object?>[
      permission,
      status,
    ];
  }

  Object encode() {
    return _toList();  }

  static HealthDataPermissionRequestResultDto decode(Object result) {
    result as List<Object?>;
    return HealthDataPermissionRequestResultDto(
      permission: result[0]! as HealthDataPermissionDto,
      status: result[1]! as PermissionStatusDto,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! HealthDataPermissionRequestResultDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents a permissions request.
class PermissionsRequestDto {
  PermissionsRequestDto({
    required this.healthDataPermissions,
  });

  /// List of health data permissions to request.
  List<HealthDataPermissionDto> healthDataPermissions;

  List<Object?> _toList() {
    return <Object?>[
      healthDataPermissions,
    ];
  }

  Object encode() {
    return _toList();  }

  static PermissionsRequestDto decode(Object result) {
    result as List<Object?>;
    return PermissionsRequestDto(
      healthDataPermissions: (result[0] as List<Object?>?)!.cast<HealthDataPermissionDto>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PermissionsRequestDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Represents the response from a permissions request.
class PermissionsRequestResponseDto {
  PermissionsRequestResponseDto({
    required this.healthDataPermissionResults,
  });

  /// Results for each health data permission that was requested.
  List<HealthDataPermissionRequestResultDto> healthDataPermissionResults;

  List<Object?> _toList() {
    return <Object?>[
      healthDataPermissionResults,
    ];
  }

  Object encode() {
    return _toList();  }

  static PermissionsRequestResponseDto decode(Object result) {
    result as List<Object?>;
    return PermissionsRequestResponseDto(
      healthDataPermissionResults: (result[0] as List<Object?>?)!.cast<HealthDataPermissionRequestResultDto>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PermissionsRequestResponseDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Request to perform aggregation on health records.
class AggregateRequestDto {
  AggregateRequestDto({
    required this.aggregationMetric,
    required this.dataType,
    required this.endTime,
    required this.startTime,
  });

  /// The type of aggregation to perform.
  AggregationMetricDto aggregationMetric;

  /// The type of health data to aggregate.
  HealthDataTypeDto dataType;

  /// End of time range in milliseconds since epoch (UTC), exclusive.
  int endTime;

  /// Start of time range in milliseconds since epoch (UTC), inclusive.
  int startTime;

  List<Object?> _toList() {
    return <Object?>[
      aggregationMetric,
      dataType,
      endTime,
      startTime,
    ];
  }

  Object encode() {
    return _toList();  }

  static AggregateRequestDto decode(Object result) {
    result as List<Object?>;
    return AggregateRequestDto(
      aggregationMetric: result[0]! as AggregationMetricDto,
      dataType: result[1]! as HealthDataTypeDto,
      endTime: result[2]! as int,
      startTime: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AggregateRequestDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Response containing aggregated value.
class AggregateResponseDto {
  AggregateResponseDto({
    required this.value,
  });

  /// Aggregated value.
  MeasurementUnitDto value;

  List<Object?> _toList() {
    return <Object?>[
      value,
    ];
  }

  Object encode() {
    return _toList();  }

  static AggregateResponseDto decode(Object result) {
    result as List<Object?>;
    return AggregateResponseDto(
      value: result[0]! as MeasurementUnitDto,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AggregateResponseDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Request to delete specific records by their IDs.
class DeleteRecordsByIdsRequestDto {
  DeleteRecordsByIdsRequestDto({
    required this.dataType,
    required this.recordIds,
  });

  /// The type of health data to delete.
  HealthDataTypeDto dataType;

  /// List of unique identifiers for records to delete.
  List<String> recordIds;

  List<Object?> _toList() {
    return <Object?>[
      dataType,
      recordIds,
    ];
  }

  Object encode() {
    return _toList();  }

  static DeleteRecordsByIdsRequestDto decode(Object result) {
    result as List<Object?>;
    return DeleteRecordsByIdsRequestDto(
      dataType: result[0]! as HealthDataTypeDto,
      recordIds: (result[1] as List<Object?>?)!.cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DeleteRecordsByIdsRequestDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Request to delete records by time range.
class DeleteRecordsByTimeRangeRequestDto {
  DeleteRecordsByTimeRangeRequestDto({
    required this.dataType,
    required this.endTime,
    required this.startTime,
  });

  /// The type of health data to delete.
  HealthDataTypeDto dataType;

  /// End of time range in milliseconds since epoch (UTC), exclusive.
  int endTime;

  /// Start of time range in milliseconds since epoch (UTC), inclusive.
  int startTime;

  List<Object?> _toList() {
    return <Object?>[
      dataType,
      endTime,
      startTime,
    ];
  }

  Object encode() {
    return _toList();  }

  static DeleteRecordsByTimeRangeRequestDto decode(Object result) {
    result as List<Object?>;
    return DeleteRecordsByTimeRangeRequestDto(
      dataType: result[0]! as HealthDataTypeDto,
      endTime: result[1]! as int,
      startTime: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DeleteRecordsByTimeRangeRequestDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Request to read a single health record by ID.
class ReadRecordRequestDto {
  ReadRecordRequestDto({
    required this.recordId,
    required this.dataType,
  });

  /// The unique identifier of the record to read.
  String recordId;

  /// The type of health data to read.
  HealthDataTypeDto dataType;

  List<Object?> _toList() {
    return <Object?>[
      recordId,
      dataType,
    ];
  }

  Object encode() {
    return _toList();  }

  static ReadRecordRequestDto decode(Object result) {
    result as List<Object?>;
    return ReadRecordRequestDto(
      recordId: result[0]! as String,
      dataType: result[1]! as HealthDataTypeDto,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ReadRecordRequestDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Response containing a single health record.
class ReadRecordResponseDto {
  ReadRecordResponseDto({
    this.record,
  });

  /// The health record that was read.
  HealthRecordDto? record;

  List<Object?> _toList() {
    return <Object?>[
      record,
    ];
  }

  Object encode() {
    return _toList();  }

  static ReadRecordResponseDto decode(Object result) {
    result as List<Object?>;
    return ReadRecordResponseDto(
      record: result[0] as HealthRecordDto?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ReadRecordResponseDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Request to read multiple health records within a time range.
class ReadRecordsRequestDto {
  ReadRecordsRequestDto({
    required this.dataType,
    required this.pageSize,
    this.pageToken,
    required this.startTime,
    required this.endTime,
    this.dataOriginPackageNames = const [],
  });

  /// The type of health data to read.
  HealthDataTypeDto dataType;

  /// Maximum number of records to return per page (1-10,000).
  int pageSize;

  /// Opaque pagination token for fetching next page (optional).
  ///
  /// Provided by previous response's nextPageToken.
  String? pageToken;

  /// Start of time range in milliseconds since epoch (UTC), inclusive.
  int startTime;

  /// End of time range in milliseconds since epoch (UTC), exclusive.
  int endTime;

  /// List of package names to filter by.
  List<String> dataOriginPackageNames;

  List<Object?> _toList() {
    return <Object?>[
      dataType,
      pageSize,
      pageToken,
      startTime,
      endTime,
      dataOriginPackageNames,
    ];
  }

  Object encode() {
    return _toList();  }

  static ReadRecordsRequestDto decode(Object result) {
    result as List<Object?>;
    return ReadRecordsRequestDto(
      dataType: result[0]! as HealthDataTypeDto,
      pageSize: result[1]! as int,
      pageToken: result[2] as String?,
      startTime: result[3]! as int,
      endTime: result[4]! as int,
      dataOriginPackageNames: (result[5] as List<Object?>?)!.cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ReadRecordsRequestDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Response containing paginated health records.
class ReadRecordsResponseDto {
  ReadRecordsResponseDto({
    this.nextPageToken,
    required this.records,
  });

  /// Token for fetching next page, null if no more pages exist.
  String? nextPageToken;

  /// List of health records that were read.
  List<HealthRecordDto> records;

  List<Object?> _toList() {
    return <Object?>[
      nextPageToken,
      records,
    ];
  }

  Object encode() {
    return _toList();  }

  static ReadRecordsResponseDto decode(Object result) {
    result as List<Object?>;
    return ReadRecordsResponseDto(
      nextPageToken: result[0] as String?,
      records: (result[1] as List<Object?>?)!.cast<HealthRecordDto>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ReadRecordsResponseDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Request to write a single health record.
class WriteRecordRequestDto {
  WriteRecordRequestDto({
    required this.record,
  });

  /// Health record.
  HealthRecordDto record;

  List<Object?> _toList() {
    return <Object?>[
      record,
    ];
  }

  Object encode() {
    return _toList();  }

  static WriteRecordRequestDto decode(Object result) {
    result as List<Object?>;
    return WriteRecordRequestDto(
      record: result[0]! as HealthRecordDto,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WriteRecordRequestDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Response after writing a single record.
class WriteRecordResponseDto {
  WriteRecordResponseDto({
    required this.recordId,
  });

  /// Platform-assigned unique identifier for the written record.
  String recordId;

  List<Object?> _toList() {
    return <Object?>[
      recordId,
    ];
  }

  Object encode() {
    return _toList();  }

  static WriteRecordResponseDto decode(Object result) {
    result as List<Object?>;
    return WriteRecordResponseDto(
      recordId: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WriteRecordResponseDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Request to write multiple health records atomically.
class WriteRecordsRequestDto {
  WriteRecordsRequestDto({
    required this.records,
  });

  /// Records being written.
  List<HealthRecordDto> records;

  List<Object?> _toList() {
    return <Object?>[
      records,
    ];
  }

  Object encode() {
    return _toList();  }

  static WriteRecordsRequestDto decode(Object result) {
    result as List<Object?>;
    return WriteRecordsRequestDto(
      records: (result[0] as List<Object?>?)!.cast<HealthRecordDto>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WriteRecordsRequestDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Response after writing multiple records.
class WriteRecordsResponseDto {
  WriteRecordsResponseDto({
    required this.recordIds,
  });

  /// Platform-assigned unique identifiers for written records.
  List<String> recordIds;

  List<Object?> _toList() {
    return <Object?>[
      recordIds,
    ];
  }

  Object encode() {
    return _toList();  }

  static WriteRecordsResponseDto decode(Object result) {
    result as List<Object?>;
    return WriteRecordsResponseDto(
      recordIds: (result[0] as List<Object?>?)!.cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! WriteRecordsResponseDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Request to update a single health record.
class UpdateRecordRequestDto {
  UpdateRecordRequestDto({
    required this.record,
  });

  /// The health record to update.
  HealthRecordDto record;

  List<Object?> _toList() {
    return <Object?>[
      record,
    ];
  }

  Object encode() {
    return _toList();  }

  static UpdateRecordRequestDto decode(Object result) {
    result as List<Object?>;
    return UpdateRecordRequestDto(
      record: result[0]! as HealthRecordDto,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UpdateRecordRequestDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Response after updating a single record.
class UpdateRecordResponseDto {
  UpdateRecordResponseDto({
    required this.recordId,
  });

  /// Platform-assigned unique identifier for the updated record.
  String recordId;

  List<Object?> _toList() {
    return <Object?>[
      recordId,
    ];
  }

  Object encode() {
    return _toList();  }

  static UpdateRecordResponseDto decode(Object result) {
    result as List<Object?>;
    return UpdateRecordResponseDto(
      recordId: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UpdateRecordResponseDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is HealthConnectorErrorCodeDto) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is HealthPlatformStatusDto) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is BloodGlucoseUnitDto) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is EnergyUnitDto) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is LengthUnitDto) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is MassUnitDto) {
      buffer.putUint8(134);
      writeValue(buffer, value.index);
    }    else if (value is NumericUnitDto) {
      buffer.putUint8(135);
      writeValue(buffer, value.index);
    }    else if (value is PercentageUnitDto) {
      buffer.putUint8(136);
      writeValue(buffer, value.index);
    }    else if (value is PermissionAccessTypeDto) {
      buffer.putUint8(137);
      writeValue(buffer, value.index);
    }    else if (value is PermissionStatusDto) {
      buffer.putUint8(138);
      writeValue(buffer, value.index);
    }    else if (value is PressureUnitDto) {
      buffer.putUint8(139);
      writeValue(buffer, value.index);
    }    else if (value is PowerUnitDto) {
      buffer.putUint8(140);
      writeValue(buffer, value.index);
    }    else if (value is TemperatureUnitDto) {
      buffer.putUint8(141);
      writeValue(buffer, value.index);
    }    else if (value is VelocityUnitDto) {
      buffer.putUint8(142);
      writeValue(buffer, value.index);
    }    else if (value is VolumeUnitDto) {
      buffer.putUint8(143);
      writeValue(buffer, value.index);
    }    else if (value is RecordingMethodDto) {
      buffer.putUint8(144);
      writeValue(buffer, value.index);
    }    else if (value is HealthDataTypeDto) {
      buffer.putUint8(145);
      writeValue(buffer, value.index);
    }    else if (value is AggregationMetricDto) {
      buffer.putUint8(146);
      writeValue(buffer, value.index);
    }    else if (value is BloodGlucoseDto) {
      buffer.putUint8(147);
      writeValue(buffer, value.encode());
    }    else if (value is EnergyDto) {
      buffer.putUint8(148);
      writeValue(buffer, value.encode());
    }    else if (value is LengthDto) {
      buffer.putUint8(149);
      writeValue(buffer, value.encode());
    }    else if (value is MassDto) {
      buffer.putUint8(150);
      writeValue(buffer, value.encode());
    }    else if (value is NumericDto) {
      buffer.putUint8(151);
      writeValue(buffer, value.encode());
    }    else if (value is PercentageDto) {
      buffer.putUint8(152);
      writeValue(buffer, value.encode());
    }    else if (value is PowerDto) {
      buffer.putUint8(153);
      writeValue(buffer, value.encode());
    }    else if (value is PressureDto) {
      buffer.putUint8(154);
      writeValue(buffer, value.encode());
    }    else if (value is TemperatureDto) {
      buffer.putUint8(155);
      writeValue(buffer, value.encode());
    }    else if (value is VelocityDto) {
      buffer.putUint8(156);
      writeValue(buffer, value.encode());
    }    else if (value is VolumeDto) {
      buffer.putUint8(157);
      writeValue(buffer, value.encode());
    }    else if (value is DataOriginDto) {
      buffer.putUint8(158);
      writeValue(buffer, value.encode());
    }    else if (value is DeviceDto) {
      buffer.putUint8(159);
      writeValue(buffer, value.encode());
    }    else if (value is MetadataDto) {
      buffer.putUint8(160);
      writeValue(buffer, value.encode());
    }    else if (value is HealthDataPermissionDto) {
      buffer.putUint8(161);
      writeValue(buffer, value.encode());
    }    else if (value is ActiveCaloriesBurnedRecordDto) {
      buffer.putUint8(162);
      writeValue(buffer, value.encode());
    }    else if (value is DistanceRecordDto) {
      buffer.putUint8(163);
      writeValue(buffer, value.encode());
    }    else if (value is FloorsClimbedRecordDto) {
      buffer.putUint8(164);
      writeValue(buffer, value.encode());
    }    else if (value is WheelchairPushesRecordDto) {
      buffer.putUint8(165);
      writeValue(buffer, value.encode());
    }    else if (value is StepRecordDto) {
      buffer.putUint8(166);
      writeValue(buffer, value.encode());
    }    else if (value is WeightRecordDto) {
      buffer.putUint8(167);
      writeValue(buffer, value.encode());
    }    else if (value is LeanBodyMassRecordDto) {
      buffer.putUint8(168);
      writeValue(buffer, value.encode());
    }    else if (value is HeightRecordDto) {
      buffer.putUint8(169);
      writeValue(buffer, value.encode());
    }    else if (value is BodyFatPercentageRecordDto) {
      buffer.putUint8(170);
      writeValue(buffer, value.encode());
    }    else if (value is BodyTemperatureRecordDto) {
      buffer.putUint8(171);
      writeValue(buffer, value.encode());
    }    else if (value is HydrationRecordDto) {
      buffer.putUint8(172);
      writeValue(buffer, value.encode());
    }    else if (value is HeartRateMeasurementDto) {
      buffer.putUint8(173);
      writeValue(buffer, value.encode());
    }    else if (value is HeartRateMeasurementRecordDto) {
      buffer.putUint8(174);
      writeValue(buffer, value.encode());
    }    else if (value is HealthDataPermissionRequestResultDto) {
      buffer.putUint8(175);
      writeValue(buffer, value.encode());
    }    else if (value is PermissionsRequestDto) {
      buffer.putUint8(176);
      writeValue(buffer, value.encode());
    }    else if (value is PermissionsRequestResponseDto) {
      buffer.putUint8(177);
      writeValue(buffer, value.encode());
    }    else if (value is AggregateRequestDto) {
      buffer.putUint8(178);
      writeValue(buffer, value.encode());
    }    else if (value is AggregateResponseDto) {
      buffer.putUint8(179);
      writeValue(buffer, value.encode());
    }    else if (value is DeleteRecordsByIdsRequestDto) {
      buffer.putUint8(180);
      writeValue(buffer, value.encode());
    }    else if (value is DeleteRecordsByTimeRangeRequestDto) {
      buffer.putUint8(181);
      writeValue(buffer, value.encode());
    }    else if (value is ReadRecordRequestDto) {
      buffer.putUint8(182);
      writeValue(buffer, value.encode());
    }    else if (value is ReadRecordResponseDto) {
      buffer.putUint8(183);
      writeValue(buffer, value.encode());
    }    else if (value is ReadRecordsRequestDto) {
      buffer.putUint8(184);
      writeValue(buffer, value.encode());
    }    else if (value is ReadRecordsResponseDto) {
      buffer.putUint8(185);
      writeValue(buffer, value.encode());
    }    else if (value is WriteRecordRequestDto) {
      buffer.putUint8(186);
      writeValue(buffer, value.encode());
    }    else if (value is WriteRecordResponseDto) {
      buffer.putUint8(187);
      writeValue(buffer, value.encode());
    }    else if (value is WriteRecordsRequestDto) {
      buffer.putUint8(188);
      writeValue(buffer, value.encode());
    }    else if (value is WriteRecordsResponseDto) {
      buffer.putUint8(189);
      writeValue(buffer, value.encode());
    }    else if (value is UpdateRecordRequestDto) {
      buffer.putUint8(190);
      writeValue(buffer, value.encode());
    }    else if (value is UpdateRecordResponseDto) {
      buffer.putUint8(191);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : HealthConnectorErrorCodeDto.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : HealthPlatformStatusDto.values[value];
      case 131: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : BloodGlucoseUnitDto.values[value];
      case 132: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : EnergyUnitDto.values[value];
      case 133: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : LengthUnitDto.values[value];
      case 134: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : MassUnitDto.values[value];
      case 135: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : NumericUnitDto.values[value];
      case 136: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PercentageUnitDto.values[value];
      case 137: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PermissionAccessTypeDto.values[value];
      case 138: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PermissionStatusDto.values[value];
      case 139: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PressureUnitDto.values[value];
      case 140: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PowerUnitDto.values[value];
      case 141: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : TemperatureUnitDto.values[value];
      case 142: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : VelocityUnitDto.values[value];
      case 143: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : VolumeUnitDto.values[value];
      case 144: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : RecordingMethodDto.values[value];
      case 145: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : HealthDataTypeDto.values[value];
      case 146: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : AggregationMetricDto.values[value];
      case 147: 
        return BloodGlucoseDto.decode(readValue(buffer)!);
      case 148: 
        return EnergyDto.decode(readValue(buffer)!);
      case 149: 
        return LengthDto.decode(readValue(buffer)!);
      case 150: 
        return MassDto.decode(readValue(buffer)!);
      case 151: 
        return NumericDto.decode(readValue(buffer)!);
      case 152: 
        return PercentageDto.decode(readValue(buffer)!);
      case 153: 
        return PowerDto.decode(readValue(buffer)!);
      case 154: 
        return PressureDto.decode(readValue(buffer)!);
      case 155: 
        return TemperatureDto.decode(readValue(buffer)!);
      case 156: 
        return VelocityDto.decode(readValue(buffer)!);
      case 157: 
        return VolumeDto.decode(readValue(buffer)!);
      case 158: 
        return DataOriginDto.decode(readValue(buffer)!);
      case 159: 
        return DeviceDto.decode(readValue(buffer)!);
      case 160: 
        return MetadataDto.decode(readValue(buffer)!);
      case 161: 
        return HealthDataPermissionDto.decode(readValue(buffer)!);
      case 162: 
        return ActiveCaloriesBurnedRecordDto.decode(readValue(buffer)!);
      case 163: 
        return DistanceRecordDto.decode(readValue(buffer)!);
      case 164: 
        return FloorsClimbedRecordDto.decode(readValue(buffer)!);
      case 165: 
        return WheelchairPushesRecordDto.decode(readValue(buffer)!);
      case 166: 
        return StepRecordDto.decode(readValue(buffer)!);
      case 167: 
        return WeightRecordDto.decode(readValue(buffer)!);
      case 168: 
        return LeanBodyMassRecordDto.decode(readValue(buffer)!);
      case 169: 
        return HeightRecordDto.decode(readValue(buffer)!);
      case 170: 
        return BodyFatPercentageRecordDto.decode(readValue(buffer)!);
      case 171: 
        return BodyTemperatureRecordDto.decode(readValue(buffer)!);
      case 172: 
        return HydrationRecordDto.decode(readValue(buffer)!);
      case 173: 
        return HeartRateMeasurementDto.decode(readValue(buffer)!);
      case 174: 
        return HeartRateMeasurementRecordDto.decode(readValue(buffer)!);
      case 175: 
        return HealthDataPermissionRequestResultDto.decode(readValue(buffer)!);
      case 176: 
        return PermissionsRequestDto.decode(readValue(buffer)!);
      case 177: 
        return PermissionsRequestResponseDto.decode(readValue(buffer)!);
      case 178: 
        return AggregateRequestDto.decode(readValue(buffer)!);
      case 179: 
        return AggregateResponseDto.decode(readValue(buffer)!);
      case 180: 
        return DeleteRecordsByIdsRequestDto.decode(readValue(buffer)!);
      case 181: 
        return DeleteRecordsByTimeRangeRequestDto.decode(readValue(buffer)!);
      case 182: 
        return ReadRecordRequestDto.decode(readValue(buffer)!);
      case 183: 
        return ReadRecordResponseDto.decode(readValue(buffer)!);
      case 184: 
        return ReadRecordsRequestDto.decode(readValue(buffer)!);
      case 185: 
        return ReadRecordsResponseDto.decode(readValue(buffer)!);
      case 186: 
        return WriteRecordRequestDto.decode(readValue(buffer)!);
      case 187: 
        return WriteRecordResponseDto.decode(readValue(buffer)!);
      case 188: 
        return WriteRecordsRequestDto.decode(readValue(buffer)!);
      case 189: 
        return WriteRecordsResponseDto.decode(readValue(buffer)!);
      case 190: 
        return UpdateRecordRequestDto.decode(readValue(buffer)!);
      case 191: 
        return UpdateRecordResponseDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

/// The main API for communicating with the health platform.
class HealthConnectorPlatformApi {
  /// Constructor for [HealthConnectorPlatformApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  HealthConnectorPlatformApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<AggregateResponseDto> aggregate(AggregateRequestDto request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.health_connector_hk_ios.HealthConnectorPlatformApi.aggregate$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as AggregateResponseDto?)!;
    }
  }

  Future<void> deleteRecordsByIds(DeleteRecordsByIdsRequestDto request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.health_connector_hk_ios.HealthConnectorPlatformApi.deleteRecordsByIds$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> deleteRecordsByTimeRange(DeleteRecordsByTimeRangeRequestDto request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.health_connector_hk_ios.HealthConnectorPlatformApi.deleteRecordsByTimeRange$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<HealthPlatformStatusDto> getHealthPlatformStatus() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.health_connector_hk_ios.HealthConnectorPlatformApi.getHealthPlatformStatus$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as HealthPlatformStatusDto?)!;
    }
  }

  Future<PermissionsRequestResponseDto> requestPermissions(PermissionsRequestDto request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.health_connector_hk_ios.HealthConnectorPlatformApi.requestPermissions$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as PermissionsRequestResponseDto?)!;
    }
  }

  Future<ReadRecordResponseDto?> readRecord(ReadRecordRequestDto request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.health_connector_hk_ios.HealthConnectorPlatformApi.readRecord$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as ReadRecordResponseDto?);
    }
  }

  Future<ReadRecordsResponseDto> readRecords(ReadRecordsRequestDto request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.health_connector_hk_ios.HealthConnectorPlatformApi.readRecords$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as ReadRecordsResponseDto?)!;
    }
  }

  Future<WriteRecordResponseDto> writeRecord(WriteRecordRequestDto request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.health_connector_hk_ios.HealthConnectorPlatformApi.writeRecord$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as WriteRecordResponseDto?)!;
    }
  }

  Future<WriteRecordsResponseDto> writeRecords(WriteRecordsRequestDto request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.health_connector_hk_ios.HealthConnectorPlatformApi.writeRecords$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as WriteRecordsResponseDto?)!;
    }
  }

  Future<UpdateRecordResponseDto> updateRecord(UpdateRecordRequestDto request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.health_connector_hk_ios.HealthConnectorPlatformApi.updateRecord$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as UpdateRecordResponseDto?)!;
    }
  }
}
