import 'package:collection/collection.dart';
import 'package:health_connector_logger/src/models/health_connector_log_level.dart';
import 'package:meta/meta.dart' show immutable;

/// A structured log event emitted by `HealthConnectorLogger`.
///
/// Represents a single log entry with all associated metadata including
/// the log level, tag, operation, timestamp, and optional contextual data.
@immutable
final class HealthConnectorLog {
  /// The severity level of this log entry.
  final HealthConnectorLogLevel level;

  /// A tag for categorizing the log entry.
  ///
  /// Typically represents the source or category of the log,
  /// such as 'HealthConnector', 'HealthConnectorHCClient', or
  /// 'HealthConnectorHKClient'.
  final String tag;

  /// The operation being logged.
  ///
  /// Examples: 'read_records', 'write_records', 'request_permissions'.
  final String operation;

  /// The timestamp when this log was created.
  final DateTime dateTime;

  /// Optional descriptive message.
  final String? message;

  /// Optional contextual information as key-value pairs.
  ///
  /// Examples: `{'recordCount': 42, 'duration': '123ms'}`.
  final Map<String, dynamic>? context;

  /// Optional exception object if an error occurred.
  final Object? exception;

  /// Optional stack trace associated with the exception.
  final StackTrace? stackTrace;

  /// The formatted structured message.
  ///
  /// This is the JSON-like formatted output generated by the logger's
  /// formatting logic, including all fields with proper indentation.
  final String structuredMessage;

  /// Creates a [HealthConnectorLog] with the specified properties.
  const HealthConnectorLog({
    required this.level,
    required this.tag,
    required this.operation,
    required this.dateTime,
    required this.structuredMessage,
    this.message,
    this.context,
    this.exception,
    this.stackTrace,
  });

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is HealthConnectorLog &&
          runtimeType == other.runtimeType &&
          level == other.level &&
          tag == other.tag &&
          operation == other.operation &&
          dateTime == other.dateTime &&
          message == other.message &&
          const MapEquality<String, dynamic>().equals(
            context,
            other.context,
          ) &&
          exception == other.exception &&
          stackTrace == other.stackTrace &&
          structuredMessage == other.structuredMessage;

  @override
  int get hashCode =>
      level.hashCode ^
      tag.hashCode ^
      operation.hashCode ^
      dateTime.hashCode ^
      message.hashCode ^
      context.hashCode ^
      exception.hashCode ^
      stackTrace.hashCode ^
      structuredMessage.hashCode;

  @override
  String toString() =>
      'HealthConnectorLog('
      'level: ${level.name}, '
      'tag: $tag, '
      'operation: $operation, '
      'dateTime: $dateTime, '
      'message: $message, '
      'context: $context, '
      'exception: $exception, '
      'stackTrace: $stackTrace, '
      'structuredMessage: $structuredMessage'
      ')';
}
