name: health_connector_example
resolution: workspace
description: "Demonstrates how to use the health_connector plugin."
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  health_connector:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  health_connector_lint:
    path: ../../health_connector_lint

flutter:
  uses-material-design: true
