import 'package:health_connector_core/health_connector_core.dart';
import 'package:parameterized_test/parameterized_test.dart';
import 'package:test/test.dart';

void main() {
  group(
    'HealthDataType Category Getters',
    () {
      parameterizedTest(
        'returns only data types for specific category',
        [
          [
            HealthDataType.activityTypes.toList(),
            HealthDataTypeCategory.activity,
            <HealthDataType>[
              HealthDataType.activeEnergyBurned,
              HealthDataType.activityIntensity,
              HealthDataType.exerciseTime,
              HealthDataType.moveTime,
              HealthDataType.standTime,
              HealthDataType.basalEnergyBurned,
              HealthDataType.basalMetabolicRate,
              HealthDataType.crossCountrySkiingDistance,
              HealthDataType.cyclingPedalingCadence,
              HealthDataType.cyclingPedalingCadenceSeries,
              HealthDataType.cyclingPower,
              HealthDataType.distance,
              HealthDataType.downhillSnowSportsDistance,
              HealthDataType.elevationGained,
              HealthDataType.environmentalAudioExposure,
              HealthDataType.environmentalAudioExposureEvent,
              HealthDataType.exerciseSession,
              HealthDataType.headphoneAudioExposure,
              HealthDataType.headphoneAudioExposureEvent,
              HealthDataType.floorsClimbed,
              HealthDataType.lowCardioFitnessEvent,
              HealthDataType.paddleSportsDistance,
              HealthDataType.powerSeries,
              HealthDataType.rowingDistance,
              HealthDataType.runningGroundContactTime,
              HealthDataType.runningPower,
              HealthDataType.runningStrideLength,
              HealthDataType.skatingSportsDistance,
              HealthDataType.speedSeries,
              HealthDataType.steps,
              HealthDataType.stepsCadenceSeries,
              HealthDataType.swimmingDistance,
              HealthDataType.swimmingStrokes,
              HealthDataType.totalEnergyBurned,
              HealthDataType.walkingRunningDistance,
              HealthDataType.wheelchairDistance,
              HealthDataType.wheelchairPushes,
            ],
          ],
          [
            HealthDataType.bodyMeasurementTypes.toList(),
            HealthDataTypeCategory.bodyMeasurement,
            <HealthDataType>[
              HealthDataType.bodyWaterMass,
              HealthDataType.boneMass,
              HealthDataType.bodyMassIndex,
              HealthDataType.bodyFatPercentage,
              HealthDataType.height,
              HealthDataType.leanBodyMass,
              HealthDataType.waistCircumference,
              HealthDataType.weight,
            ],
          ],
          [
            HealthDataType.clinicalTypes.toList(),
            HealthDataTypeCategory.clinical,
            <HealthDataType>[
              HealthDataType.inhalerUsage,
              HealthDataType.insulinDelivery,
            ],
          ],
          [
            HealthDataType.mentalHealthTypes.toList(),
            HealthDataTypeCategory.mentalHealth,
            <HealthDataType>[HealthDataType.mindfulnessSession],
          ],
          [
            HealthDataType.mobilityTypes.toList(),
            HealthDataTypeCategory.mobility,
            <HealthDataType>[
              HealthDataType.numberOfTimesFallen,
              HealthDataType.walkingSteadiness,
              HealthDataType.runningSpeed,
              HealthDataType.sixMinuteWalkTestDistance,
              HealthDataType.stairAscentSpeed,
              HealthDataType.stairDescentSpeed,
              HealthDataType.walkingAsymmetryPercentage,
              HealthDataType.walkingDoubleSupportPercentage,
              HealthDataType.walkingSpeed,
              HealthDataType.walkingSteadinessEvent,
              HealthDataType.walkingStepLength,
            ],
          ],
          [
            HealthDataType.nutritionTypes.toList(),
            HealthDataTypeCategory.nutrition,
            <HealthDataType>[
              HealthDataType.alcoholicBeverages,
              HealthDataType.dietaryBiotin,
              HealthDataType.dietaryCaffeine,
              HealthDataType.dietaryCalcium,
              HealthDataType.dietaryCholesterol,
              HealthDataType.dietaryFiber,
              HealthDataType.dietaryEnergyConsumed,
              HealthDataType.dietaryFolate,
              HealthDataType.dietaryIron,
              HealthDataType.dietaryMagnesium,
              HealthDataType.dietaryManganese,
              HealthDataType.dietaryMonounsaturatedFat,
              HealthDataType.dietaryNiacin,
              HealthDataType.dietaryPantothenicAcid,
              HealthDataType.dietaryPhosphorus,
              HealthDataType.dietaryPolyunsaturatedFat,
              HealthDataType.dietaryPotassium,
              HealthDataType.dietaryProtein,
              HealthDataType.dietaryRiboflavin,
              HealthDataType.dietarySaturatedFat,
              HealthDataType.dietarySelenium,
              HealthDataType.dietarySodium,
              HealthDataType.dietarySugar,
              HealthDataType.dietaryThiamin,
              HealthDataType.dietaryTotalCarbohydrate,
              HealthDataType.dietaryTotalFat,
              HealthDataType.dietaryVitaminA,
              HealthDataType.dietaryVitaminB12,
              HealthDataType.dietaryVitaminB6,
              HealthDataType.dietaryVitaminC,
              HealthDataType.dietaryVitaminD,
              HealthDataType.dietaryVitaminE,
              HealthDataType.dietaryVitaminK,
              HealthDataType.dietaryZinc,
              HealthDataType.hydration,
              HealthDataType.nutrition,
            ],
          ],
          [
            HealthDataType.reproductiveHealthTypes.toList(),
            HealthDataTypeCategory.reproductiveHealth,
            <HealthDataType>[
              HealthDataType.basalBodyTemperature,
              HealthDataType.cervicalMucus,
              HealthDataType.contraceptive,
              HealthDataType.infrequentMenstrualCycleEvent,
              HealthDataType.intermenstrualBleeding,
              HealthDataType.irregularMenstrualCycleEvent,
              HealthDataType.lactation,
              HealthDataType.menstrualFlow,
              HealthDataType.menstrualFlowInstant,
              HealthDataType.menstruationPeriod,
              HealthDataType.ovulationTest,
              HealthDataType.persistentIntermenstrualBleedingEvent,
              HealthDataType.pregnancy,
              HealthDataType.pregnancyTest,
              HealthDataType.progesteroneTest,
              HealthDataType.prolongedMenstrualPeriodEvent,
              HealthDataType.sexualActivity,
            ],
          ],
          [
            HealthDataType.sleepTypes.toList(),
            HealthDataTypeCategory.sleep,
            <HealthDataType>[
              HealthDataType.sleepSession,
              HealthDataType.sleepStageRecord,
            ],
          ],
          [
            HealthDataType.vitalsTypes.toList(),
            HealthDataTypeCategory.vitals,
            <HealthDataType>[
              HealthDataType.atrialFibrillationBurden,
              HealthDataType.electrodermalActivity,
              HealthDataType.bloodAlcoholContent,
              HealthDataType.bloodGlucose,
              HealthDataType.bloodPressure,
              HealthDataType.bodyTemperature,
              HealthDataType.diastolicBloodPressure,
              HealthDataType.forcedExpiratoryVolume,
              HealthDataType.forcedVitalCapacity,
              HealthDataType.heartRate,
              HealthDataType.heartRateRecoveryOneMinute,
              HealthDataType.heartRateSeries,
              HealthDataType.heartRateVariabilityRMSSD,
              HealthDataType.heartRateVariabilitySDNN,
              HealthDataType.highHeartRateEvent,
              HealthDataType.irregularHeartRhythmEvent,
              HealthDataType.lowHeartRateEvent,
              HealthDataType.oxygenSaturation,
              HealthDataType.peakExpiratoryFlowRate,
              HealthDataType.peripheralPerfusionIndex,
              HealthDataType.respiratoryRate,
              HealthDataType.restingHeartRate,
              HealthDataType.sleepingWristTemperature,
              HealthDataType.skinTemperatureDeltaSeries,
              HealthDataType.systolicBloodPressure,
              HealthDataType.vo2Max,
              HealthDataType.walkingHeartRateAverage,
            ],
          ],
        ],
        (
          List<HealthDataType> dataTypes,
          HealthDataTypeCategory expectedCategory,
          List<HealthDataType> expectedDataTypes,
        ) {
          for (final dataType in dataTypes) {
            expect(
              dataType.category,
              equals(expectedCategory),
              reason: '$dataType should be in $expectedCategory category',
            );
          }

          expect(
            dataTypes,
            equals(expectedDataTypes),
            reason: '$expectedCategory should contain all expected data types',
          );
        },
      );

      test('all data types are categorized', () {
        final allDataTypes = HealthDataType.values.toSet();
        final categorizedTypes = <HealthDataType>{};

        categorizedTypes.addAll(HealthDataType.activityTypes);
        categorizedTypes.addAll(HealthDataType.bodyMeasurementTypes);
        categorizedTypes.addAll(HealthDataType.clinicalTypes);
        categorizedTypes.addAll(HealthDataType.mentalHealthTypes);
        categorizedTypes.addAll(HealthDataType.mobilityTypes);
        categorizedTypes.addAll(HealthDataType.nutritionTypes);
        categorizedTypes.addAll(HealthDataType.reproductiveHealthTypes);
        categorizedTypes.addAll(HealthDataType.sleepTypes);
        categorizedTypes.addAll(HealthDataType.vitalsTypes);

        expect(
          categorizedTypes,
          equals(allDataTypes),
          reason: 'Every data type should be assigned to exactly one category',
        );
      });
    },
  );
}
