name: health_connector_hk_ios_example
resolution: workspace
description: "Demonstrates how to use the health_connector_hk_ios plugin."
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  health_connector_core: ^2.0.0
  health_connector_hk_ios: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  health_connector_lint: ^1.2.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
