package com.phamtunglam.health_connector_hc_android

import android.content.Context
import androidx.activity.ComponentActivity
import androidx.annotation.VisibleForTesting
import com.phamtunglam.health_connector_hc_android.exceptions.HealthConnectorException
import com.phamtunglam.health_connector_hc_android.logger.HealthConnectorLogger
import com.phamtunglam.health_connector_hc_android.mappers.toDto
import com.phamtunglam.health_connector_hc_android.pigeon.AggregateRequestDto
import com.phamtunglam.health_connector_hc_android.pigeon.DeleteRecordsByIdsRequestDto
import com.phamtunglam.health_connector_hc_android.pigeon.DeleteRecordsByTimeRangeRequestDto
import com.phamtunglam.health_connector_hc_android.pigeon.DeleteRecordsRequestDto
import com.phamtunglam.health_connector_hc_android.pigeon.HealthConnectorConfigDto
import com.phamtunglam.health_connector_hc_android.pigeon.HealthConnectorErrorDto
import com.phamtunglam.health_connector_hc_android.pigeon.HealthConnectorHCAndroidApi
import com.phamtunglam.health_connector_hc_android.pigeon.HealthDataSyncResultDto
import com.phamtunglam.health_connector_hc_android.pigeon.HealthDataSyncTokenDto
import com.phamtunglam.health_connector_hc_android.pigeon.HealthDataTypeDto
import com.phamtunglam.health_connector_hc_android.pigeon.HealthPlatformFeatureDto
import com.phamtunglam.health_connector_hc_android.pigeon.HealthPlatformFeatureStatusDto
import com.phamtunglam.health_connector_hc_android.pigeon.HealthPlatformStatusDto
import com.phamtunglam.health_connector_hc_android.pigeon.HealthRecordDto
import com.phamtunglam.health_connector_hc_android.pigeon.MeasurementUnitDto
import com.phamtunglam.health_connector_hc_android.pigeon.PermissionRequestDto
import com.phamtunglam.health_connector_hc_android.pigeon.PermissionRequestResultDto
import com.phamtunglam.health_connector_hc_android.pigeon.PermissionRequestsDto
import com.phamtunglam.health_connector_hc_android.pigeon.PermissionStatusDto
import com.phamtunglam.health_connector_hc_android.pigeon.ReadRecordRequestDto
import com.phamtunglam.health_connector_hc_android.pigeon.ReadRecordsRequestDto
import com.phamtunglam.health_connector_hc_android.pigeon.ReadRecordsResponseDto
import com.phamtunglam.health_connector_hc_android.utils.aggregationMetric
import com.phamtunglam.health_connector_hc_android.utils.dataType
import io.flutter.embedding.engine.plugins.FlutterPlugin
import io.flutter.embedding.engine.plugins.activity.ActivityAware
import io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding
import kotlin.coroutines.cancellation.CancellationException
import kotlinx.coroutines.CoroutineExceptionHandler
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.launch
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock

/**
 * Flutter plugin for accessing Health Connect on Android devices.
 *
 * This plugin implements the [HealthConnectorHCAndroidApi] interface generated by Pigeon
 * and bridges Flutter/Dart to the Android Health Connect SDK.
 *
 * ## Usage in Production
 *
 * Flutter automatically instantiates this plugin using the default no-argument constructor.
 *
 * ## Usage in Tests
 *
 * ```kotlin
 * val testDispatcher = StandardTestDispatcher()
 * val plugin = HealthConnectorHCAndroidPlugin(ioDispatcher = testDispatcher)
 * plugin.setContext(mockContext)
 * plugin.setActivity(mockActivity)
 * plugin.setClient(mockClient)
 * ```
 */
class HealthConnectorHCAndroidPlugin @VisibleForTesting internal constructor(
    private val dispatchers: DispatcherProvider = StandardDispatcherProvider,
) : FlutterPlugin,
    ActivityAware,
    HealthConnectorHCAndroidApi {

    /**
     * Application context used for accessing Health Connect services.
     * Initialized in [onAttachedToEngine] and persists throughout the plugin lifecycle.
     */
    private lateinit var context: Context

    /**
     * The current Flutter activity, required for operations that need activity context.
     * This is nullable because the activity may be detached during configuration changes
     * or when the app is in the background.
     *
     * @see onAttachedToActivity
     * @see onDetachedFromActivity
     */
    private var activity: ComponentActivity? = null

    /**
     * Mutex to ensure thread-safe initialization of [client].
     * Prevents race conditions when multiple concurrent calls to [initialize] attempt
     * to create the client simultaneously.
     */
    private val clientInitMutex: Mutex = Mutex()

    /**
     * Cached instance of [HealthConnectorClient].
     * Created lazily on first use via [initialize] and reused for subsequent operations.
     * Nullable to support testing without requiring full initialization.
     */
    private var client: HealthConnectorClient? = null

    /**
     * Coroutine scope for executing asynchronous Health Connect operations.
     *
     * Uses [DispatcherProvider.io] for background execution and [SupervisorJob] to prevent
     * cancellation of sibling coroutines when one fails.
     */
    private val scope: CoroutineScope = CoroutineScope(
        SupervisorJob() + dispatchers.io + CoroutineExceptionHandler { _, e ->
            HealthConnectorLogger.warning(
                "HealthConnectorHCAndroidPlugin",
                operation = "coroutine_exception_handler",
                message = "Unhandled exception in coroutine scope",
                exception = e,
            )
        },
    )

    // region Flutter/Android lifecycle

    /**
     * Called when the plugin is attached to a Flutter engine.
     *
     * @param flutterPluginBinding Provides access to the Flutter engine and application context
     */
    override fun onAttachedToEngine(flutterPluginBinding: FlutterPlugin.FlutterPluginBinding) {
        context = flutterPluginBinding.applicationContext
        HealthConnectorHCAndroidApi.setUp(flutterPluginBinding.binaryMessenger, this)

        HealthConnectorLogger.initialize(
            scope,
            flutterPluginBinding.binaryMessenger,
        )
    }

    /**
     * Called when the plugin is detached from the Flutter engine.
     *
     * @param binding The Flutter plugin binding being detached
     */
    override fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        HealthConnectorHCAndroidApi.setUp(binding.binaryMessenger, null)
        scope.cancel()
    }

    /**
     * Called when the plugin is attached to a Flutter activity.
     *
     * Validates that the activity is a [ComponentActivity] (required for Health Connect permissions request)
     * and stores it for later use in permission requests.
     *
     * @param binding Provides access to the Flutter activity
     * @throws IllegalStateException if the activity is not a [ComponentActivity]
     */
    @Throws(IllegalStateException::class)
    override fun onAttachedToActivity(binding: ActivityPluginBinding) {
        val activityInstance = binding.activity
        check(activityInstance is ComponentActivity) {
            "Activity must be a ComponentActivity."
        }
        activity = activityInstance
    }

    /**
     * Called when the activity is detached for configuration changes (e.g., screen rotation).
     *
     * Temporarily clears the activity reference. The activity will be reattached via
     * [onReattachedToActivityForConfigChanges] after the configuration change completes.
     */
    override fun onDetachedFromActivityForConfigChanges() {
        activity = null
    }

    /**
     * Called when the activity is reattached after configuration changes.
     *
     * Validates and restores the activity reference after configuration changes like screen rotation.
     *
     * @param binding Provides access to the reattached Flutter activity
     * @throws IllegalStateException if the activity is not a [ComponentActivity]
     */
    @Throws(IllegalStateException::class)
    override fun onReattachedToActivityForConfigChanges(binding: ActivityPluginBinding) {
        val activityInstance = binding.activity
        check(activityInstance is ComponentActivity) {
            "Activity must be a ComponentActivity"
        }
        activity = activityInstance
    }

    /**
     * Called when the activity is detached from the plugin.
     *
     * This is a permanent detachment (not due to configuration changes).
     * Clears the activity reference to prevent memory leaks.
     */
    override fun onDetachedFromActivity() {
        activity = null
    }

    // endregion

    // region Plugin API

    /**
     * Initializes the Health Connector client with the provided configuration.
     *
     * This method must be called before any other Health Connector operations
     * to properly configure the native platform code, including logger settings.
     *
     * @param config Configuration settings for the Health Connector
     * @param callback Called with a [Result] indicating success or failure
     */
    override fun initialize(config: HealthConnectorConfigDto, callback: (Result<Unit>) -> Unit) {
        val operation = "initialize"
        val logContext = mapOf("is_logger_enabled" to config.isLoggerEnabled)

        scope.launch {
            HealthConnectorLogger.debug(
                TAG,
                operation = operation,
                message = "Initializing Health Connector Android plugin...",
                context = logContext,
            )

            try {
                clientInitMutex.withLock {
                    if (client == null) {
                        client = HealthConnectorClient.getOrCreate(
                            context = context,
                            dispatchers = dispatchers,
                        )
                    }
                }

                HealthConnectorLogger.isEnabled = config.isLoggerEnabled

                HealthConnectorLogger.debug(
                    TAG,
                    operation = operation,
                    message = "Initialized Health Connector Android plugin.",
                    context = logContext,
                )

                callback(Result.success(Unit))
            } catch (e: HealthConnectorException) {
                HealthConnectorLogger.error(
                    TAG,
                    operation = operation,
                    message = "Failed to initialize Health Connector Android plugin.",
                    context = logContext + mapOf(
                        "error_code" to e.code,
                        "error_message" to (e.message ?: "Unknown error"),
                    ),
                    exception = e,
                )

                callback(Result.failure(e))
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                HealthConnectorLogger.error(
                    TAG,
                    operation = operation,
                    message = "Unexpected error during initialization Health Connector " +
                        "Android plugin.",
                    context = logContext,
                    exception = e,
                )
                callback(
                    Result.failure(
                        HealthConnectorException.Unknown(
                            "Unexpected error: ${e.message ?: "Unknown error"}",
                            cause = e,
                        ).toDto(),
                    ),
                )
            }
        }
    }

    /**
     * Launches the Health Connect app page in the Google Play Store.
     *
     * Opens the Google Play Store application to the Health Connect app's detail page,
     * allowing users to install or update the app. This method should be called when
     * [getHealthPlatformStatus] indicates that Health Connect installation or update is required.
     *
     * @param callback Called with a [Result] indicating success or failure
     *
     * @throws HealthConnectorErrorDto if the Play Store cannot be launched or activity is unavailable
     */
    override fun launchHealthConnectPageInGooglePlay(callback: (Result<Unit>) -> Unit) {
        val operation = "launch_health_connect_page_in_google_play"

        try {
            val currentActivity = activity
            if (currentActivity == null) {
                HealthConnectorLogger.error(
                    TAG,
                    operation = operation,
                    message = "Cannot launch Play Store without activity context",
                )

                callback(
                    Result.failure(
                        HealthConnectorException.InvalidConfiguration(
                            message = "Activity is unavailable. " +
                                "The app may be in the background or " +
                                "activity has been destroyed.",
                        ).toDto(),
                    ),
                )

                return
            }

            HealthConnectorLogger.debug(
                TAG,
                operation = operation,
                message = "Launching Health Connect page in Google Play...",
            )

            HealthConnectorClient.launchHealthConnectPageInGooglePlay(currentActivity)

            HealthConnectorLogger.info(
                TAG,
                operation = operation,
                message = "Launched Health Connect page in Google Play.",
            )

            callback(Result.success(Unit))
        } catch (e: HealthConnectorException) {
            HealthConnectorLogger.error(
                TAG,
                operation = operation,
                message = "Failed to launch Health Connect page in Google Play",
                context = mapOf(
                    "error_code" to e.code,
                    "error_message" to (e.message ?: "Unknown error"),
                ),
                exception = e,
            )

            callback(Result.failure(e))
        } catch (e: Exception) {
            HealthConnectorLogger.error(
                "HealthConnectorHCAndroidPlugin",
                operation = "launch_health_connect_page_in_google_play",
                message = "Unexpected error while launching Play Store",
                exception = e,
            )

            callback(
                Result.failure(
                    HealthConnectorException.Unknown(
                        message = "Failed to launch Play Store: ${e.message ?: "Unknown error"}",
                        cause = e,
                    ).toDto(),
                ),
            )
        }
    }

    /**
     * Gets the current status of the Health Connect platform on the device.
     *
     * @param callback Called with a [Result] containing the platform status
     */
    override fun getHealthPlatformStatus(callback: (Result<HealthPlatformStatusDto>) -> Unit) {
        val operation = "get_health_platform_status"

        scope.launch {
            try {
                HealthConnectorLogger.debug(
                    TAG,
                    operation = operation,
                    message = "Getting health platform status...",
                )

                val statusDto = HealthConnectorClient.getHealthPlatformStatus(context)

                HealthConnectorLogger.info(
                    TAG,
                    operation = operation,
                    message = "Got health platform status.",
                )

                callback(Result.success(statusDto))
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                HealthConnectorLogger.error(
                    TAG,
                    operation = operation,
                    message = "Unexpected error while getting platform status",
                    exception = e,
                )
                callback(
                    Result.failure(
                        HealthConnectorException.Unknown(
                            message = "Unexpected error: ${e.message ?: "Unknown error"}",
                            cause = e,
                        ).toDto(),
                    ),
                )
            }
        }
    }

    /**
     * Requests permissions from the user.
     *
     * Requires an active [ComponentActivity].
     *
     * @param request The permissions request containing both health data and feature permissions
     * @param callback Called with a [Result] containing the permission request response
     */
    @Throws(HealthConnectorErrorDto::class)
    override fun requestPermissions(
        request: PermissionRequestsDto,
        callback: (Result<List<PermissionRequestResultDto>>) -> Unit,
    ) {
        val operation = "request_permissions"
        val logContext = mapOf("permission_count" to request.permissionRequests.size)

        scope.launch {
            try {
                val currentActivity = activity
                if (currentActivity == null) {
                    HealthConnectorLogger.error(
                        TAG,
                        operation = operation,
                        message = "Activity is null. " +
                            "Cannot request permissions without activity context",
                        context = logContext,
                    )

                    callback(
                        Result.failure(
                            HealthConnectorException.InvalidConfiguration(
                                message = "Activity is unavailable. " +
                                    "The app may be in the background or " +
                                    "activity has been destroyed.",
                            ).toDto(),
                        ),
                    )

                    return@launch
                }

                HealthConnectorLogger.debug(
                    TAG,
                    operation = operation,
                    message = "Requesting permissions...",
                    context = logContext,
                )

                val responseDto = requireClient().requestPermissions(
                    activity = currentActivity,
                    request = request,
                )

                HealthConnectorLogger.info(
                    TAG,
                    operation = operation,
                    message = "Requested permissions.",
                    context = logContext,
                )

                callback(Result.success(responseDto))
            } catch (e: HealthConnectorException) {
                HealthConnectorLogger.error(
                    TAG,
                    operation = operation,
                    message = "Failed to request Health Connect permissions",
                    context = logContext + mapOf(
                        "error_code" to e.code,
                        "error_message" to (e.message ?: "Unknown error"),
                    ),
                    exception = e,
                )

                callback(Result.failure(e))
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                HealthConnectorLogger.error(
                    TAG,
                    operation = operation,
                    message = "Unexpected error while requesting permissions",
                    context = logContext,
                    exception = e,
                )
                callback(
                    Result.failure(
                        HealthConnectorException.Unknown(
                            message = "Unexpected error: ${e.message ?: "Unknown error"}",
                            cause = e,
                        ).toDto(),
                    ),
                )
            }
        }
    }

    /**
     * Gets the current permission status for a specific permission.
     *
     * @param request The permission to check
     * @param callback Called with a [Result] containing the permission status
     */
    @Throws(HealthConnectorErrorDto::class)
    override fun getPermissionStatus(
        request: PermissionRequestDto,
        callback: (Result<PermissionStatusDto>) -> Unit,
    ) {
        val operation = "get_permission_status"
        val logContext = mapOf("permission" to request)

        scope.launch {
            process(
                operation = operation,
                context = logContext,
                callback = callback,
            ) {
                HealthConnectorLogger.debug(
                    TAG,
                    operation = operation,
                    message = "Getting permission status...",
                    context = logContext,
                )

                val result = requireClient().getPermissionStatus(request)

                HealthConnectorLogger.info(
                    TAG,
                    operation = operation,
                    message = "Got permission status.",
                    context = logContext,
                )

                result
            }
        }
    }

    /**
     * Gets all permissions that have been granted to the app.
     *
     * @param callback Called with a [Result] containing the permission response
     */
    @Throws(HealthConnectorErrorDto::class)
    override fun getGrantedPermissions(
        callback: (Result<List<PermissionRequestResultDto>>) -> Unit,
    ) {
        val operation = "get_granted_permissions"

        scope.launch {
            process(
                operation = operation,
                callback = callback,
            ) {
                HealthConnectorLogger.debug(
                    TAG,
                    operation = operation,
                    message = "Getting granted permissions...",
                )

                val result = requireClient().getGrantedPermissions()

                HealthConnectorLogger.info(
                    TAG,
                    operation = operation,
                    message = "Got granted permissions.",
                )

                result
            }
        }
    }

    /**
     * Revokes all permissions that have been granted to the app.
     *
     * @param callback Called with a [Result] containing the operation result
     */
    @Throws(HealthConnectorErrorDto::class)
    override fun revokeAllPermissions(callback: (Result<Unit>) -> Unit) {
        val operation = "revoke_all_permissions"

        scope.launch {
            process(
                operation = operation,
                callback = callback,
            ) {
                HealthConnectorLogger.debug(
                    TAG,
                    operation = operation,
                    message = "Revoking all permissions...",
                )

                requireClient().revokeAllPermissions()

                HealthConnectorLogger.info(
                    TAG,
                    operation = operation,
                    message = "Revoked all permissions.",
                )
            }
        }
    }

    /**
     * Gets the status of a specific feature on the current platform.
     *
     * @param feature The feature to check availability for
     * @param callback Called with a [Result] containing the feature status
     */
    @Throws(HealthConnectorErrorDto::class)
    override fun getFeatureStatus(
        feature: HealthPlatformFeatureDto,
        callback: (Result<HealthPlatformFeatureStatusDto>) -> Unit,
    ) {
        val operation = "get_feature_status"
        val logContext = mapOf("feature" to feature)

        scope.launch {
            process(
                operation = operation,
                context = logContext,
                callback = callback,
            ) {
                HealthConnectorLogger.debug(
                    TAG,
                    operation = operation,
                    message = "Getting feature status...",
                    context = logContext,
                )

                val result = requireClient().getFeatureStatus(context, feature)

                HealthConnectorLogger.info(
                    TAG,
                    operation = operation,
                    message = "Got feature status.",
                    context = logContext,
                )

                result
            }
        }
    }

    /**
     * Reads a single health record by ID.
     *
     * @param request Contains the data type and record ID to read
     * @param callback Called with a [Result] containing the read record response or null if not found
     */
    @Throws(HealthConnectorErrorDto::class)
    override fun readRecord(
        request: ReadRecordRequestDto,
        callback: (Result<HealthRecordDto?>) -> Unit,
    ) {
        val operation = "read_record"
        val logContext = mapOf(
            "data_type" to request.dataType,
            "record_id" to request.recordId,
        )

        scope.launch {
            process(
                operation = operation,
                context = logContext,
                callback = callback,
            ) {
                HealthConnectorLogger.debug(
                    TAG,
                    operation = operation,
                    message = "Reading record...",
                    context = logContext,
                )

                val result = requireClient().readRecord(request)

                HealthConnectorLogger.info(
                    TAG,
                    operation = operation,
                    message = "Read record.",
                    context = logContext,
                )

                result
            }
        }
    }

    /**
     * Reads multiple health records within a time range.
     *
     * @param request Contains data type, time range, page size, and optional page token
     * @param callback Called with a [Result] containing the read records response
     */
    @Throws(HealthConnectorErrorDto::class)
    override fun readRecords(
        request: ReadRecordsRequestDto,
        callback: (Result<ReadRecordsResponseDto>) -> Unit,
    ) {
        val operation = "read_records"
        val logContext = mapOf(
            "data_type" to request.dataType,
            "page_size" to request.pageSize,
        )

        scope.launch {
            process(
                operation = operation,
                context = logContext,
                callback = callback,
            ) {
                HealthConnectorLogger.debug(
                    TAG,
                    operation = operation,
                    message = "Reading records...",
                    context = logContext,
                )

                val result = requireClient().readRecords(request)

                HealthConnectorLogger.info(
                    TAG,
                    operation = operation,
                    message = "Read records.",
                    context = logContext,
                )

                result
            }
        }
    }

    /**
     * Writes a single health record.
     *
     * @param record The record to write
     * @param callback Called with a [Result] containing the new record ID
     */
    @Throws(HealthConnectorErrorDto::class)
    override fun writeRecord(record: HealthRecordDto, callback: (Result<String>) -> Unit) {
        val operation = "write_record"

        scope.launch {
            process(
                operation = operation,
                callback = callback,
            ) {
                HealthConnectorLogger.debug(
                    TAG,
                    operation = operation,
                    message = "Writing record...",
                )

                val result = requireClient().writeRecord(record)

                HealthConnectorLogger.info(
                    TAG,
                    operation = operation,
                    message = "Written record.",
                )

                result
            }
        }
    }

    /**
     * Writes multiple health records atomically.
     *
     * @param records The list of records to write
     * @param callback Called with a [Result] containing the list of IDs
     */
    @Throws(HealthConnectorErrorDto::class)
    override fun writeRecords(
        records: List<HealthRecordDto>,
        callback: (Result<List<String>>) -> Unit,
    ) {
        val operation = "write_records"
        val logContext = mapOf("records_count" to records.size)

        scope.launch {
            process(
                operation = operation,
                context = logContext,
                callback = callback,
            ) {
                HealthConnectorLogger.debug(
                    TAG,
                    operation = operation,
                    message = "Writing records...",
                    context = logContext,
                )

                val result = requireClient().writeRecords(records)

                HealthConnectorLogger.info(
                    TAG,
                    operation = operation,
                    message = "Written records.",
                    context = logContext,
                )

                result
            }
        }
    }

    /**
     * Updates a single health record.
     *
     * @param record The record to update
     * @param callback Called with a [Result] indicating success or failure
     */
    @Throws(HealthConnectorErrorDto::class)
    override fun updateRecord(record: HealthRecordDto, callback: (Result<Unit>) -> Unit) {
        val operation = "update_record"

        scope.launch {
            process(
                operation = operation,
                callback = callback,
            ) {
                HealthConnectorLogger.debug(
                    TAG,
                    operation = operation,
                    message = "Updating record...",
                )

                requireClient().updateRecord(record)

                HealthConnectorLogger.info(
                    TAG,
                    operation = operation,
                    message = "Updated record.",
                )
            }
        }
    }

    /**
     * Updates multiple health records atomically.
     *
     * @param records The list of records to update
     * @param callback Called with a [Result] indicating success or failure
     */
    @Throws(HealthConnectorErrorDto::class)
    override fun updateRecords(records: List<HealthRecordDto>, callback: (Result<Unit>) -> Unit) {
        val operation = "update_records"
        val logContext = mapOf("records_count" to records.size)

        scope.launch {
            process(
                operation = operation,
                context = logContext,
                callback = callback,
            ) {
                HealthConnectorLogger.debug(
                    TAG,
                    operation = operation,
                    message = "Updating records...",
                    context = logContext,
                )

                requireClient().updateRecords(records)

                HealthConnectorLogger.info(
                    TAG,
                    operation = operation,
                    message = "Updated records.",
                    context = logContext,
                )
            }
        }
    }

    /**
     * Deletes health records based on the request type.
     *
     * @param request The deletion request (either by IDs or time range)
     * @param callback Called with a [Result] indicating success or failure
     */
    override fun deleteRecords(
        request: DeleteRecordsRequestDto,
        callback: (Result<Unit>) -> Unit,
    ) {
        val operation = "delete_records"
        val logContext = mapOf("request_type" to request.javaClass.simpleName)

        scope.launch {
            process(
                operation = operation,
                context = logContext,
                callback = callback,
            ) {
                HealthConnectorLogger.debug(
                    TAG,
                    operation = operation,
                    message = "Deleting records...",
                    context = logContext,
                )

                val healthClient = requireClient()
                when (request) {
                    is DeleteRecordsByIdsRequestDto -> healthClient.deleteRecordsByIds(request)
                    is DeleteRecordsByTimeRangeRequestDto -> healthClient.deleteRecordsByTimeRange(
                        request,
                    )
                }

                HealthConnectorLogger.info(
                    TAG,
                    operation = operation,
                    message = "Deleted records.",
                    context = logContext,
                )
            }
        }
    }

    /**
     * Performs an aggregation query on health records.
     *
     * @param request Contains data type, aggregation metric, and time range
     * @param callback Called with a [Result] containing the aggregation response
     */
    @Throws(HealthConnectorErrorDto::class)
    override fun aggregate(
        request: AggregateRequestDto,
        callback: (Result<MeasurementUnitDto>) -> Unit,
    ) {
        val operation = "aggregate"
        val logContext = mapOf(
            "data_type" to request.dataType,
            "aggregation_metric" to request.aggregationMetric,
        )

        scope.launch {
            process(
                operation = operation,
                context = logContext,
                callback = callback,
            ) {
                HealthConnectorLogger.debug(
                    TAG,
                    operation = operation,
                    message = "Aggregating records...",
                    context = logContext,
                )

                val result = requireClient().aggregate(request)

                HealthConnectorLogger.info(
                    TAG,
                    operation = operation,
                    message = "Aggregated records.",
                    context = logContext,
                )

                result
            }
        }
    }

    override fun synchronize(
        dataTypes: List<HealthDataTypeDto>,
        syncToken: HealthDataSyncTokenDto?,
        callback: (Result<HealthDataSyncResultDto>) -> Unit,
    ) {
        val operation = "synchronize"
        val logContext = mapOf(
            "data_types" to dataTypes.joinToString(","),
        )

        scope.launch {
            process(
                operation = operation,
                context = logContext,
                callback = callback,
            ) {
                HealthConnectorLogger.debug(
                    TAG,
                    operation = operation,
                    message = "Synchronizing data...",
                    context = logContext,
                )

                val result = requireClient().synchronize(
                    dataTypes = dataTypes,
                    syncToken = syncToken,
                )

                HealthConnectorLogger.info(
                    TAG,
                    operation = operation,
                    message = "Synchronized data.",
                    context = logContext,
                )

                result
            }
        }
    }

    // endregion

    // region Private/internal methods

    /**
     * Sets the application context for testing purposes.
     *
     * This allows tests to inject a mock context without going through
     * the Flutter plugin lifecycle.
     *
     * @param context The context to use for Health Connect operations
     */
    @VisibleForTesting
    internal fun setContext(context: Context) {
        this.context = context
    }

    /**
     * Sets the Health Connect client for testing purposes.
     *
     * This allows tests to inject a mock client without calling [initialize].
     *
     * @param client The client to use for Health Connect operations
     */
    @VisibleForTesting
    internal fun setClient(client: HealthConnectorClient) {
        this.client = client
    }

    /**
     * Sets the activity for testing purposes.
     *
     * This allows tests to inject a mock activity without going through
     * the Flutter activity lifecycle.
     *
     * @param activity The activity to use for permission requests
     */
    @VisibleForTesting
    internal fun setActivity(activity: ComponentActivity?) {
        this.activity = activity
    }

    /**
     * Returns the [HealthConnectorClient] instance, or throws if not initialized.
     *
     * @return The initialized Health Connect client
     * @throws HealthConnectorException.InvalidConfiguration if the client has not been initialized
     */
    private fun requireClient(): HealthConnectorClient =
        client ?: throw HealthConnectorException.InvalidConfiguration(
            message = "Plugin not initialized. Call `initialize()` before using any API.",
        )

    // endregion

    companion object {
        private const val TAG = "HealthConnectorHCAndroidPlugin"

        /**
         * Executes a suspendable operation with standardized error handling.
         *
         * This method encapsulates the common error handling pattern used across all API methods:
         * - Catches [HealthConnectorException] and logs/converts to DTO
         * - Rethrows [CancellationException] to preserve structured concurrency
         * - Catches generic [Exception] and wraps in [HealthConnectorException.Unknown]
         *
         * @param T The success type returned by the operation
         * @param operation The operation name for logging purposes
         * @param context Additional context information for logging
         * @param callback The callback to invoke with the result
         * @param block The suspendable operation to execute
         */
        private suspend fun <T> process(
            operation: String,
            context: Map<String, Any> = emptyMap(),
            callback: (Result<T>) -> Unit,
            block: suspend () -> T,
        ) {
            try {
                callback(Result.success(block()))
            } catch (e: HealthConnectorException) {
                HealthConnectorLogger.error(
                    TAG,
                    operation = operation,
                    message = "Failed to execute $operation",
                    context = context + mapOf(
                        "error_code" to e.code,
                        "error_message" to (e.message ?: "Unknown error"),
                    ),
                    exception = e,
                )
                callback(Result.failure(e.toDto()))
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = operation,
                    message = "Unexpected error in $operation",
                    context = context,
                    exception = e,
                )
                callback(
                    Result.failure(
                        HealthConnectorException.Unknown(
                            message = "Unexpected error: ${e.message ?: "Unknown error"}",
                            cause = e,
                        ).toDto(),
                    ),
                )
            }
        }
    }
}
