package com.phamtunglam.health_connector_hc_android

import android.content.Context
import androidx.activity.ComponentActivity
import androidx.annotation.VisibleForTesting
import com.phamtunglam.health_connector_hc_android.logger.HealthConnectorLogger
import com.phamtunglam.health_connector_hc_android.logger.TAG
import com.phamtunglam.health_connector_hc_android.pigeon.AggregateRequestDto
import com.phamtunglam.health_connector_hc_android.pigeon.DeleteRecordsByIdsRequestDto
import com.phamtunglam.health_connector_hc_android.pigeon.DeleteRecordsByTimeRangeRequestDto
import com.phamtunglam.health_connector_hc_android.pigeon.DeleteRecordsRequestDto
import com.phamtunglam.health_connector_hc_android.pigeon.HealthConnectorConfigDto
import com.phamtunglam.health_connector_hc_android.pigeon.HealthConnectorErrorCodeDto
import com.phamtunglam.health_connector_hc_android.pigeon.HealthConnectorErrorDto
import com.phamtunglam.health_connector_hc_android.pigeon.HealthConnectorHCAndroidApi
import com.phamtunglam.health_connector_hc_android.pigeon.HealthPlatformFeatureDto
import com.phamtunglam.health_connector_hc_android.pigeon.HealthPlatformFeatureStatusDto
import com.phamtunglam.health_connector_hc_android.pigeon.HealthPlatformStatusDto
import com.phamtunglam.health_connector_hc_android.pigeon.HealthRecordDto
import com.phamtunglam.health_connector_hc_android.pigeon.MeasurementUnitDto
import com.phamtunglam.health_connector_hc_android.pigeon.PermissionRequestDto
import com.phamtunglam.health_connector_hc_android.pigeon.PermissionRequestResultDto
import com.phamtunglam.health_connector_hc_android.pigeon.PermissionRequestsDto
import com.phamtunglam.health_connector_hc_android.pigeon.PermissionStatusDto
import com.phamtunglam.health_connector_hc_android.pigeon.ReadRecordRequestDto
import com.phamtunglam.health_connector_hc_android.pigeon.ReadRecordsRequestDto
import com.phamtunglam.health_connector_hc_android.pigeon.ReadRecordsResponseDto
import com.phamtunglam.health_connector_hc_android.utils.aggregationMetric
import com.phamtunglam.health_connector_hc_android.utils.dataType
import com.phamtunglam.health_connector_hc_android.utils.endTime
import com.phamtunglam.health_connector_hc_android.utils.startTime
import com.phamtunglam.health_connector_hc_android.utils.toError
import io.flutter.embedding.engine.plugins.FlutterPlugin
import io.flutter.embedding.engine.plugins.activity.ActivityAware
import io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding
import kotlin.coroutines.cancellation.CancellationException
import kotlinx.coroutines.CoroutineDispatcher
import kotlinx.coroutines.CoroutineExceptionHandler
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.SupervisorJob
import kotlinx.coroutines.cancel
import kotlinx.coroutines.launch
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock

/**
 * Flutter plugin for accessing Health Connect on Android devices.
 *
 * This plugin implements the [HealthConnectorHCAndroidApi] interface generated by Pigeon
 * and bridges Flutter/Dart to the Android Health Connect SDK.
 *
 * ## Usage in Production
 *
 * Flutter automatically instantiates this plugin using the default no-argument constructor.
 *
 * ## Usage in Tests
 *
 * ```kotlin
 * val testDispatcher = StandardTestDispatcher()
 * val plugin = HealthConnectorHCAndroidPlugin(ioDispatcher = testDispatcher)
 * plugin.setContext(mockContext)
 * plugin.setActivity(mockActivity)
 * plugin.setClient(mockClient)
 * ```
 */
class HealthConnectorHCAndroidPlugin @VisibleForTesting internal constructor(
    private val ioDispatcher: CoroutineDispatcher,
) : FlutterPlugin,
    ActivityAware,
    HealthConnectorHCAndroidApi {

    /**
     * Default public constructor for Flutter plugin registration.
     *
     * Flutter uses this no-argument constructor to instantiate the plugin.
     * This constructor uses production defaults for all dependencies.
     */
    constructor() : this(
        ioDispatcher = Dispatchers.IO,
    )

    /**
     * Application context used for accessing Health Connect services.
     * Initialized in [onAttachedToEngine] and persists throughout the plugin lifecycle.
     */
    private lateinit var context: Context

    /**
     * The current Flutter activity, required for operations that need activity context.
     * This is nullable because the activity may be detached during configuration changes
     * or when the app is in the background.
     *
     * @see onAttachedToActivity
     * @see onDetachedFromActivity
     */
    private var activity: ComponentActivity? = null

    /**
     * Mutex to ensure thread-safe initialization of [client].
     * Prevents race conditions when multiple concurrent calls to [initialize] attempt
     * to create the client simultaneously.
     */
    private val clientInitMutex: Mutex = Mutex()

    /**
     * Cached instance of [HealthConnectorClient].
     * Created lazily on first use via [initialize] and reused for subsequent operations.
     * Nullable to support testing without requiring full initialization.
     */
    private var client: HealthConnectorClient? = null

    /**
     * Coroutine scope for executing asynchronous Health Connect operations.
     *
     * Uses [ioDispatcher] for background execution and [SupervisorJob] to prevent
     * cancellation of sibling coroutines when one fails.
     */
    private val scope: CoroutineScope = CoroutineScope(
        SupervisorJob() + ioDispatcher + CoroutineExceptionHandler { _, e ->
            HealthConnectorLogger.warning(
                tag = TAG,
                operation = "coroutine_exception_handler",
                message = "Unhandled exception in coroutine scope",
                exception = e,
            )
        },
    )

    // region Flutter/Android lifecycle

    /**
     * Called when the plugin is attached to a Flutter engine.
     *
     * @param flutterPluginBinding Provides access to the Flutter engine and application context
     */
    override fun onAttachedToEngine(flutterPluginBinding: FlutterPlugin.FlutterPluginBinding) {
        context = flutterPluginBinding.applicationContext
        HealthConnectorHCAndroidApi.setUp(flutterPluginBinding.binaryMessenger, this)
    }

    /**
     * Called when the plugin is detached from the Flutter engine.
     *
     * @param binding The Flutter plugin binding being detached
     */
    override fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        HealthConnectorHCAndroidApi.setUp(binding.binaryMessenger, null)
        scope.cancel()
    }

    /**
     * Called when the plugin is attached to a Flutter activity.
     *
     * Validates that the activity is a [ComponentActivity] (required for Health Connect permissions request)
     * and stores it for later use in permission requests.
     *
     * @param binding Provides access to the Flutter activity
     * @throws IllegalStateException if the activity is not a [ComponentActivity]
     */
    @Throws(IllegalStateException::class)
    override fun onAttachedToActivity(binding: ActivityPluginBinding) {
        val activityInstance = binding.activity
        check(activityInstance is ComponentActivity) {
            "Activity must be a ComponentActivity."
        }
        activity = activityInstance
    }

    /**
     * Called when the activity is detached for configuration changes (e.g., screen rotation).
     *
     * Temporarily clears the activity reference. The activity will be reattached via
     * [onReattachedToActivityForConfigChanges] after the configuration change completes.
     */
    override fun onDetachedFromActivityForConfigChanges() {
        activity = null
    }

    /**
     * Called when the activity is reattached after configuration changes.
     *
     * Validates and restores the activity reference after configuration changes like screen rotation.
     *
     * @param binding Provides access to the reattached Flutter activity
     * @throws IllegalStateException if the activity is not a [ComponentActivity]
     */
    @Throws(IllegalStateException::class)
    override fun onReattachedToActivityForConfigChanges(binding: ActivityPluginBinding) {
        val activityInstance = binding.activity
        check(activityInstance is ComponentActivity) {
            "Activity must be a ComponentActivity"
        }
        activity = activityInstance
    }

    /**
     * Called when the activity is detached from the plugin.
     *
     * This is a permanent detachment (not due to configuration changes).
     * Clears the activity reference to prevent memory leaks.
     */
    override fun onDetachedFromActivity() {
        activity = null
    }

    // endregion

    // region Plugin API

    /**
     * Initializes the Health Connector client with the provided configuration.
     *
     * This method must be called before any other Health Connector operations
     * to properly configure the native platform code, including logger settings.
     *
     * @param config Configuration settings for the Health Connector
     * @param callback Called with a [Result] indicating success or failure
     */
    override fun initialize(config: HealthConnectorConfigDto, callback: (Result<Unit>) -> Unit) {
        scope.launch {
            HealthConnectorLogger.debug(
                tag = TAG,
                operation = "create",
                message = "Creating ${HealthConnectorClient.TAG}...",
                context = mapOf("is_logger_enabled" to config.isLoggerEnabled.toString()),
            )

            try {
                clientInitMutex.withLock {
                    if (client == null) {
                        client = HealthConnectorClient.getOrCreate(context)
                    }
                }

                HealthConnectorLogger.setEnabled(config.isLoggerEnabled)

                HealthConnectorLogger.debug(
                    tag = TAG,
                    operation = "create",
                    message = "${HealthConnectorClient.TAG} initialized successfully",
                    context = mapOf("is_logger_enabled" to config.isLoggerEnabled.toString()),
                )

                callback(Result.success(Unit))
            } catch (e: HealthConnectorErrorDto) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "create",
                    message = "Failed to create ${HealthConnectorClient.TAG}",
                    context = mapOf(
                        "error_code" to e.code,
                        "error_message" to (e.message ?: "Unknown error"),
                    ),
                    exception = e,
                )

                callback(Result.failure(e))
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "create",
                    message = "Unexpected error during initialization",
                    context = mapOf("is_logger_enabled" to config.isLoggerEnabled.toString()),
                    exception = e,
                )
                callback(
                    Result.failure(
                        HealthConnectorErrorCodeDto.UNKNOWN.toError(
                            "Unexpected error: ${e.message ?: "Unknown error"}",
                        ),
                    ),
                )
            }
        }
    }

    /**
     * Launches the Health Connect app page in the Google Play Store.
     *
     * Opens the Google Play Store application to the Health Connect app's detail page,
     * allowing users to install or update the app. This method should be called when
     * [getHealthPlatformStatus] indicates that Health Connect installation or update is required.
     *
     * @param callback Called with a [Result] indicating success or failure
     *
     * @throws HealthConnectorErrorDto if the Play Store cannot be launched or activity is unavailable
     */
    override fun launchHealthConnectPageInGooglePlay(callback: (Result<Unit>) -> Unit) {
        try {
            val currentActivity = activity
            if (currentActivity == null) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "launch_health_connect_page_in_google_play",
                    message = "Cannot launch Play Store without activity context",
                )

                callback(
                    Result.failure(
                        HealthConnectorErrorCodeDto.INVALID_CONFIGURATION.toError(
                            "Activity is unavailable. " +
                                "The app may be in the background or " +
                                "activity has been destroyed.",
                        ),
                    ),
                )

                return
            }

            HealthConnectorClient.launchHealthConnectPageInGooglePlay(currentActivity)

            callback(Result.success(Unit))
        } catch (e: HealthConnectorErrorDto) {
            HealthConnectorLogger.error(
                tag = TAG,
                operation = "launch_health_connect_page_in_google_play",
                message = "Failed to launch Health Connect page in Google Play",
                context = mapOf(
                    "error_code" to e.code,
                    "error_message" to (e.message ?: "Unknown error"),
                ),
                exception = e,
            )

            callback(Result.failure(e))
        } catch (e: Exception) {
            HealthConnectorLogger.error(
                tag = TAG,
                operation = "launch_health_connect_page_in_google_play",
                message = "Unexpected error while launching Play Store",
                exception = e,
            )

            callback(
                Result.failure(
                    HealthConnectorErrorCodeDto.UNKNOWN.toError(
                        "Failed to launch Play Store: ${e.message ?: "Unknown error"}",
                    ),
                ),
            )
        }
    }

    /**
     * Gets the current status of the Health Connect platform on the device.
     *
     * @param callback Called with a [Result] containing the platform status
     */
    override fun getHealthPlatformStatus(callback: (Result<HealthPlatformStatusDto>) -> Unit) {
        scope.launch {
            try {
                val statusDto = HealthConnectorClient.getHealthPlatformStatus(context)

                callback(Result.success(statusDto))
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "get_health_platform_status",
                    message = "Unexpected error while getting platform status",
                    exception = e,
                )
                callback(
                    Result.failure(
                        HealthConnectorErrorCodeDto.UNKNOWN.toError(
                            "Unexpected error: ${e.message ?: "Unknown error"}",
                        ),
                    ),
                )
            }
        }
    }

    /**
     * Requests permissions from the user.
     *
     * Requires an active [ComponentActivity].
     *
     * @param request The permissions request containing both health data and feature permissions
     * @param callback Called with a [Result] containing the permission request response
     */
    @Throws(HealthConnectorErrorDto::class)
    override fun requestPermissions(
        request: PermissionRequestsDto,
        callback: (Result<List<PermissionRequestResultDto>>) -> Unit,
    ) {
        scope.launch {
            try {
                val currentActivity = activity
                if (currentActivity == null) {
                    HealthConnectorLogger.error(
                        tag = TAG,
                        operation = "request_permissions",
                        message = "Activity is null. " +
                            "Cannot request permissions without activity context",
                    )

                    callback(
                        Result.failure(
                            HealthConnectorErrorCodeDto.INVALID_CONFIGURATION.toError(
                                "Activity is unavailable. " +
                                    "The app may be in the background or " +
                                    "activity has been destroyed.",
                            ),
                        ),
                    )

                    return@launch
                }

                val responseDto = requireClient().requestPermissions(
                    activity = currentActivity,
                    request = request,
                )

                callback(Result.success(responseDto))
            } catch (e: HealthConnectorErrorDto) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "request_permissions",
                    message = "Failed to request Health Connect permissions",
                    context = mapOf(
                        "error_code" to e.code,
                        "error_message" to (e.message ?: "Unknown error"),
                    ),
                    exception = e,
                )

                callback(Result.failure(e))
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "request_permissions",
                    message = "Unexpected error while requesting permissions",
                    context = mapOf("requested_permissions" to request.permissionRequests),
                    exception = e,
                )
                callback(
                    Result.failure(
                        HealthConnectorErrorCodeDto.UNKNOWN.toError(
                            "Unexpected error: ${e.message ?: "Unknown error"}",
                        ),
                    ),
                )
            }
        }
    }

    /**
     * Gets the current permission status for a specific permission.
     *
     * @param request The permission to check
     * @param callback Called with a [Result] containing the permission status
     */
    @Throws(HealthConnectorErrorDto::class)
    override fun getPermissionStatus(
        request: PermissionRequestDto,
        callback: (Result<PermissionStatusDto>) -> Unit,
    ) {
        scope.launch {
            try {
                val statusDto = requireClient().getPermissionStatus(request)

                callback(Result.success(statusDto))
            } catch (e: HealthConnectorErrorDto) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "get_permission_status",
                    message = "Failed to get permission status",
                    context = mapOf(
                        "permission" to request.toString(),
                        "error_code" to e.code,
                        "error_message" to (e.message ?: "Unknown error"),
                    ),
                    exception = e,
                )

                callback(Result.failure(e))
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "get_permission_status",
                    message = "Unexpected error while getting permission status",
                    context = mapOf("permission" to request),
                    exception = e,
                )
                callback(
                    Result.failure(
                        HealthConnectorErrorCodeDto.UNKNOWN.toError(
                            "Unexpected error: ${e.message ?: "Unknown error"}",
                        ),
                    ),
                )
            }
        }
    }

    /**
     * Gets all permissions that have been granted to the app.
     *
     * @param callback Called with a [Result] containing the permission response
     */
    @Throws(HealthConnectorErrorDto::class)
    override fun getGrantedPermissions(
        callback: (Result<List<PermissionRequestResultDto>>) -> Unit,
    ) {
        scope.launch {
            try {
                val responseDto = requireClient().getGrantedPermissions()

                callback(Result.success(responseDto))
            } catch (e: HealthConnectorErrorDto) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "get_granted_permissions",
                    message = "Failed to get granted Health Connect permissions",
                    context = mapOf(
                        "error_code" to e.code,
                        "error_message" to (e.message ?: "Unknown error"),
                    ),
                    exception = e,
                )

                callback(Result.failure(e))
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "get_granted_permissions",
                    message = "Unexpected error while getting granted permissions",
                    exception = e,
                )
                callback(
                    Result.failure(
                        HealthConnectorErrorCodeDto.UNKNOWN.toError(
                            "Unexpected error: ${e.message ?: "Unknown error"}",
                        ),
                    ),
                )
            }
        }
    }

    /**
     * Revokes all permissions that have been granted to the app.
     *
     * @param callback Called with a [Result] containing the operation result
     */
    @Throws(HealthConnectorErrorDto::class)
    override fun revokeAllPermissions(callback: (Result<Unit>) -> Unit) {
        scope.launch {
            try {
                requireClient().revokeAllPermissions()

                callback(Result.success(Unit))
            } catch (e: HealthConnectorErrorDto) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "revoke_all_permissions",
                    message = "Failed to revoke all Health Connect permissions",
                    context = mapOf(
                        "error_code" to e.code,
                        "error_message" to (e.message ?: "Unknown error"),
                    ),
                    exception = e,
                )

                callback(Result.failure(e))
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "revoke_all_permissions",
                    message = "Unexpected error while revoking all permissions",
                    exception = e,
                )
                callback(
                    Result.failure(
                        HealthConnectorErrorCodeDto.UNKNOWN.toError(
                            "Unexpected error: ${e.message ?: "Unknown error"}",
                        ),
                    ),
                )
            }
        }
    }

    /**
     * Gets the status of a specific feature on the current platform.
     *
     * @param feature The feature to check availability for
     * @param callback Called with a [Result] containing the feature status
     */
    @Throws(HealthConnectorErrorDto::class)
    override fun getFeatureStatus(
        feature: HealthPlatformFeatureDto,
        callback: (Result<HealthPlatformFeatureStatusDto>) -> Unit,
    ) {
        scope.launch {
            try {
                val featureStatusDto = requireClient().getFeatureStatus(context, feature)

                callback(Result.success(featureStatusDto))
            } catch (e: HealthConnectorErrorDto) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "get_feature_status",
                    message = "Failed to get Health Connect feature status",
                    context = mapOf(
                        "feature" to feature.toString(),
                        "error_code" to e.code,
                        "error_message" to (e.message ?: "Unknown error"),
                    ),
                    exception = e,
                )

                callback(Result.failure(e))
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "get_feature_status",
                    message = "Unexpected error while getting feature status",
                    context = mapOf("feature" to feature.toString()),
                    exception = e,
                )
                callback(
                    Result.failure(
                        HealthConnectorErrorCodeDto.UNKNOWN.toError(
                            "Unexpected error: ${e.message ?: "Unknown error"}",
                        ),
                    ),
                )
            }
        }
    }

    /**
     * Reads a single health record by ID.
     *
     * @param request Contains the data type and record ID to read
     * @param callback Called with a [Result] containing the read record response or null if not found
     */
    @Throws(HealthConnectorErrorDto::class)
    override fun readRecord(
        request: ReadRecordRequestDto,
        callback: (Result<HealthRecordDto?>) -> Unit,
    ) {
        scope.launch {
            try {
                val result = requireClient().readRecord(request)

                callback(Result.success(result))
            } catch (e: HealthConnectorErrorDto) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "read_record",
                    message = "Failed to read Health Connect record",
                    context = mapOf(
                        "data_type" to request.dataType.toString(),
                        "record_id" to request.recordId,
                        "error_code" to e.code,
                        "error_message" to (e.message ?: "Unknown error"),
                    ),
                    exception = e,
                )

                callback(Result.failure(e))
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "read_record",
                    message = "Unexpected error escaped from handler",
                    context = mapOf("request" to request),
                    exception = e,
                )
                callback(
                    Result.failure(
                        HealthConnectorErrorCodeDto.UNKNOWN.toError(
                            "Unexpected error: ${e.message ?: "Unknown error"}",
                        ),
                    ),
                )
            }
        }
    }

    /**
     * Reads multiple health records within a time range.
     *
     * @param request Contains data type, time range, page size, and optional page token
     * @param callback Called with a [Result] containing the read records response
     */
    @Throws(HealthConnectorErrorDto::class)
    override fun readRecords(
        request: ReadRecordsRequestDto,
        callback: (Result<ReadRecordsResponseDto>) -> Unit,
    ) {
        scope.launch {
            try {
                val result = requireClient().readRecords(request)

                callback(Result.success(result))
            } catch (e: HealthConnectorErrorDto) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "read_records",
                    message = "Failed to read Health Connect records",
                    context = mapOf(
                        "data_type" to request.dataType.toString(),
                        "start_time" to request.startTime,
                        "end_time" to request.endTime,
                        "page_size" to request.pageSize,
                        "error_code" to e.code,
                        "error_message" to (e.message ?: "Unknown error"),
                    ),
                    exception = e,
                )

                callback(Result.failure(e))
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "read_records",
                    message = "Unexpected error escaped from handler",
                    context = mapOf("request" to request),
                    exception = e,
                )
                callback(
                    Result.failure(
                        HealthConnectorErrorCodeDto.UNKNOWN.toError(
                            "Unexpected error: ${e.message ?: "Unknown error"}",
                        ),
                    ),
                )
            }
        }
    }

    /**
     * Writes a single health record.
     *
     * @param record The record to write
     * @param callback Called with a [Result] containing the new record ID
     */
    @Throws(HealthConnectorErrorDto::class)
    override fun writeRecord(record: HealthRecordDto, callback: (Result<String>) -> Unit) {
        scope.launch {
            try {
                val id = requireClient().writeRecord(record)

                callback(Result.success(id))
            } catch (e: HealthConnectorErrorDto) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "write_record",
                    message = "Failed to write Health Connect record",
                    context = mapOf(
                        "error_code" to e.code,
                        "error_message" to (e.message ?: "Unknown error"),
                    ),
                    exception = e,
                )

                callback(Result.failure(e))
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "write_record",
                    message = "Unexpected error escaped from handler",
                    context = mapOf("record" to record),
                    exception = e,
                )
                callback(
                    Result.failure(
                        HealthConnectorErrorCodeDto.UNKNOWN.toError(
                            "Unexpected error: ${e.message ?: "Unknown error"}",
                        ),
                    ),
                )
            }
        }
    }

    /**
     * Writes multiple health records atomically.
     *
     * @param records The list of records to write
     * @param callback Called with a [Result] containing the list of IDs
     */
    @Throws(HealthConnectorErrorDto::class)
    override fun writeRecords(
        records: List<HealthRecordDto>,
        callback: (Result<List<String>>) -> Unit,
    ) {
        scope.launch {
            try {
                val ids = requireClient().writeRecords(records)

                callback(Result.success(ids))
            } catch (e: HealthConnectorErrorDto) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "write_records",
                    message = "Failed to write Health Connect records",
                    context = mapOf(
                        "records_count" to records.size,
                        "error_code" to e.code,
                        "error_message" to (e.message ?: "Unknown error"),
                    ),
                    exception = e,
                )

                callback(Result.failure(e))
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "write_records",
                    message = "Unexpected error escaped from handler",
                    context = mapOf("records" to records),
                    exception = e,
                )
                callback(
                    Result.failure(
                        HealthConnectorErrorCodeDto.UNKNOWN.toError(
                            "Unexpected error: ${e.message ?: "Unknown error"}",
                        ),
                    ),
                )
            }
        }
    }

    /**
     * Updates a single health record.
     *
     * @param record The record to update
     * @param callback Called with a [Result] indicating success or failure
     */
    @Throws(HealthConnectorErrorDto::class)
    override fun updateRecord(record: HealthRecordDto, callback: (Result<Unit>) -> Unit) {
        scope.launch {
            try {
                requireClient().updateRecord(record)

                callback(Result.success(Unit))
            } catch (e: HealthConnectorErrorDto) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "update_record",
                    message = "Failed to update Health Connect record",
                    context = mapOf(
                        "error_code" to e.code,
                        "error_message" to (e.message ?: "Unknown error"),
                    ),
                    exception = e,
                )

                callback(Result.failure(e))
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "update_record",
                    message = "Unexpected error escaped from handler",
                    context = mapOf("record" to record),
                    exception = e,
                )
                callback(
                    Result.failure(
                        HealthConnectorErrorCodeDto.UNKNOWN.toError(
                            "Unexpected error: ${e.message ?: "Unknown error"}",
                        ),
                    ),
                )
            }
        }
    }

    /**
     * Updates multiple health records atomically.
     *
     * @param records The list of records to update
     * @param callback Called with a [Result] indicating success or failure
     */
    @Throws(HealthConnectorErrorDto::class)
    override fun updateRecords(records: List<HealthRecordDto>, callback: (Result<Unit>) -> Unit) {
        scope.launch {
            try {
                requireClient().updateRecords(records)

                callback(Result.success(Unit))
            } catch (e: HealthConnectorErrorDto) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "update_records",
                    message = "Failed to update Health Connect records",
                    context = mapOf(
                        "records_count" to records.size,
                        "error_code" to e.code,
                        "error_message" to (e.message ?: "Unknown error"),
                    ),
                    exception = e,
                )

                callback(Result.failure(e))
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "update_records",
                    message = "Unexpected error escaped from handler",
                    context = mapOf("records" to records),
                    exception = e,
                )
                callback(
                    Result.failure(
                        HealthConnectorErrorCodeDto.UNKNOWN.toError(
                            "Unexpected error: ${e.message ?: "Unknown error"}",
                        ),
                    ),
                )
            }
        }
    }

    /**
     * Deletes health records based on the request type.
     *
     * @param request The deletion request (either by IDs or time range)
     * @param callback Called with a [Result] indicating success or failure
     */
    override fun deleteRecords(
        request: DeleteRecordsRequestDto,
        callback: (Result<Unit>) -> Unit,
    ) {
        scope.launch {
            try {
                val healthClient = requireClient()
                when (request) {
                    is DeleteRecordsByIdsRequestDto -> healthClient.deleteRecordsByIds(request)
                    is DeleteRecordsByTimeRangeRequestDto -> healthClient.deleteRecordsByTimeRange(
                        request,
                    )
                }

                callback(Result.success(Unit))
            } catch (e: HealthConnectorErrorDto) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "delete_records",
                    message = "Failed to delete Health Connect records",
                    context = mapOf(
                        "request_type" to request.javaClass.simpleName,
                        "error_code" to e.code,
                        "error_message" to (e.message ?: "Unknown error"),
                    ),
                    exception = e,
                )

                callback(Result.failure(e))
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "delete_records",
                    message = "Unexpected error escaped from handler",
                    context = mapOf("request" to request.toString()),
                    exception = e,
                )
                callback(
                    Result.failure(
                        HealthConnectorErrorCodeDto.UNKNOWN.toError(
                            "Unexpected error: ${e.message ?: "Unknown error"}",
                        ),
                    ),
                )
            }
        }
    }

    /**
     * Performs an aggregation query on health records.
     *
     * @param request Contains data type, aggregation metric, and time range
     * @param callback Called with a [Result] containing the aggregation response
     */
    @Throws(HealthConnectorErrorDto::class)
    override fun aggregate(
        request: AggregateRequestDto,
        callback: (Result<MeasurementUnitDto>) -> Unit,
    ) {
        scope.launch {
            try {
                val result = requireClient().aggregate(request)

                callback(Result.success(result))
            } catch (e: HealthConnectorErrorDto) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "aggregate",
                    message = "Failed to aggregate Health Connect data",
                    context = mapOf(
                        "data_type" to request.dataType.toString(),
                        "aggregation_metric" to request.aggregationMetric.toString(),
                        "start_time" to request.startTime,
                        "end_time" to request.endTime,
                        "error_code" to e.code,
                        "error_message" to (e.message ?: "Unknown error"),
                    ),
                    exception = e,
                )

                callback(Result.failure(e))
            } catch (e: CancellationException) {
                throw e
            } catch (e: Exception) {
                HealthConnectorLogger.error(
                    tag = TAG,
                    operation = "aggregate",
                    message = "Unexpected error escaped from handler",
                    context = mapOf("request" to request),
                    exception = e,
                )
                callback(
                    Result.failure(
                        HealthConnectorErrorCodeDto.UNKNOWN.toError(
                            "Unexpected error: ${e.message ?: "Unknown error"}",
                        ),
                    ),
                )
            }
        }
    }

    // endregion

    // region Private/internal methods

    /**
     * Sets the application context for testing purposes.
     *
     * This allows tests to inject a mock context without going through
     * the Flutter plugin lifecycle.
     *
     * @param context The context to use for Health Connect operations
     */
    @VisibleForTesting
    internal fun setContext(context: Context) {
        this.context = context
    }

    /**
     * Sets the Health Connect client for testing purposes.
     *
     * This allows tests to inject a mock client without calling [initialize].
     *
     * @param client The client to use for Health Connect operations
     */
    @VisibleForTesting
    internal fun setClient(client: HealthConnectorClient) {
        this.client = client
    }

    /**
     * Sets the activity for testing purposes.
     *
     * This allows tests to inject a mock activity without going through
     * the Flutter activity lifecycle.
     *
     * @param activity The activity to use for permission requests
     */
    @VisibleForTesting
    internal fun setActivity(activity: ComponentActivity?) {
        this.activity = activity
    }

    /**
     * Returns the [HealthConnectorClient] instance, or throws if not initialized.
     *
     * @return The initialized Health Connect client
     * @throws HealthConnectorErrorDto if the client has not been initialized
     */
    private fun requireClient(): HealthConnectorClient =
        client ?: throw HealthConnectorErrorCodeDto.INVALID_CONFIGURATION.toError(
            "Plugin not initialized. Call `initialize()` before using any API.",
        )

    // endregion
}
