name: health_connector_hc_android_example
resolution: workspace
description: "Demonstrates how to use the health_connector_hc_android plugin."
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  health_connector_hc_android:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  health_connector_lint: ^0.1.1
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
