name: health_connector_hc_android_example
resolution: workspace
description: "Demonstrates how to use the health_connector_hc_android plugin."
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  health_connector_core: ^1.0.0
  health_connector_hc_android: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  health_connector_lint: ^1.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
