name: 'Setup Melos'
description: 'Setup Melos for monorepo management (requires Flutter to be installed)'

runs:
  using: 'composite'
  steps:
    - name: Setup Melos
      uses: bluefireteam/melos-action@8cca19067d5bc4021b5a9f4656955d8b386583bf # v3
