name: CI - health_connector

on:
  push:
    branches: [ main ]
    paths: &main_paths
      - 'packages/health_connector/**'
      - 'packages/health_connector_core/**'
      - 'packages/health_connector_hc_android/**'
      - 'packages/health_connector_hk_ios/**'
      - 'packages/health_connector_logger/**'
      - '.github/workflows/**'
  pull_request:
    types: [ opened, reopened, synchronize, ready_for_review ]
    paths: *main_paths
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dart-quality:
    uses: ./.github/workflows/_reusable-dart-quality.yaml
    with:
      package-scope: health_connector

  dart-tests:
    needs: [ dart-quality ]
    uses: ./.github/workflows/_reusable-dart-tests.yaml
    with:
      package-scope: health_connector

  build-android:
    needs: [ dart-tests ]
    uses: ./.github/workflows/_reusable-build-android.yaml
    with:
      package-path: packages/health_connector

  build-ios:
    needs: [ dart-tests ]
    uses: ./.github/workflows/_reusable-build-ios.yaml
    with:
      package-path: packages/health_connector
